### ISSUE TITLE
ERROR: Can not perform a '--user' install. User site-packages are not visible in this virtualenv.

### ISSUE THREAD

**Issue by wereket** [emacs-eaf/emacs-application-framework#1000]
Running pip install --user -U epc tld lxml PyQt6 PyQt6-Qt6 PyQt6-sip PyQt6-WebEngine PyQt6-WebEngine-Qt6 @ /home/perrierjouet/.emacs.d/site-elisp/emacs-application-framework
ERROR: Can not perform a '--user' install. User site-packages are not visible in this virtualenv.

**Comment by manateelazycat** [comment]
https://github.com/emacs-eaf/emacs-application-framework/wiki/Python-Virtual-Environment
