### ISSUE TITLE
eaf-browser opens up in a separate window outside emacs frame when emacs is opened in full screen.

### ISSUE THREAD

**Issue by RidaEn-nasry** [emacs-eaf/emacs-application-framework#1004]
**Describe the bug**
After following the installation instructions in official github repo, i tried lunching eaf browser using `eaf-open-browser` and/or `eaf-open-browser-other-window` which actually opens the browser but in a separate window outside emacs frame. the interesting thing is when i go out of full screen and try again `eaf-open-browser` or/and  `eaf-open-browser-other-window`  , the bug semi-resolves and the browser show embedded in emacs but as i move right/left emacs the browser frame still in it's initial place.

**To Reproduce**
 * open emacs full screen.
 * lunch `eaf-open-browser` or `emcas-open-browser-other-window`

**Expected behavior**
eaf browser showing inside emacs frame.

**Versions (please complete the following info):**
- Macbook air m1 monterey 12.5
 - GNU Emacs 28.1 (build 1, aarch64-apple-darwin21.1.0, NS appkit-2113.00 Version 12.0.1 (Build 21A559)) of 2022-05-11

**Error logs**
Please install app-frontmost from https://pypi.org/project/mac-app-frontmost/ to make EAF works with macOS 
NOTE i have the specific package installed .

**Screenshots**
Here emacs is full screen in another window while eaf browser is opened here.
<img width="1440" alt="Screen Shot 2022-09-09 at 16 28 50" src="https://user-images.githubusercontent.com/65143740/189386643-9f5f1258-89fc-4f6a-96bf-2d40113f533a.png">
Here emacs is not full screen so the eaf browser behaves correctly and show inside the emacs frame. 
<img width="1438" alt="Screen Shot 2022-09-09 at 16 31 18" src="https://user-images.githubusercontent.com/65143740/189387119-af586c80-bc6c-4a35-a244-0d4e12a26c4f.png">
However when i move emacs window using cursor eaf browser doesn't follow and stays in it's initial place , here i move emacs window a bit to the right and this happened : 
<img width="1025" alt="Screen Shot 2022-09-09 at 16 33 02" src="https://user-images.githubusercontent.com/65143740/189387466-21c87c47-6167-4996-a896-29ef0b1b112c.png">

**Additional context**
The error in the minibuffer may have something to do with the problem ???

**Comment by MatthewZMD** [comment]
There are known issues in https://github.com/emacs-eaf/emacs-application-framework/wiki/macOS , let me know if your issues matches the ones in the Wiki. If you have a fix proposal please let us know and I will re-open the issue.
