### ISSUE TITLE
EAF浏览器的openlink操作不能穿透<iframe>。

### ISSUE THREAD

**Issue by icezyj** [emacs-eaf/emacs-application-framework#1021]
**Describe the bug**
EAF浏览器键盘操作是，按下f键后，位于<iframe>.....</iframe>内的所有按键和链接都没有检测到，旁边没有显示按键提示，不能通过按键打开链接。

**Screenshots**
![Screenshot_2022-10-19-00_1920x1080](https://user-images.githubusercontent.com/40057994/196607350-675c372b-cb19-47fc-aa21-704df2d44b38.png)
右面运行结果里的输入框和“提交”按键都没有检测到，但是用其它浏览器的vimium插件就可以。

**Comment by manateelazycat** [comment]
@MatthewZMD  https://www.runoob.com/try/try.php?filename=tryjs_validation_html 是这个地址

**Comment by MatthewZMD** [comment]
不好搞，通过更改getVisibleElements可以让它识别出iframe里面的内容，但css selector进不去iframe，改起来太麻烦了，为一个网站不值得。

给你看我目前的改动，剩下的欢迎PR
```
modified   core/js/marker.js
@@ -4,6 +4,12 @@ try {
 
     function getVisibleElements(filter) {
         let all = Array.from(document.documentElement.getElementsByTagName("*"));
+        let iframes = document.getElementsByTagName('iframe');
+        let all_iframes = [];
+        for (let i = 0; i < iframes.length; i++) {
+            all_iframes = all_iframes.concat(Array.from(iframes[i].contentWindow.document.getElementsByTagName("*")));
+        }
+        all = all.concat(all_iframes);
         let visibleElements = [];
         for (let i = 0; i < all.length; i++) {
             let e = all[i];
```
