### ISSUE TITLE
pdf-viewer在debian系的操作系统下无法启动

### ISSUE THREAD

**Issue by Allinaent** [emacs-eaf/emacs-application-framework#1022]
emacs -q使用最小配置也报错。

```
Buffer id '{}' not exists, rebuild EAF buffer
```
我不清楚您是否在ubuntu，debain或者UOS下做过适配。但我在archlinux下也browser也遇到过类似问题。

我打开了
```
(setq eaf-enable-debug t)
```
但是没有打印任何信息。我有时候不能用archlinux，开发者能不在ubuntu下调试一下安装脚本，我认
为一个好用的安装过程对debian下的普通用户很有用。

或者把调试方法写出来，我来补充更多的信息。

**Comment by manateelazycat** [comment]
调试方法README写的有， 你安装了 gdb 了吗？

**Comment by Allinaent** [comment]
问题解决了，说一下我的解决过程：

1.在eaf中看到了python少frontend这个模块，python3.7不能安装这个模块。换了python3.9

2../install-eaf.py --install pdf-viewer --use-gitee --force

**Comment by manateelazycat** [comment]
建议用emacs 28，用EAF效果最好。

这是社区项目，不是商业项目，没有啥加快开发一说，都是社区开发者有时间就改进一下。

所以不要期望太高。

**Comment by AKmatiAK** [comment]
For english readers: You need to do this in cmd:
pip uninstall pymupdf
pip uninstall fitz
pip install fitz
pip install pymupdf

because fitz must be installed before pymupdf
