### ISSUE TITLE
The buffer of EAF will block part of the bottom column of emacs

### ISSUE THREAD

**Issue by AndyVerne** [emacs-eaf/emacs-application-framework#1025]
**Describe the bug**
The buffer of EAF will block part of the bottom column of emacs like the image shows below.

**To Reproduce**
Not sure how to reproduce, but the operating environment is MacOS Ventura (intel version), Emacs version is 28.2.

**Expected behavior**
Hope the EAF buffer shows as normal buffer.

**Versions (please complete the following info):**
 The operating environment is MacOS Ventura (intel version), Emacs version is 28.2.

**Screenshots**
![image](https://user-images.githubusercontent.com/23656398/198236394-f0a42f3f-ac9b-44ba-8059-63f85c1fd131.png)

**Comment by AndyVerne** [comment]
It has been solved, change "**32**" to "**20**" in ***defun eaf--get-titlebar-height ()*** under **eaf.el** file, the occlusion problem is solved

**Comment by MatthewZMD** [comment]
Duplicate of #1024 , it has been resolved in the latest version.
