### ISSUE TITLE
Can you change background color for darkreader?

### ISSUE THREAD

**Issue by niv-dev** [emacs-eaf/emacs-application-framework#1026]
I tried to edit darkreader.js, but the color remains normal, is there any way to have a custom background color? thanks!

**Comment by manateelazycat** [comment]
https://github.com/emacs-eaf/emacs-application-framework/blob/f97b9a8d373662a5a13e0c080e81c229707df225/core/webengine.py#L723

**Comment by niv-dev** [comment]
hi sorry, im not sure how you can add the background color, do you just make a variable?

**Comment by manateelazycat** [comment]
you can change source code, if can work, we can add elisp var for customize purpose

**Comment by manateelazycat** [comment]
> brightness: 100, contrast: 90, sepia: 10,

You just need change `brightness: 100, contrast: 90, sepia: 10` to change color.
