### ISSUE TITLE
Could not load the Qt platform plugin "xcb" 

### ISSUE THREAD

**Issue by faust45** [emacs-eaf/emacs-application-framework#1027]
Need your help!

qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vkkhrdisplay, vnc, wayland-egl, wayland, xcb.

Process *eaf* aborted

**Comment by manateelazycat** [comment]
read readme carefully

**Comment by faust45** [comment]
i have, but still have no idea
i installed all debs manually on guix i use X11 not wayland

**Comment by manateelazycat** [comment]
https://github.com/emacs-eaf/emacs-application-framework#report-bug

**Comment by manateelazycat** [comment]
use gdb , follow readme, then paste content of `*eaf*`

**Comment by faust45** [comment]
yes in case of segfault error they ask for gdb, but i have no seg fault err
and i have already posted *eaf* buffer

**Comment by faust45** [comment]
i have set QT_DEBUG_PLUGINS=1
after i got more detailed err description at *eaf* buffer so i was able to install missed .so libs
may be you can put this QT_DEBUG_PLUGINS=1 
to readme

**Comment by manateelazycat** [comment]
its qt is not install correctly, i have no idea, its not bug of EAF

**Comment by 0xsuk** [comment]
I had the same error on Ubuntu 22.04 and solved it by installing missing dependency.

First you need to figure out where pip installed libqxcb.so. In my case (most of the time I guess) it is ~/.local/lib/python3.10/site-packages/PyQt6/Qt6/plugins/platforms/libqxcb.so. I found this by running `find -type f -name *xcb* ` in ~/.local/.

Then find missing dependency with `ldd  ~/.local/lib/python3.10/site-packages/PyQt6/Qt6/plugins/platforms/libqxcb.so | grep not`

In my case libxcb-cursor.so.0 is not found, so I installed it `sudo apt install libxcb-cursor0`
