### ISSUE TITLE
QT_FONT_DPI: small font when open external GUI applitions in HiDPI screen

### ISSUE THREAD

**Issue by ybyygu** [emacs-eaf/emacs-application-framework#1029]
**Describe the bug**
When open external GUI application such as libreoffice, the display font is too small for HiDPI screen.

I found this is caused by QT_FONT_DPI env var which is set by eaf:
https://github.com/emacs-eaf/emacs-application-framework/blob/9e930fd128709f2f5135135714bf159ec7cbe525/eaf.el#L659

**To Reproduce**
open libreoffce in emacs

> M-! libreoffice

**Expected behavior**
The normal size font

**Versions (please complete the following info):**
 - Distro and DE/WM: KDE
 - Versions of Dependencies:
 - M-x emacs-version: 28.2

**Error logs**
Please check the `*eaf*` buffer, if there is any error in it, paste it here.

**Screenshots**
before
![image](https://user-images.githubusercontent.com/128990/202067461-99cc880b-1e27-493e-937c-5f46340c5d9f.png)

after unset QT_FONT_DPI env var:

![image](https://user-images.githubusercontent.com/128990/202067832-a87365fe-18c6-4f85-94af-69c2e7ff8b0f.png)

**Additional context**

**Comment by manateelazycat** [comment]
I have commit https://github.com/emacs-eaf/emacs-application-framework/commit/3bc9c731e02651353cfc48c4f855b733f7033985

Can you try again? Thanks for report.

**Comment by ybyygu** [comment]
Thank you! It works now.
