### ISSUE TITLE
PyQt6 on NixOs

### ISSUE THREAD

**Issue by madorian** [emacs-eaf/emacs-application-framework#1030]
**Describe the bug**
```
Process *eaf* exited abnormally with code 1
Traceback (most recent call last):\0
  File "/home/b0ef/.emacs.d/site-lisp/emacs-application-framework/eaf.py", line 25, in <module>
    from PyQt6 import QtWebEngineWidgets as NeverUsed # noqa
ImportError: cannot import name 'QtWebEngineWidgets' from 'PyQt6' (/nix/store/awam08nk598vvxj5v1sng0jpn7yj10kk-python3-3.10.8-env/lib/python3.10/site-packages/PyQt6/__init__.py)

Process *eaf* exited abnormally with code 1
```
**Versions (please complete the following info):**
 - Distro and DE/WM: NixOs 22.05 with Python from Unstable
 - M-x emacs-version: 28.1

I'm installing Python like this: 

```
with pkgs;
let
  my-python-packages = python-packages: with python-packages; [
    pandas
    requests
    pyqt6 sip qtpy qt6.qtwebengine epc lxml # for eaf
    qrcode # eaf-file-browser
    pysocks # eaf-browser
    pymupdf # eaf-pdf-viewer
    pypinyin # eaf-file-manager
    psutil # eaf-system-monitor
    retry # eaf-markdown-previewer
    markdown
  ];
  python-with-my-packages = unstable.python3.withPackages my-python-packages;

```

**Comment by manateelazycat** [comment]
You need report this bug to NixOS developer, if you can't install PyQt6 on NixOS, EAF can't start.

It's not a bug of EAF.

**Comment by madorian** [comment]
ok, got it working. 

Here's the correct declaration for NixOs-22.05

```
with pkgs;
let
  my-python-packages = python-packages: with python-packages; [
    pandas
    requests
    pyqt6 sip qtpy qt6.qtwebengine epc lxml pyqt6-webengine # for eaf
    qrcode # eaf-file-browser
    pysocks # eaf-browser
    pymupdf # eaf-pdf-viewer
    pypinyin # eaf-file-manager
    psutil # eaf-system-monitor
    retry # eaf-markdown-previewer
    markdown
  ];
  python-with-my-packages = unstable.python3.withPackages my-python-packages;

```
Should probably add that to the wiki

Thanks;)

**Comment by manateelazycat** [comment]
> ok, got it working.
> 
> Here's the correct declaration for NixOs-22.05
> 
> ```
> with pkgs;
> let
>   my-python-packages = python-packages: with python-packages; [
>     pandas
>     requests
>     pyqt6 sip qtpy qt6.qtwebengine epc lxml pyqt6-webengine # for eaf
>     qrcode # eaf-file-browser
>     pysocks # eaf-browser
>     pymupdf # eaf-pdf-viewer
>     pypinyin # eaf-file-manager
>     psutil # eaf-system-monitor
>     retry # eaf-markdown-previewer
>     markdown
>   ];
>   python-with-my-packages = unstable.python3.withPackages my-python-packages;
> ```
> 
> Should probably add that to the wiki
> 
> Thanks;)

Done, thanks for reply. ;)
