### ISSUE TITLE
eaf.py cannot find pyqt6 (macos)

### ISSUE THREAD

**Issue by homerhanumat** [emacs-eaf/emacs-application-framework#1033]
**Describe the bug**

New installation of emacs-eaf on MacOS.  When i open Emacs, initialization of eaf fails.  the problem appears to be that eaf cannot find the pyqt6 library, although it is installed.

**To Reproduce**

1. Install eaf as per directions in the repo README
2. Modify emacs initialization file.  in my case, `.emacs` looks like this:
 ```
(set-face-attribute 'default (selected-frame) :height 170)

(when window-system
  (set-frame-position (selected-frame) 0 0)
  (set-frame-size (selected-frame) 91 63))

(load (expand-file-name "~/.quicklisp/slime-helper.el"))
  ;; Replace "sbcl" with the path to your implementation
  (setq inferior-lisp-program "sbcl")

(add-to-list 'load-path "~/.emacs.d/site-lisp/emacs-application-framework/")
(require 'eaf)

(require 'eaf-demo)
(require 'eaf-pdf-viewer)
(require 'eaf-browser)
(require 'eaf-markdown-previewer)
``` 
3. Start Emacs

**Expected behavior**

Emacs should start without any error messages, instead see **Error Logs** below.

**Versions (please complete the following info):**
 - Distro:  MacOS 10.14.16
 - Versions of Dependencies:  Python 3.9.1
 - M-x emacs-version:
 ```
GNU Emacs 28.2 (build 1, x86_64-apple-darwin18.7.0, NS appkit-1671.60 Version 10.14.6 (Build 18G95)) of 2022-09-1
```

**Error logs**

eaf buffer shows:

```
Traceback (most recent call last):
  File "/Users/homer/.emacs.d/site-lisp/emacs-application-framework/eaf.py", line 25, in <module>
    from PyQt6 import QtWebEngineWidgets as NeverUsed # noqa
ModuleNotFoundError: No module named 'PyQt6'

Process *eaf* exited abnormally with code 1
```

**Additional context**

Necessary Python packages are in the system, as shown by the initial output of `./install-eaf.py`:

```
[EAF] ------------------------------------------
[EAF] Installing core dependencies
[EAF] Running pip3 install --user -U epc sexpdata tld lxml mac-app-frontmost PyQt6==6.3.1 PyQt6-Qt6==6.3.1 PyQt6-sip PyQt6-WebEngine==6.3.1 PyQt6-WebEngine-Qt6==6.3.1 @ /Users/homer/.emacs.d/site-lisp/emacs-application-framework
Requirement already satisfied: epc in /Users/homer/.local/lib/python3.9/site-packages (0.0.5)
Requirement already satisfied: sexpdata in /Users/homer/.local/lib/python3.9/site-packages (0.0.3)
Requirement already satisfied: tld in /Users/homer/.local/lib/python3.9/site-packages (0.12.6)
Requirement already satisfied: lxml in /opt/anaconda3/lib/python3.9/site-packages (4.9.1)
Requirement already satisfied: mac-app-frontmost in /Users/homer/.local/lib/python3.9/site-packages (2020.12.3)
Requirement already satisfied: PyQt6==6.3.1 in /Users/homer/.local/lib/python3.9/site-packages (6.3.1)
Requirement already satisfied: PyQt6-Qt6==6.3.1 in /Users/homer/.local/lib/python3.9/site-packages (6.3.1)
Requirement already satisfied: PyQt6-sip in /Users/homer/.local/lib/python3.9/site-packages (13.4.0)
Requirement already satisfied: PyQt6-WebEngine==6.3.1 in /Users/homer/.local/lib/python3.9/site-packages (6.3.1)
Requirement already satisfied: PyQt6-WebEngine-Qt6==6.3.1 in /Users/homer/.local/lib/python3.9/site-packages (6.3.1)
[EAF] Finished installing core dependencies
```

Not sure if PyQt6 has any dependency on lxlml, but I do note that, unlike all other dependencies, lxml was found in my Anaconda distribution location, rather than `.local/lib`.

**Comment by manateelazycat** [comment]
don't use eaf with Anaconda

**Comment by homerhanumat** [comment]
Update:  I installed lxml specifically into `~/.local/lib/python3.9/site-packages` and re-ran `install-eaf.py`.  This time all core dependencies were found in `~/.local/lib/python3.9/site-packages`, but the same error message was generated when I opened Emacs.

**Comment by manateelazycat** [comment]
did you know https://github.com/purcell/exec-path-from-shell ?

**Comment by homerhanumat** [comment]
Thanks for the notice of `exec-path-from-shell`!  I installed it, re-wrote my shell profile as suggested by the instructions for that package, uninstalled Anaconda and installed Python through Homebrew, ran the eaf install script again, and, hey presto, EAF opened.

The browser works.  pdf and markdown fail (I get the "rebuild EAF buffer" error).

Nonetheless EAF found python and the dependencies, so the current issue could be considered closed.

**Comment by manateelazycat** [comment]
You should use ./install-eaf.py install EAF like README said.

**Comment by homerhanumat** [comment]
Yes, for both pdf view and markdown preview, I saw an error messages that looked like they were generated by line 241 of [eaf.py](https://github.com/emacs-eaf/emacs-application-framework/blob/master/eaf.py).

**Comment by arstum** [comment]
> 是的，对于 pdf 视图和 markdown 预览，我看到错误消息看起来像是由 [eaf.py ](https://github.com/emacs-eaf/emacs-application-framework/blob/master/eaf.py)的第 241 行生成的。

same as me
