### ISSUE TITLE
ConnectionRefusedError: [Errno 111] Connection refused

### ISSUE THREAD

**Issue by ThanosApollo** [emacs-eaf/emacs-application-framework#1034]
**Describe the bug**
A clear and concise description of what the bug is:

-Unable to install eaf
Edit: To be more precise, after following the installation guide, using `eaf-open-browser` or trying to open a .pdf with eaf gave resulted in the following error log

**To Reproduce**
Ensure you're on the latest master branch, then note the steps to reproduce the behavior.

Follow the installation steps

**Expected behavior**

I've just been trying to install eaf, after following the installation instructions I got the following error[see error log]

**Versions (please complete the following info):**
 - Distro and DE/WM:
   - Arch Linux 6.0.9-arch1-1
   - Qtile
 - Versions of Dependencies:
 - M-x emacs-version: 28.2

**Error logs**
```
Traceback (most recent call last):
  File "/home/apollo/.emacs.d/site-lisp/emacs-application-framework/core/utils.py", line 224, in init_epc_client
    epc_client = EPCClient(("localhost", emacs_server_port), log_traceback=True)
  File "/home/apollo/.local/lib/python3.10/site-packages/epc/client.py", line 95, in __init__
    self.connect(socket_or_address)
  File "/home/apollo/.local/lib/python3.10/site-packages/epc/client.py", line 110, in connect
    self.socket = socket.create_connection(socket_or_address)
  File "/usr/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/usr/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
Traceback (most recent call last):
  File "/home/apollo/.emacs.d/site-lisp/emacs-application-framework/eaf.py", line 499, in <module>
    eaf = EAF(sys.argv[1:])
  File "/home/apollo/.emacs.d/site-lisp/emacs-application-framework/eaf.py", line 71, in __init__
    eaf_config_dir = get_emacs_config_dir()
  File "/home/apollo/.emacs.d/site-lisp/emacs-application-framework/core/utils.py", line 336, in get_emacs_config_dir
    emacs_config_dir = os.path.join(os.path.expanduser(get_emacs_var("eaf-config-location")), '')
  File "/home/apollo/.emacs.d/site-lisp/emacs-application-framework/core/utils.py", line 324, in get_emacs_var
    (symbol_value, symbol_is_boolean) = epc_client.call_sync("get-emacs-var", [var_name]) # type: ignore
AttributeError: 'NoneType' object has no attribute 'call_sync'

Process *eaf* exited abnormally with code 1
```
**Screenshots**
-Don't think its needed, but I can provide one with the error log above if it's required.

**Additional context**

I've installed eaf about a week ago in my old thinkpad just fine, today I've been trying to get it to work in my main machine but to no avail, hope it helps though as an issue cause this project is really promising.

**Comment by MatthewZMD** [comment]
Did your error resolve?

**Comment by ThanosApollo** [comment]
> Did your error resolve?

Nope, if you have any quick way to solve this so I can use this awesome framework (especially the pdf-viewer) on my main PC would be appreciated xD 

I've probably messed up my pyqt installation and it throws errors such as `No name 'QtWebEngineWidgets imported from PyQt6'`

I'm about to distrohop to guix and didn't want to waste your time as I believe I won't have this issue in my new installation, cause I probably messed something up, that's why I closed this issue. 
Btw loved your emacsconf talk.

**Comment by MatthewZMD** [comment]
> Btw loved your emacsconf talk.

Thank you very much!

However, EAF does not support GUIX yet. https://github.com/emacs-eaf/emacs-application-framework/issues/1010

**Comment by ThanosApollo** [comment]
I've managed to get working, using the installation from [system crafters](https://github.com/SystemCrafters/guix-installer/releases/tag/v202211220357), +  [nonguix](https://github.com/SystemCrafters/guix-installer/releases/tag/v202211220357) channel instead of the linux-libre and the official guix channel, this way I could get pyqt6 to work. 

*Had some other issues tho so I'm dual booting with arch for now for what's it worth.*
