### ISSUE TITLE
使用C-，M-，S- 等前缀的快捷键

### ISSUE THREAD

**Issue by xDashBW** [emacs-eaf/emacs-application-framework#1038]
某些情况下，会出现无法聚焦输入框的情况，这时候键盘输入会优先被截获为 EAF 的快捷键，而无法输入文本的情况。

例如，[网易 163 邮箱的帐号和密码输入框](https://mail.163.com/)

所以，建议 EAF 的默认快捷键全部采用前缀键，把最直观的按键用作文本输入。

**Comment by manateelazycat** [comment]
这个问题可以参考QQ邮箱的方式去解决，
https://github.com/emacs-eaf/emacs-application-framework/blob/ee53f7d7dad07ecba050e2a26e85153cb7bf92f7/core/js/get_focus_text.js#L8

欢迎发PR

**Comment by manateelazycat** [comment]
已经修复了。
