### ISSUE TITLE
Unable to login to google (gmail, youtube, etc)

### ISSUE THREAD

**Issue by vikasrawal** [emacs-eaf/emacs-application-framework#1041]
**Describe the bug**

When I try to login to google, I get the error:

This browser or app may not be secure. [Learn more](https://support.google.com/accounts/answer/7675428?hl=en-GB)
Try using a different browser. If you’re already using a supported browser, you can try again to sign in.

**To Reproduce**

I just try to open gmail and login. It asks for the email/phone but does not go to the next screen for writing the password.

**Expected behavior**
Google should open the page for entering the password

**Versions (please complete the following info):**
 - Distro and DE/WM:  Manjaro
 - Versions of Dependencies:
 - M-x emacs-version: GNU Emacs 30.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.34, cairo version 1.17.6) of 2022-11-29

**Screenshots**
![Selection_005](https://user-images.githubusercontent.com/479692/206883873-d3638925-02a9-4f3a-a542-103c6f34e0af.png)

**Comment by manateelazycat** [comment]
you need change EAF user agent to value that same as chrome

**Comment by vikasrawal** [comment]
Could you please guide me how to do that. Thank you.

**Comment by manateelazycat** [comment]
https://github.com/emacs-eaf/emacs-application-framework/blob/7d9ed514014f8b5a04ced68e8805070ec1c554c0/eaf.el#L410

**Comment by manateelazycat** [comment]
Can you update to newest and try?

**Comment by manateelazycat** [comment]
Re-open issue if still have problem in newest version.

**Comment by Jousimies** [comment]
<img width="1437" alt="image" src="https://user-images.githubusercontent.com/72933939/207328630-6411a935-d1bc-43b9-915a-9692c0f739c6.png">
使用更新后的 User agent还是提示不能登陆。eaf 己更新到最新。

**Comment by albert748** [comment]
改ua没有用

![Screenshot from 2024-02-22 21-36-07](https://github.com/emacs-eaf/emacs-application-framework/assets/57474/04d997bc-cee1-411e-98c1-9a1facc33915)
![Screenshot from 2024-02-22 21-36-22](https://github.com/emacs-eaf/emacs-application-framework/assets/57474/7fb43800-e7e4-4384-a7ec-47cf2279bb45)

**Comment by manateelazycat** [comment]
EAF 为了加载本地脚本以构建本地应用， 会关闭一些安全选项。

加上 EAF 本身是单进程架构， 会导致网页多的时候， 页面加载比较慢（主要是页面之间相互影响）， 我准备开发一个新的框架， 专门用于浏览器， 这样就可以打开全部安全选项。

**Comment by albert748** [comment]
@manateelazycat 果然是 policy 问题的话，请麻烦告知一下如何暂时性开启以方便登录？无法登录 google 确实有诸多困扰和不便

**Comment by manateelazycat** [comment]
应该是 https://github.com/emacs-eaf/emacs-application-framework/blob/ac135be35220786df1e0bcb4f1a1a95d7c0c7183/eaf.el#L675 这一句， 这一句的目的就是关闭安全选项来加载本地JS和访问本地文件（比如 eaf-file-manager), 这一句关闭以后， eaf-browser 可以访问 gmail 但是又会导致 eaf 本地应用无法工作

**Comment by albert748** [comment]
经过测试，关闭后确实可以登录 google， 以及所有需要用 google 做第三方登录的平台

```
(defun my-eaf--build-process-environment-disable-security (orig-func)
    (let ((environments (funcall orig-func)))
      (when (eq system-type 'gnu/linux)
	(add-to-list 'environments "QTWEBENGINE_CHROMIUM_FLAGS=--disable-web-security" t))
      environments))
  
  (defun eaf-open-browser-nosafe (url &optional args)
    "Open EAF browser application given a URL and ARGS. (with security disabled)
this command is a quick fix for google login purpose etc."
    (interactive "M[EAF/browser] URL: ")
    (advice-add 'eaf--build-process-environment :around #'my-eaf--build-process-environment-disable-security)
    (eaf-open (eaf-wrap-url url) "browser" args)
    (advice-remove 'eaf--build-process-environment #'my-eaf--build-process-environment-disable-security))

```

另外我测试过，登录之后注释掉这段代码其实也是OK的，所以封装到 eaf-open-browser-nosafe 命令中，作为新框架未发布之前的备用策略吧，@manateelazycat 如果可行，建议在 eaf 代码中增加类似方法以方便登录 google

**Comment by albert748** [comment]
@manateelazycat 从我这里看暂时一切正常，可以正常使用

**Comment by manateelazycat** [comment]
@albert748 那欢迎发送PR， 我来合并一下， 可以临时用一下。 ;)
