### ISSUE TITLE
gnome.shell service is not provided

### ISSUE THREAD

**Issue by EricaLinaG** [emacs-eaf/emacs-application-framework#1042]
**Describe the bug**

This started happening with the latest update.

There is a constant dbus error looking for the gnome.shell service.
I do not nor do I wish to have gnome.shell on my system.

This has made eaf unusable for me. The browser leaves its frame and the emacs 
instance is very unresposive. If it manages to render anything.
The only way to get the errors is to not actually 
use it.  Once that happens emacs is useless. 
Even in not using it helm-buffers is broken, and also M-x if using helm.
the problems are really numerous.

Uninstalling eaf solves the problem.  I see that the only use of gnome.shell
should occur only with wayland. I didnt dig any deeper.

From *messages*
```
[EAF/browser] Opening http://duckduckgo.com
When done with this frame, type C-x 5 0
dbus-call-method: D-Bus error: "org.freedesktop.DBus.Error.ServiceUnknown", "The name org.gnome.Shell was not provided by any .service files" [4 times]
```

The page never renders, emacs is useless.

**To Reproduce**
 - Fresh arch linux install with X11.  - probably optional.
 - Make sure eaf is installed and up to date with no problems.
 - Run an emacs daemon.
   ```emacs --daemon=foo```
 - Run a client gui.
   ```emacsclient -c --socketname=foo```

**Expected behavior**
To not get a system crippling error.

**Versions (please complete the following info):**
 - Arch Linux:                 
   Linux Archbook 6.0.11-arch1-1 #1 SMP PREEMPT_DYNAMIC Fri, 02 Dec 2022 17:25:31 +0000 x86_64 
   GNU/Linux
 - Xmonad 0.17.1

 - Versions of Dependencies:
 - M-x emacs-version:  GNU Emacs 28.2 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.34, cairo version 1.17.6) of 2022-09-12

**Error logs**
 - *eaf*
```
QXcbConnection: XCB error: 9 (BadDrawable), sequence: 1340, resource id: 29360178, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 9 (BadDrawable), sequence: 1344, resource id: 29360178, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 9 (BadDrawable), sequence: 1348, resource id: 29360178, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 9 (BadDrawable), sequence: 1352, resource id: 29360178, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 9 (BadDrawable), sequence: 1356, resource id: 29360178, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 9 (BadDrawable), sequence: 1360, resource id: 29360178, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 9 (BadDrawable), sequence: 1364, resource id: 29360178, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 9 (BadDrawable), sequence: 1368, resource id: 29360178, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 9 (BadDrawable), sequence: 1372, resource id: 29360178, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 9 (BadDrawable), sequence: 1376, resource id: 29360178, major code: 130 (Unknown), minor code: 3

```

**Screenshots**

**Additional context**
I hope it reproduces for you.  This a completely fresh install on an old laptop. It
did seem to work after the initial install. But started this after a git pull yesterday,
My personal install is automated, I have the same configuration on another computer.
EAF seems to be broken in a different, out of date way there.

**Comment by manateelazycat** [comment]
What's the elisp value of `window-system`  and `system-type` ?

**Comment by manateelazycat** [comment]
EAF can't work with Emacs daemon.

**Comment by EricGebhart** [comment]
Interesting. It did work at one time, as that is the only way I've used it.
I am also to understand that eaf only works with xwayland/gnome?
Not with x or something other than gnome?
S

**Comment by manateelazycat** [comment]
> Interesting. It did work at one time, as that is the only way I've used it. I am also to understand that eaf only works with xwayland/gnome? Not with x or something other than gnome? S

x11，xwayland，wayland/gnome42 can work，wayland/gnome43 can not work
