### ISSUE TITLE
D-Bus error: org.gnome.Shell was not provided by any .service files

### ISSUE THREAD

**Issue by ATNewHope** [emacs-eaf/emacs-application-framework#1043]
**Describe the bug**
_The issue might be similar to #1042 ._

After adding eaf layer (for the first time) and restarting Spacemacs, error message:

> [persp-mode] Error: Can not initialize frame -- (void-function dbus-call-method)

And when I try to open a PDF file, a new window ("frame" in emacs term) opened and rendered the PDF file normally, but not responding to my keyboard, and error message:

> dbus-call-method: D-Bus error: "org.freedesktop.DBus.Error.ServiceUnknown", "The name org.gnome.Shell was not provided by any .service files"

Considering that I'm using Sway WM, and there's no Gnome DE installed, this is so weird.

**To Reproduce**

1. Fresh install Arch Linux on an amd64 computer, with Sway as Window Manager.
2. Create a sudoer user and login (i.e. NOT as a root user).
3. Add QT_QPA_PLATFORM="wayland;xcb" to /etc/environment .
4. Install Spacemacs (develop branch, as the master one is deprecated).
5. Add eaf to spacemacs layer.
6. Run Spacemacs gui, then M-x eaf-install, then M-x eaf-install-and-update .
7. Choose Y for every prompt, so that all available eaf apps are installed.
8. Restart spacemacs, open a PDF file.

**Expected behavior**
No D-Bus related error message appears, as before adding the eaf layer.

**Versions:**
 - Distro and DE/WM: Arch Linux, Sway
 - Versions of Dependencies: All upgraded to latest.
 - M-x emacs-version: GNU Emacs 28.2 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.34, cairo version 1.17.6) of 2022-09-12

**Error logs**
`*eaf*` buffer:

> 
> qt.core.plugin.factoryloader: Got keys from plugin meta data QList("wayland-egl")
> qt.core.plugin.factoryloader: looking at "/home/tux/.local/lib/python3.10/site-packages/PyQt6/Qt6/plugins/platforms/libqwayland-generic.so"
> qt.core.plugin.loader: Found metadata in lib /home/tux/.local/lib/python3.10/site-packages/PyQt6/Qt6/plugins/platforms/libqwayland-generic.so, metadata=
> {
>     "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
>     "MetaData": {
>         "Keys": [
>             "wayland"
>         ]
>     },
>     "archlevel": 1,
>     "className": "QWaylandIntegrationPlugin",
>     "debug": false,
>     "version": 393984
> }
> 
> 
> qt.core.plugin.factoryloader: Got keys from plugin meta data QList("wayland")
> qt.core.plugin.factoryloader: looking at "/home/tux/.local/lib/python3.10/site-packages/PyQt6/Qt6/plugins/platforms/libqxcb.so"
> qt.core.plugin.loader: Found metadata in lib /home/tux/.local/lib/python3.10/site-packages/PyQt6/Qt6/plugins/platforms/libqxcb.so, metadata=
> {
>     "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
>     "MetaData": {
>         "Keys": [
>             "xcb"
>         ]
>     },
>     "archlevel": 1,
>     "className": "QXcbIntegrationPlugin",
>     "debug": false,
>     "version": 393984
> }
> 
> 
> qt.core.plugin.factoryloader: Got keys from plugin meta data QList("xcb")
> qt.core.plugin.factoryloader: checking directory path "/usr/bin/platforms" ...
> qt.core.library: "/home/tux/.local/lib/python3.10/site-packages/PyQt6/Qt6/plugins/platforms/libqwayland-generic.so" loaded library
> Failed to create wl_display (No such file or directory)
> qt.qpa.plugin: Could not load the Qt platform plugin "wayland" in "" even though it was found.
> qt.core.library: "/home/tux/.local/lib/python3.10/site-packages/PyQt6/Qt6/plugins/platforms/libqxcb.so" loaded library
> qt.qpa.xcb: could not connect to display 
> qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
> This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
> 
> Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vkkhrdisplay, vnc, wayland-egl, wayland, xcb.
> 
> 
> Process *eaf* aborted (core dumped)

message buffer(only related):

> [persp-mode] Error: Can not initialize frame -- (void-function dbus-call-method)
> [EAF/pdf-viewer] Opening /home/tux/Downloads/foo.pdf
> dbus-call-method: D-Bus error: "org.freedesktop.DBus.Error.ServiceUnknown", "The name org.gnome.Shell was not provided by any .service files" [2 times]

**Screenshots**
Not needed.

**Additional context**

1. Tried QT_QPA_PLATFORM=xcb in /etc/environment , no luck.

eaf buffer becomes:

> qt.core.plugin.factoryloader: Got keys from plugin meta data QList("xcb")
> qt.core.plugin.factoryloader: checking directory path "/usr/bin/platforms" ...
> qt.core.library: "/home/tux/.local/lib/python3.10/site-packages/PyQt6/Qt6/plugins/platforms/libqxcb.so" loaded library
> qt.qpa.xcb: could not connect to display 
> qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
> This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
> 
> Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vkkhrdisplay, vnc, wayland-egl, wayland, xcb.

2. Tried QT_QPA_PLATFORM=wayland in /etc/environment , no luck.

PDF viewer even won't show up this time.

> 
> qt.core.plugin.factoryloader: Got keys from plugin meta data QList("xcb")
> qt.core.plugin.factoryloader: checking directory path "/usr/bin/platforms" ...
> qt.core.library: "/home/tux/.local/lib/python3.10/site-packages/PyQt6/Qt6/plugins/platforms/libqwayland-generic.so" loaded library
> Failed to create wl_display (No such file or directory)
> qt.qpa.plugin: Could not load the Qt platform plugin "wayland" in "" even though it was found.
> This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
> 
> Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vkkhrdisplay, vnc, wayland-egl, wayland, xcb.
> 
> 
> Process *eaf* aborted (core dumped)
> 

3. I also have some qt programs (eg. dolphin, konsole, kdeconnect) installed, all of them run without problem. So this seems not be a qt problem, or at least there should be a workaround.

4. In Spacemacs, C-h v show value:
window-system = x
system-type = gnu/linux

5. Thanks in advance for help.

**Comment by ATNewHope** [comment]
And there's a little weird that for wayland part, the README of EAF only tells about preparation for Gnome 3 users, not sway or kde(wayland) etc. users. Maybe needed to add somethings there?

**Comment by manateelazycat** [comment]
If your `window-sytem` not `pgtk`, then eaf-emacs-running-in-wayland-native is false.

And EAF can't works for terminal enviroment. 

Wayland not allow other program to query Emacs's position and size, we need write Gnome-Shell code to do this, Sway or KDE(Wayland) should write more code to do similar like Gnome3.


-------------------------
I guess you running EAF in terminal enviroment?

**Comment by manateelazycat** [comment]
If you window-system is `x` and running in GUI, https://github.com/emacs-eaf/emacs-application-framework/blob/1c26beb971ef93a8a279d5159e5f880c100ac257/eaf.el#L1015 can't be true, and https://github.com/emacs-eaf/emacs-application-framework/blob/1c26beb971ef93a8a279d5159e5f880c100ac257/eaf.el#L1024 never have a chance to run.

This issue should occur.

**Comment by ATNewHope** [comment]
Welp, you might be right, but here's the thing:
I did what https://wiki.archlinux.org/title/Spacemacs#Systemd_Module do, i.e. add a systemd module, so that actually my spacemacs run in background before the real GUI client connect to it. Maybe that's the case.

**Comment by manateelazycat** [comment]
EAF can't works with Emacs's daemon mode.

**Comment by ATNewHope** [comment]
And I'm back... Installed aur/emacs-gcc-wayland-devel-bin, the problem still exists, but somethings change.

window-system becomes pgtk.

~*eaf*~ show no error, the progress bar appear when open PDF and stoped at near 15%.

~*Messages*~ show same thing like before, i.e.

> cond: Symbol’s function definition is void: dbus-call-method
> [EAF/pdf-viewer] Opening /home/tux/foo.pdf
> dbus-call-method: D-Bus error: "org.freedesktop.DBus.Error.ServiceUnknown", "The name org.gnome.Shell was not provided by any .service files" [4 times]

And this time, notice that I started emacs GUI directly, not as a client. So systemd thingy is not the case.

C-h v

**Comment by manateelazycat** [comment]
(require 'dbus)

**Comment by manateelazycat** [comment]
EAF can works with Gnome3 V42, and can't works with Gnome3 V43.1, and Sway can't work too IMO.

I suggestion you run EAF with XWayland, it's works great for X11

**Comment by ATNewHope** [comment]
Install dbus seems not work.

Xwayland could be a workaround. Thanks, I'll try.

**Comment by manateelazycat** [comment]
> 

EAF just can works with Gnome3/Wayland v42, Sway can't work because we need write Sway code to get Emacs's size and position.

XWayland is better way if you really want to run EAF and don't care DE enviroment.

I use Gnome3/XWayland with EAF, works out of box.

**Comment by manateelazycat** [comment]
I need close this issue, because EAF can't works with newest version of Gnome3 and Sway.

**Comment by ATNewHope** [comment]
Uninstalled  emacs-gcc-wayland-devel-bin (ver 28.2.50, which is close to the current stable branch), installed emacs-pgtk-git (ver 30.0.50)
Run directly in GUI mode, no systemd thingy.
The PDF viewer now works perfectly.
There's still one type of error messages, and the one contains "void" (i.e. (void-function dbus-call-method)) does NOT show anymore.
It continously appears, not regularly, but never stops.

> dbus-call-method: D-Bus error: "org.freedesktop.DBus.Error.ServiceUnknown", "The name org.gnome.Shell was not provided by any .service files" [3 times]

**Comment by manateelazycat** [comment]
Well, EAF just test with Gnome3 V42 Wayland, I haven't time to test Sway, any PR are welcome. 

Sorry.

**Comment by ATNewHope** [comment]
Since spacemacs doesn't support emacs' develop branch officially, (welp, but the eaf layer IS officially provided), this workaround is not perfect, as some other error messages (not related to EAF) appeared.

And I tried again with systemd thingy, launch a emacsclient connect to it. All the same.

> EAF can't works with Emacs's daemon mode.

So the conclusion is that emacs' daemon mode may not effect anything at all.

ps. I'm using QT_QPA_PLATFORM=wayland in /etc/environment

And as #1042 said, the "Gnome" thingy appeared after an update. If that is true, maybe there's a chance that the EAF code has a bug, e.g. on determining which D-Bus session need to connect , so that it won't try to connect the none-existing Gnome D-Bus service?

**Comment by manateelazycat** [comment]
> Since spacemacs doesn't support emacs' develop branch officially, (welp, but the eaf layer IS officially provided), this workaround is not perfect, as some other error messages (not related to EAF) appeared.
> 
> And I tried again with systemd thingy, launch a emacsclient connect to it. All the same.
> 
> > EAF can't works with Emacs's daemon mode.
> 
> So the conclusion is that emacs' daemon mode may not effect anything at all.
> 
> ps. I'm using QT_QPA_PLATFORM=wayland in /etc/environment
> 
> And as #1042 said, the "Gnome" thingy appeared after an update. If that is true, maybe there's a chance that the EAF code has a bug, e.g. on determining which D-Bus session need to connect , so that it won't try to connect the none-existing Gnome D-Bus service?

not just dbus, we shoud find a way to get emacs size and position dynamically in sway, and we need find focs emacs way in sway.

remove dbus code not work

it need wrote many code for sway.

if you not want switch xwayland, you should hacking sway yourself

**Comment by ATNewHope** [comment]
Edit: I see, so that the D-Bus thing is to get Emacs's size and position,
Which means that D-Bus part code for sway needed to be written specifically.
I think that's true, but sway use wlroots, so that the code could only specifically for wlroots, so that all wlroots based WM/DE could use this.

As for PR, though I'm willing to, I currently don't have elips programming ability, sorry.

**Comment by manateelazycat** [comment]
> Since spacemacs doesn't support emacs' develop branch officially, (welp, but the eaf layer IS officially provided), this workaround is not perfect, as some other error messages (not related to EAF) appeared.
> 
> And I tried again with systemd thingy, launch a emacsclient connect to it. All the same.
> 
> > EAF can't works with Emacs's daemon mode.
> 
> So the conclusion is that emacs' daemon mode may not effect anything at all.
> 
> ps. I'm using QT_QPA_PLATFORM=wayland in /etc/environment
> 
> And as #1042 said, the "Gnome" thingy appeared after an update. If that is true, maybe there's a chance that the EAF code has a bug, e.g. on determining which D-Bus session need to connect , so that it won't try to connect the none-existing Gnome D-Bus service?

in gnome, we need copy gnome-shell plugin 
 dictionary to  gnome extension dictionary, it works for gnome v42, gnome v43 still need gnome-shell plugin and dbus service, just window attribute can not work somehow.

as i said, you need write sway code yourself, disable dbus is not right way

**Comment by ATNewHope** [comment]
The PDF viewer render 3 pages, and won't render the last ones (stucked there).

So that XWayland, as you said, may really be the only workaround currently.
Or until someone works on EAF's code for wlroots.

Many thanks for your patient help.

**Comment by ATNewHope** [comment]
To those (including future me) who would like to solve the issue for real, i.e. get emacs' windows coordinates from wlroots:
[wlr-protocols](https://github.com/swaywm/wlr-protocols) may be the key.
