### ISSUE TITLE
Cannot find image file

### ISSUE THREAD

**Issue by ATNewHope** [emacs-eaf/emacs-application-framework#1045]
**Describe the bug**
Open PDF Viewer, wait for a long time, but nothing rendered.

**To Reproduce**
Archlinux, Swaywm, Emacs 30.0.50 with pgtk support
newest EAF pdf viewer

**Expected behavior**
PDF rendered as expected.

**Versions (please complete the following info):**
 - Distro and DE/WM: Swaywm
 - M-x emacs-version: GNU Emacs 30.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.35, cairo version 1.17.6) of 2022-12-15

**Error logs**
eaf buffer: Empty

In messages buffer, this appears many times:

> Cannot find image file ‘/home/tux/.emacs.d/eaf/8142-ac21-0aa6-eb46-781e-4460-1154.jpeg’ [9 times]

**Screenshots**
Not needed

**Comment by ATNewHope** [comment]
Now, the most interesting part is that, I downloaded a jpeg image and move it to /home/tux/.emacs.d/eaf/8142-ac21-0aa6-eb46-781e-4460-1154.jpeg, then miracle appears:

The pdf viewer rendered that image.

**Comment by manateelazycat** [comment]
Please check file path. 

And Pdf Viewer should open image, should use EAF image-viewer

**Comment by ATNewHope** [comment]
> Please check file path.
> 
> And Pdf Viewer should open image, should use EAF image-viewer

What I opened sure is a pdf file, but nothing rendered originally.
The downloaded image is just to help test what the error message actually means.

**Comment by ATNewHope** [comment]
> Please check file path.
> 
> And Pdf Viewer should open image, should use EAF image-viewer

What I opened sure is an existing pdf file, but nothing rendered originally.
The downloaded image is just to help test what the error message actually means.

**Comment by manateelazycat** [comment]
Check `*eaf*` buffer content like README said.

**Comment by manateelazycat** [comment]
Are you Chinese?

**Comment by ATNewHope** [comment]
> Check `*eaf*` buffer content like README said.

As I said, that buffer is empty.

**Comment by ATNewHope** [comment]
> Are you Chinese?

I don't know if this matters, but yes.

**Comment by manateelazycat** [comment]
说中文吧， 我的英文不好， 全程英文意思表达不准确， 也很耽误我的时间。

你搞定了 Sway 环境的 active window 和 emacs coordiante 了吗？

你先看看 eaf-demo 或者 eaf-vue-demo 这些最简单的测试程序能不能跑？ 还有就是 EAF Browser 能不能跑， 这些能跑证明 PyQt 或者 WebEngine 是好的。

一般没法渲染要不是文件路径有问题， 要不就是mupdf这些库没有正常安装。

**Comment by ATNewHope** [comment]
窗口的激活和坐标那边，理论上看起来应该是没问题的（运行的时候也没有相关报错），但是没办法测试，因为昨天重装EAF之后什么都渲染不出来。

两个demo运行后是卡死的，无法操作只能退出（会出现进度条，卡在15%左右的位置）。
Browser也是无法渲染，但是唯一一个在eaf buffer给了信息的。

> qt.webenginecontext: 
> 
> GL Type: desktop
> Surface Type: OpenGL
> Surface Profile: CompatibilityProfile
> Surface Version: 4.6
> QSG RHI Backend: OpenGL
> Using Supported QSG Backend: yes
> Using Software Dynamic GL: no
> Using Multithreaded OpenGL: yes
> 
> Init Parameters:
>   *  application-name eaf.py 
>   *  browser-subprocess-path /home/tux/.local/lib/python3.10/site-packages/PyQt6/Qt6/libexec/QtWebEngineProcess 
>   *  create-default-gl-context  
>   *  disable-features ConsolidatedMovementXY,InstalledApp,BackgroundFetch,WebOTP,WebPayments,WebUSB,PictureInPicture 
>   *  disable-setuid-sandbox  
>   *  disable-speech-api  
>   *  disable-web-security  
>   *  enable-features NetworkServiceInProcess,TracingServiceInProcess 
>   *  enable-gpu-rasterization  
>   *  enable-native-gpu-memory-buffers  
>   *  enable-threaded-compositing  
>   *  ignore-gpu-blocklist  
>   *  in-process-gpu  
>   *  use-gl desktop 
>

**Comment by ATNewHope** [comment]
browser打开过程中eaf buffer又有新的信息

> Fontconfig error: Cannot load default config file: No such file: (null)
> crbug/1173575, non-JS module files deprecated.
> [EAF] Browser http://www.duckduckgo.com/ loading time: 130.00840520858765s
> 

但是我fontconfig其实是配置过的（在~/.config/fontconfig/fonts.conf），应该不是这个问题

**Comment by ATNewHope** [comment]
https://github.com/ATNewHope/emacs-application-framework
由于没有成功测试，所以还没有PR。当然PR大概也没问题？毕竟只是添加针对sway的分支，没有任何损害

**Comment by manateelazycat** [comment]
你先换个gnome3 xwayland或者kde的环境测试一下，确保pyqt没问题。

你的问题看起来像系统升级后pyqt挂了。

补丁还是要测试一下再提交吧。

**Comment by ATNewHope** [comment]
其实这边还是属于一个比较奇怪的问题，就是说我本来是要打开一个pdf文档了，结果它报错说某个jpeg文件找不到，

> [EAF/pdf-viewer] Opening /hub/foo.pdf
> Cannot find image file ‘/home/tux/.emacs.d/eaf/dd84-58f6-2463-c72a-c42e-2650-dc1b.jpeg’ [34 times]
> C-SPC ESC is undefined
> Cannot find image file ‘/home/tux/.emacs.d/eaf/dd84-58f6-2463-c72a-c42e-2650-dc1b.jpeg’ [19 times]
> End of buffer
> Cannot find image file ‘/home/tux/.emacs.d/eaf/dd84-58f6-2463-c72a-c42e-2650-dc1b.jpeg’ [21 times]

所以我的理解（猜测）是：
> EAF的PDF阅读器的原理是将pdf页面转为图像文件临时保存在某个位置，再显示这个图像文件。

那么问题就变成了，为什么它生成的图像不在它所认为的 `~/.emacs.d/eaf/xxxx.jpeg` 。
其中一种原因，可能是我在调用 swaymsg-treefetch 脚本文件时，更改了目录，即
```elisp
    (defun eaf--topmost-focus-change ()
      "Manage Emacs's focus change."
      (let ((front (cond ((eq system-type 'darwin)
                          (shell-command-to-string "app-frontmost --name"))
			 ((string-equal (getenv "XDG_CURRENT_DESKTOP") "sway")
			  (let ((default-directory eaf-build-dir))
			    (if (executable-find "jshon")
			      (shell-command-to-string "bash ./swaymsg-treefetch/swaymsg-focusfetcher.sh")
			      (message "Please install jshon for swaywm support."))))
                         (t
                          (require 'dbus)
                          (dbus-call-method :session "org.gnome.Shell" "/org/eaf/wayland" "org.eaf.wayland" "get_active_window" :timeout 1000)))))
        (cond
         ((member front (list "Python\n" "python3\n" "python3"))
          (setq eaf--topmost-switch-to-python t))
         ((member front (list "Emacs\n" "emacs"))
          (if eaf--topmost-switch-to-python
              (setq eaf--topmost-switch-to-python nil)
            (run-with-timer 0.1 nil #'eaf--topmost-focus-update)))
         (t (eaf--topmost-focus-out)))))
```

我想知道 ` (let ((default-directory eaf-build-dir))` 这一行是全局生效的还是局部生效的。如果是全局，那么该怎么改。

**Comment by manateelazycat** [comment]
> 其实这边还是属于一个比较奇怪的问题，就是说我本来是要打开一个pdf文档了，结果它报错说某个jpeg文件找不到，
> 
> > [EAF/pdf-viewer] Opening /hub/foo.pdf
> > Cannot find image file ‘/home/tux/.emacs.d/eaf/dd84-58f6-2463-c72a-c42e-2650-dc1b.jpeg’ [34 times]
> > C-SPC ESC is undefined
> > Cannot find image file ‘/home/tux/.emacs.d/eaf/dd84-58f6-2463-c72a-c42e-2650-dc1b.jpeg’ [19 times]
> > End of buffer
> > Cannot find image file ‘/home/tux/.emacs.d/eaf/dd84-58f6-2463-c72a-c42e-2650-dc1b.jpeg’ [21 times]
> 
> 所以我的理解（猜测）是：
> 
> > EAF的PDF阅读器的原理是将pdf页面转为图像文件临时保存在某个位置，再显示这个图像文件。
> 
> 那么问题就变成了，为什么它生成的图像不在它所认为的 `~/.emacs.d/eaf/xxxx.jpeg` 。 其中一种原因，可能是我在调用 swaymsg-treefetch 脚本文件时，更改了目录，即
> 
> ```emacs-lisp
>     (defun eaf--topmost-focus-change ()
>       "Manage Emacs's focus change."
>       (let ((front (cond ((eq system-type 'darwin)
>                           (shell-command-to-string "app-frontmost --name"))
> 			 ((string-equal (getenv "XDG_CURRENT_DESKTOP") "sway")
> 			  (let ((default-directory eaf-build-dir))
> 			    (if (executable-find "jshon")
> 			      (shell-command-to-string "bash ./swaymsg-treefetch/swaymsg-focusfetcher.sh")
> 			      (message "Please install jshon for swaywm support."))))
>                          (t
>                           (require 'dbus)
>                           (dbus-call-method :session "org.gnome.Shell" "/org/eaf/wayland" "org.eaf.wayland" "get_active_window" :timeout 1000)))))
>         (cond
>          ((member front (list "Python\n" "python3\n" "python3"))
>           (setq eaf--topmost-switch-to-python t))
>          ((member front (list "Emacs\n" "emacs"))
>           (if eaf--topmost-switch-to-python
>               (setq eaf--topmost-switch-to-python nil)
>             (run-with-timer 0.1 nil #'eaf--topmost-focus-update)))
>          (t (eaf--topmost-focus-out)))))
> ```
> 
> 我想知道 ` (let ((default-directory eaf-build-dir))` 这一行是全局生效的还是局部生效的。如果是全局，那么该怎么改。如果是局部，那应该不是这个问题。
> 
> EDIT：试着在根目录用catfish找了一下 `dd84-58f6-2463-c72a-c42e-2650-dc1b.jpeg` ，居然不存在这个文件。

EAF PDF不会生成任何图片文件到本地系统，你最好emacs -Q对比测试一下，99%概率是你自己配置文件的问题。

**Comment by manateelazycat** [comment]
> 其实这边还是属于一个比较奇怪的问题，就是说我本来是要打开一个pdf文档了，结果它报错说某个jpeg文件找不到，
> 
> > [EAF/pdf-viewer] Opening /hub/foo.pdf
> > Cannot find image file ‘/home/tux/.emacs.d/eaf/dd84-58f6-2463-c72a-c42e-2650-dc1b.jpeg’ [34 times]
> > C-SPC ESC is undefined
> > Cannot find image file ‘/home/tux/.emacs.d/eaf/dd84-58f6-2463-c72a-c42e-2650-dc1b.jpeg’ [19 times]
> > End of buffer
> > Cannot find image file ‘/home/tux/.emacs.d/eaf/dd84-58f6-2463-c72a-c42e-2650-dc1b.jpeg’ [21 times]
> 
> 所以我的理解（猜测）是：
> 
> > EAF的PDF阅读器的原理是将pdf页面转为图像文件临时保存在某个位置，再显示这个图像文件。
> 
> 那么问题就变成了，为什么它生成的图像不在它所认为的 `~/.emacs.d/eaf/xxxx.jpeg` 。 其中一种原因，可能是我在调用 swaymsg-treefetch 脚本文件时，更改了目录，即
> 
> ```emacs-lisp
>     (defun eaf--topmost-focus-change ()
>       "Manage Emacs's focus change."
>       (let ((front (cond ((eq system-type 'darwin)
>                           (shell-command-to-string "app-frontmost --name"))
> 			 ((string-equal (getenv "XDG_CURRENT_DESKTOP") "sway")
> 			  (let ((default-directory eaf-build-dir))
> 			    (if (executable-find "jshon")
> 			      (shell-command-to-string "bash ./swaymsg-treefetch/swaymsg-focusfetcher.sh")
> 			      (message "Please install jshon for swaywm support."))))
>                          (t
>                           (require 'dbus)
>                           (dbus-call-method :session "org.gnome.Shell" "/org/eaf/wayland" "org.eaf.wayland" "get_active_window" :timeout 1000)))))
>         (cond
>          ((member front (list "Python\n" "python3\n" "python3"))
>           (setq eaf--topmost-switch-to-python t))
>          ((member front (list "Emacs\n" "emacs"))
>           (if eaf--topmost-switch-to-python
>               (setq eaf--topmost-switch-to-python nil)
>             (run-with-timer 0.1 nil #'eaf--topmost-focus-update)))
>          (t (eaf--topmost-focus-out)))))
> ```
> 
> 我想知道 ` (let ((default-directory eaf-build-dir))` 这一行是全局生效的还是局部生效的。如果是全局，那么该怎么改。如果是局部，那应该不是这个问题。
> 
> EDIT：试着在根目录用catfish找了一下 `dd84-58f6-2463-c72a-c42e-2650-dc1b.jpeg` ，居然不存在这个文件。

你为啥要改default-directionry的值？你直接用load-file-name就可以拼装成全局路径了。

**Comment by ATNewHope** [comment]
> 你为啥要改default-directionry的值？你直接用load-file-name就可以拼装成全局路径了。

感谢指点。

主要是因为我不会elisp，就只能在网上到处抄代码。有人是这样做的。

至于load-file-name，我确实是看到了你给的那个示例，但那个示例是
`(defvar eaf-python-file (expand-file-name "eaf.py" (file-name-directory load-file-name)))`
并且这个变量在 eaf.el 中仅用于 `(list eaf-python-file)` ，并没有运行。

所以参考到这一步的话，我是可以能拼出全局路径，但：
- 如果我想让脚本位于 `./swaymsg-treefetch/` ，那么 `(expand-file-name "swaymsg-treefetch/foo.sh" (file-name-directory load-file-name))` 真的能生效吗？
- - 怎么给这样的脚本传递参数呢？  比如 `(shell-command-to-string (expand-file-name "swaymsg-treefetch/foo.sh" (file-name-directory load-file-name)) "emacs")` 这样？

我不是很确定，所以我就选了改 default-directory 这个看起来更稳妥，且在我熟知的范围内（ shell 语言）的方法。

当然现在既然知道了这样不合适，那么我再改一下代码。

**Comment by ATNewHope** [comment]
现在是这样的：

### 获取激活窗口的app_id
```elisp
			 ((string-equal (getenv "XDG_CURRENT_DESKTOP") "sway")
			    (if (executable-find "jshon")
			      (shell-command-to-string ((expand-file-name "swaymsg-treefetch/swaymsg-focusfetcher.sh" (file-name-directory load-file-name)) "emacs"))
			      (message "Please install jshon for swaywm support.")))
```
### 获取窗口坐标
```elisp
	((string-equal (getenv "XDG_CURRENT_DESKTOP") "sway")
	   (list (string-split (shell-command-to-string ((expand-file-name "swaymsg-treefetch/swaymsg-rectfetcher.sh" (file-name-directory load-file-name)) "emacs")))))
```

**Comment by manateelazycat** [comment]
> > 你为啥要改default-directionry的值？你直接用load-file-name就可以拼装成全局路径了。
> 
> 感谢指点。
> 
> 主要是因为我不会elisp，就只能在网上到处抄代码。有人是这样做的。
> 
> 至于load-file-name，我确实是看到了你给的那个示例，但那个示例是 `(defvar eaf-python-file (expand-file-name "eaf.py" (file-name-directory load-file-name)))` 并且这个变量在 eaf.el 中仅用于 `(list eaf-python-file)` ，并没有看到怎么直接运行。
> 
> 所以参考到这一步的话，我是可以能拼出全局路径，但：
> 
> * 如果我想让脚本位于 `./swaymsg-treefetch/` ，那么 `(expand-file-name "swaymsg-treefetch/foo.sh" (file-name-directory load-file-name))` 真的能生效吗？
> * 怎么给这样的脚本传递 "emacs” 这个参数呢？  比如 `(shell-command-to-string (expand-file-name "swaymsg-treefetch/foo.sh" (file-name-directory load-file-name)) "emacs")` 这样？
> 
> 我不是很确定，所以我就选了改 default-directory 这个看起来更稳妥，且在我熟知的范围内（ shell 语言）的方法。
> 
> 当然现在既然知道了这样不合适，那么我再改一下代码。

你先学习一下elisp的函数吧， 不要着急， 这个你还是要自己研究的， 要不基本上是我在写代码了。

**Comment by ATNewHope** [comment]
又试验了一下：

我全新重装了一下spacemacs（从零开始），对于配置文件则是仅添加eaf的layer之后自动装各种包，此时pdf又能正常打开了。

然后再 M-x eaf-install ，结果pdf又打不开了。

> [EAF/pdf-viewer] Opening /hub/foo.pdf
> Cannot find image file ‘/home/tux/.emacs.d/eaf/0a83-4386-8be6-66bb-8627-c7ae-451f.jpeg’ [23 times]
> End of buffer
> Cannot find image file ‘/home/tux/.emacs.d/eaf/0a83-4386-8be6-66bb-8627-c7ae-451f.jpeg’ [29 times]
> Beginning of buffer
> Cannot find image file ‘/home/tux/.emacs.d/eaf/0a83-4386-8be6-66bb-8627-c7ae-451f.jpeg’ [10 times]
> Beginning of buffer
> Cannot find image file ‘/home/tux/.emacs.d/eaf/0a83-4386-8be6-66bb-8627-c7ae-451f.jpeg’ [10 times]
> Beginning of buffer
> Cannot find image file ‘/home/tux/.emacs.d/eaf/0a83-4386-8be6-66bb-8627-c7ae-451f.jpeg’ [10 times]
> Beginning of buffer
> Cannot find image file ‘/home/tux/.emacs.d/eaf/0a83-4386-8be6-66bb-8627-c7ae-451f.jpeg’ [15 times]
> Mark set
> Cannot find image file ‘/home/tux/.emacs.d/eaf/0a83-4386-8be6-66bb-8627-c7ae-451f.jpeg’ [16 times]
> End of buffer
> Cannot find image file ‘/home/tux/.emacs.d/eaf/0a83-4386-8be6-66bb-8627-c7ae-451f.jpeg’ [16 times]
> End of buffer

因为配置文件是全新的，这当然已经和配置无关了。
应该是安装过程出了什么问题（但是其中并没有报错）

**Comment by ATNewHope** [comment]
> 你先学习一下elisp的函数吧， 不要着急， 这个你还是要自己研究的， 要不基本上是我在写代码了。

代码那边，我找到了concat来做这个事情，用别的方式（调用notify-send通知一个特定信息）测试了下，应该是没问题的了。

**Comment by manateelazycat** [comment]
> 又试验了一下：
> 
> 我全新重装了一下spacemacs（从零开始），对于配置文件则是仅添加eaf的layer之后自动装各种包，此时pdf又能正常打开了。
> 
> 然后再 M-x eaf-install ，结果pdf又打不开了。
> 
> > [EAF/pdf-viewer] Opening /hub/foo.pdf
> > Cannot find image file ‘/home/tux/.emacs.d/eaf/0a83-4386-8be6-66bb-8627-c7ae-451f.jpeg’ [23 times]
> > End of buffer
> > Cannot find image file ‘/home/tux/.emacs.d/eaf/0a83-4386-8be6-66bb-8627-c7ae-451f.jpeg’ [29 times]
> > Beginning of buffer
> > Cannot find image file ‘/home/tux/.emacs.d/eaf/0a83-4386-8be6-66bb-8627-c7ae-451f.jpeg’ [10 times]
> > Beginning of buffer
> > Cannot find image file ‘/home/tux/.emacs.d/eaf/0a83-4386-8be6-66bb-8627-c7ae-451f.jpeg’ [10 times]
> > Beginning of buffer
> > Cannot find image file ‘/home/tux/.emacs.d/eaf/0a83-4386-8be6-66bb-8627-c7ae-451f.jpeg’ [10 times]
> > Beginning of buffer
> > Cannot find image file ‘/home/tux/.emacs.d/eaf/0a83-4386-8be6-66bb-8627-c7ae-451f.jpeg’ [15 times]
> > Mark set
> > Cannot find image file ‘/home/tux/.emacs.d/eaf/0a83-4386-8be6-66bb-8627-c7ae-451f.jpeg’ [16 times]
> > End of buffer
> > Cannot find image file ‘/home/tux/.emacs.d/eaf/0a83-4386-8be6-66bb-8627-c7ae-451f.jpeg’ [16 times]
> > End of buffer
> 
> 因为配置文件是全新的，这当然已经和配置无关了。 应该是eaf-install安装过程出了什么问题（但是其中并没有报错）
> 
> 并且把eaf-xxx/app/*清空之后再python ./install-eaf.py ，依旧如此。

你自己看吧，我的建议是只用 install-eaf.py

**Comment by ATNewHope** [comment]
> 代码那边，我找到了concat来做这个事情，用别的方式（调用emacs的message或shell的notify-send通知一个特定信息）测试了下，应该是没问题的了。

比如把 `eaf--topmost-focus-change ()` 的定义式里的 `(shell-command-to-string (concat eaf-build-dir "swaymsg-treefetch/swaymsg-focusfetcher.sh"))` 前后分别添加 `(message` 和 `)` ，再来回切换窗口，那么 emacs 的底栏就会出现当前 focus 的窗口的 appid：

> Loading /home/tux/.emacs.d/.cache/recentf...done
> When done with this frame, type SPC F d
> "emacs"
> "emacs"
> 
> "firefox"
> "firefox"
> 
> "emacs"
> "emacs"

同理，改成 `(message (shell-command-to-string (concat eaf-build-dir "swaymsg-treefetch/swaymsg-rectfetcher.sh emacs")))` 再切换窗口，则：

> 
> Loading /home/tux/.emacs.d/.cache/recentf...done
> When done with this frame, type SPC F d
> 1080 775
> 
> 1080 775
> 
> 1080 775
> 
> 1080 775
> 
> 1080 775
> 
> 1080 775

所以我认为这个代码是可以pr的了。

**Comment by lhpfvs** [comment]
这个jpeg我猜是因为macOS和pgtk需要在切换到其他应用的时候截屏搞出来的，但这个应该不是关键，eaf在pgtk下估计有更基础的问题。

**Comment by manateelazycat** [comment]
> 这个jpeg我猜是因为macOS和pgtk需要在切换到其他应用的时候截屏搞出来的，但这个应该不是关键，eaf在pgtk下估计有更基础的问题。

嗯， @ATNewHope 应该是 @lhpfvs 说的那个问题 。

**Comment by manateelazycat** [comment]
找不到图像的问题确实如 @lhpfvs 所说， 已经用新的补丁防御了 https://github.com/emacs-eaf/emacs-application-framework/commit/57ca68b4700beae94ad82f0cd6c46b68b60ad8f5

如果依然还是显示不出来， 应该是 Wayland 下焦点切换的行为和 macOS 不一样导致的。

因为 Sway 是窗口管理器， 没有传统DE的任务栏， 所以Gnome3 v43 以后的窗口属性状态和坐标的问题应该没有， 只需要解决 SWay 下 focus change 的状态就应该可以正常工作， 具体请查看 https://github.com/emacs-eaf/emacs-application-framework/blob/57ca68b4700beae94ad82f0cd6c46b68b60ad8f5/eaf.el#L1099

Happy hacking! ;)
