### ISSUE TITLE
How to activate the eaf-wayland@emacs-eaf.org plugin in gnome-extensions?

### ISSUE THREAD

**Issue by brucejuz** [emacs-eaf/emacs-application-framework#1049]
Gnome3 Wayland Native: You need to execute the command cp -r emacs-application-framework/gnome-shell/eaf-wayland@emacs-eaf.org ~/.local/share/gnome-shell/extensions and activate the eaf-wayland@emacs-eaf.org plugin in gnome-extensions

 Here “activate the eaf-wayland@emacs-eaf.org plugin in gnome-extensions”

How to activate?

这里拷贝完了，如何激活eaf-wayland@emacs-eaf.org plugin这个插件？

**Describe the bug**

**To Reproduce**
Ensure you're on the latest master branch, then note the steps to reproduce the behavior.

**Expected behavior**

**Versions (please complete the following info):**
 - Distro and DE/WM:
 - Versions of Dependencies:
 - M-x emacs-version:

**Error logs**
Please check the `*eaf*` buffer, if there is any error in it, paste it here.

**Screenshots**

**Additional context**

**Comment by manateelazycat** [comment]
有中文readme，请仔细阅读
