### ISSUE TITLE
Attempting to open browser - blank buffer and error messages in *eaf*

### ISSUE THREAD

**Issue by bethany7** [emacs-eaf/emacs-application-framework#1054]
```
Error with Permissions-Policy header: Unrecognized feature: 'unload'.
The Cross-Origin-Opener-Policy header has been ignored, because the URL's origin was untrustworthy. 
It was defined either in the final response or a redirect. 
Please deliver the response using the HTTPS protocol. 
You can also use the 'localhost' origin instead. 
See https://www.w3.org/TR/powerful-features/#potentially-trustworthy-origin and https://html.spec.whatwg.org/#the-cross-origin-opener-policy-header.

```
New user, using M-EMACS. Browser loads a blank buffer and says in mini buffer "Buffer id '...' not exists, rebuild EAF buffer. Everything appears to be installed correctly, ran the install and upgrade commands several times. Done a hunt through as many files as I could find looking for anything that might relate, but come up empty handed.

Reproduce: open emacsclient (or emacs, neither works), M-x eaf-open-browser

I hope this is right, I've never left a bug report before.

**Comment by manateelazycat** [comment]
EAF can't works emacsclient
