### ISSUE TITLE
can not open any app with eaf.

### ISSUE THREAD

**Issue by robertzhouxh** [emacs-eaf/emacs-application-framework#1055]
emacs 启动， *eaf* 缓冲区报错

1）emacs 配置

(require 'eaf)
(require 'eaf-browser)
(require 'eaf-git)

2）eaf 安装依赖

[EAF] Installing core dependencies
[EAF] Running pip3 install --user -U epc sexpdata tld lxml mac-app-frontmost PyQt6==6.3.1 PyQt6-Qt6==6.3.1 PyQt6-sip PyQt6-WebEngine==6.3.1 PyQt6-WebEngine-Qt6==6.3.1 @ /Users/zxh/githubs/dotfiles/.emacs.d/vendor/emacs-application-framework
Requirement already satisfied: epc in /Users/zxh/.local/lib/python3.9/site-packages (0.0.5)
Requirement already satisfied: sexpdata in /Users/zxh/.local/lib/python3.9/site-packages (0.0.4)
Requirement already satisfied: tld in /Users/zxh/.local/lib/python3.9/site-packages (0.12.7)
Requirement already satisfied: lxml in /Users/zxh/.local/lib/python3.9/site-packages (4.9.2)
Requirement already satisfied: mac-app-frontmost in /Users/zxh/.local/lib/python3.9/site-packages (2020.12.3)
Requirement already satisfied: PyQt6==6.3.1 in /Users/zxh/.local/lib/python3.9/site-packages (6.3.1)
Requirement already satisfied: PyQt6-Qt6==6.3.1 in /Users/zxh/.local/lib/python3.9/site-packages (6.3.1)
Requirement already satisfied: PyQt6-sip in /Users/zxh/.local/lib/python3.9/site-packages (13.4.1)
Requirement already satisfied: PyQt6-WebEngine==6.3.1 in /Users/zxh/.local/lib/python3.9/site-packages (6.3.1)
Requirement already satisfied: PyQt6-WebEngine-Qt6==6.3.1 in /Users/zxh/.local/lib/python3.9/site-packages (6.3.1)
WARNING: You are using pip version 22.0.4; however, version 23.0 is available.
You should consider upgrading via the '/Users/zxh/.pyenv/versions/3.9.15/bin/python3.9 -m pip install --upgrade pip' command.

[EAF] Installing dependencies for the selected applications

[EAF] Please always ensure the following config are added to your init.el:
(require 'eaf-browser)
(require 'eaf-git)
[EAF] Installation SUCCESS!
[EAF] ------------------------------------------
[EAF] install-eaf.py finished.

3) M-x      eaf-open-browser 

*eaf* 缓冲区日志：

ERROR:epc:AttributeError("'Symbol' object has no attribute 'value'")
ERROR:epc:Unexpected error
Traceback (most recent call last):
  File "/Users/zxh/.local/lib/python3.9/site-packages/epc/handler.py", line 238, in _handle
    (name, uid, args) = unpack_message(sexp)
  File "/Users/zxh/.local/lib/python3.9/site-packages/epc/handler.py", line 87, in unpack_message
    return (data[0].value(), data[1], data[2:])
AttributeError: 'Symbol' object has no attribute 'value'

**Versions 
macos： 10.15.7
emacs： 29.0.50
python:   3.9.15

折腾半天了， 请大佬赐教！

**Comment by yusi1** [comment]
Same problem with me on Emacs 28.2

**Comment by manateelazycat** [comment]
try pip3 install  sexpdata==0.0.3 ?

**Comment by manateelazycat** [comment]
fixed by https://github.com/emacs-eaf/emacs-application-framework/commit/4ea90263650127fdff209fa43c29d7b3f3e4e11f

**Comment by robertzhouxh** [comment]
thanks!
