### ISSUE TITLE
Add Aura to accepted list of AUR helpers

### ISSUE THREAD

**Issue by Cloudcolour** [emacs-eaf/emacs-application-framework#1072]
**Is your feature request related to a problem? Please describe.**
When running `./install-eaf.py` I am told to install one of AUR's helpers. I currently use `aura` as an AUR helper, but it is not recognized. I presume this is because it is not included in the list of aur helpers.

**Describe the solution you'd like**
Please add `aura` to the list of AUR helpers.

**Comment by manateelazycat** [comment]
Update to newest version and try again?

**Comment by manateelazycat** [comment]
Please re-open this issue if still have problem after update
