### ISSUE TITLE
小建议：针对Gentoo，emerge安装依赖时避免重复编译已安装过的软件

### ISSUE THREAD

**Issue by minyu7374** [emacs-eaf/emacs-application-framework#1075]
小问题，感觉没必要提PR

Gentoo里软件大部分是编译安装，相对比较费时。直接使用emerge不带其他参数，即使软件已经安装过，还是会重新编译。所以建议加个--update之类的参数，如下：

<img width="506" alt="image" src="https://user-images.githubusercontent.com/47101063/225798457-325876d1-037d-434a-825f-900ccae890d8.png">

**Comment by manateelazycat** [comment]
已经更新，感谢建议
