### ISSUE TITLE
Wrong Type Argument for string-match

### ISSUE THREAD

**Issue by dylanconklin** [emacs-eaf/emacs-application-framework#1079]
**Describe the bug**
Error of wrong argument type, prevents eaf from loading. The problematic function appear to be string-match.

**To Reproduce**
Install EAF, running the "install-eaf.py" file, and include eaf in "init.el". Then run emacs with "emacs --debug-init"

**Expected behavior**

**Versions (please complete the following info):**
 - Distro and DE/WM: Debian 11, AwesomeWM
 - Versions of Dependencies:
 - M-x emacs-version: Emacs 27.1

**Error logs**
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  string-match("\\(?:[ \11\n\15]+\\)\\'" nil nil)
  string-trim(nil)
  (defvar eaf--emacs-program-name (string-trim (replace-string "." "-" (alist-get 'comm (process-attributes (emacs-pid))))) "Name of Emacs.")

...

  startup--load-user-init-file(#f(compiled-function () #<bytecode 0x158f06d8d9b9>) #f(compiled-function () #<bytecode 0x158f06eec9c9>) t)
  command-line()
  normal-top-level()

**Additional context**
Tested with Emacs 27.1

**Comment by manateelazycat** [comment]
@mumu-lhl Can you help fix this issue?
