### ISSUE TITLE
"string-replace" Should be "replace-string"

### ISSUE THREAD

**Issue by dylanconklin** [emacs-eaf/emacs-application-framework#1080]
**Describe the bug**
Error prevents eaf from loading, string-replace

**To Reproduce**
Include eaf in "init.el", then run emacs with "emacs --debug-config".

**Versions (please complete the following info):**
 - Distro and DE/WM: Debian 11, AwesomeWM
 - Versions of Dependencies:
 - M-x emacs-version: Emacs 27.1

**Error logs**
Debugger entered--Lisp error: (void-function string-replace)
  (string-replace "." "-" (alist-get 'comm (process-attributes (emacs-pid))))
  (string-trim (string-replace "." "-" (alist-get 'comm (process-attributes (emacs-pid)))))
  (defvar eaf--emacs-program-name (string-trim (string-replace "." "-" (alist-get 'comm (process-attributes (emacs-pid))))) "Name of Emacs.")

...

  startup--load-user-init-file(#f(compiled-function () #<bytecode 0x1558586c91b9>) #f(compiled-function () #<bytecode 0x155858829049>) t)
  command-line()
  normal-top-level()

**Additional context**
Tested with Emacs 27.1

**Comment by manateelazycat** [comment]
@mumu-lhl Can you help fix this issue?
