### ISSUE TITLE
eaf-markdown and eaf-terminal failed with HTTP Error 502: Bad Gateway

### ISSUE THREAD

**Issue by sawyerzheng** [emacs-eaf/emacs-application-framework#1086]
**Describe the bug**
`eaf-open` command to open markdown file with eaf-markdown-previewer will lead 502 Bad gateway error.
But other eaf apps is OK, eg: eaf-browser, eaf-terminal.

``` python
qt.webenginecontext: 

GL Type: desktop
Surface Type: OpenGL
Surface Profile: CompatibilityProfile
Surface Version: 4.2
QSG RHI Backend: OpenGL
Using Supported QSG Backend: yes
Using Software Dynamic GL: no
Using Multithreaded OpenGL: yes

Init Parameters:
  *  application-name eaf.py 
  *  browser-subprocess-path /home/sawyer/programs/eaf/.venv/lib/python3.10/site-packages/PyQt6/Qt6/libexec/QtWebEngineProcess 
  *  create-default-gl-context  
  *  disable-features ConsolidatedMovementXY,InstalledApp,BackgroundFetch,WebOTP,WebPayments,WebUSB,PictureInPicture 
  *  disable-setuid-sandbox  
  *  disable-speech-api  
  *  disable-web-security  
  *  enable-features NetworkServiceInProcess,TracingServiceInProcess 
  *  enable-gpu-rasterization  
  *  enable-native-gpu-memory-buffers  
  *  enable-threaded-compositing  
  *  ignore-gpu-blocklist  
  *  in-process-gpu  
  *  use-gl desktop 

Traceback (most recent call last):
  File "/home/sawyer/programs/eaf/core/utils.py", line 52, in on_signal_received
    self._func(obj, *args, **kwargs)
  File "/home/sawyer/programs/eaf/eaf.py", line 155, in new_buffer
    self.create_buffer(buffer_id, url, module_path, arguments)
  File "/home/sawyer/programs/eaf/eaf.py", line 173, in create_buffer
    app_buffer = module.AppBuffer(buffer_id, url, arguments)
  File "/home/sawyer/programs/eaf/app/markdown-previewer/buffer.py", line 57, in __init__
    self.render()
  File "/home/sawyer/programs/eaf/.venv/lib/python3.10/site-packages/retrying.py", line 56, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "/home/sawyer/programs/eaf/.venv/lib/python3.10/site-packages/retrying.py", line 257, in call
    return attempt.get(self._wrap_exception)
  File "/home/sawyer/programs/eaf/.venv/lib/python3.10/site-packages/retrying.py", line 301, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "/home/sawyer/programs/eaf/.venv/lib/python3.10/site-packages/six.py", line 719, in reraise
    raise value
  File "/home/sawyer/programs/eaf/.venv/lib/python3.10/site-packages/retrying.py", line 251, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "/home/sawyer/programs/eaf/app/markdown-previewer/buffer.py", line 81, in render
    with urlopen(url) as f:
  File "/usr/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/usr/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 502: Bad Gateway

```
**To Reproduce**
with `eaf-open` command to open a simple markdown file:
/tmp/test.md
``` md
# Title
````
raise an exception, eg:
![image](https://user-images.githubusercontent.com/44355570/233539508-b8b89c74-6383-41ef-9b27-0b9d127959fa.png)

**Versions (please complete the following info):**
 - Distro and DE/WM: windows + wslg, (but on archlinux + gnome the error is the same)
 - Versions of Dependencies: [latest eaf + latest markdown viewer](https://github.com/emacs-eaf/emacs-application-framework/commit/ae02e955652631b924fa11b4d334b8f9a8df0f06)
 - M-x emacs-version: emacs 28.2
 - python version: python 3.10 installed with python -m venv .venv

**Comment by manateelazycat** [comment]
Markdown-Preview run server by https://github.com/emacs-eaf/eaf-markdown-previewer/blob/ca93e213cdb861b5ec7e1804cf34ede916303426/buffer.py#L63

Can you run `node ./render.js 22343` in terminal, any error from terminal?

**Comment by sawyerzheng** [comment]
the command will start and output nothing as follow:
![image](https://user-images.githubusercontent.com/44355570/233544161-fe1c706e-701b-41f7-bc97-fa2484f0c60a.png)

`telnet localhost 22343` output:
![image](https://user-images.githubusercontent.com/44355570/233544406-3b219bb7-7667-4b70-bd52-dfccdb2802eb.png)

**Comment by manateelazycat** [comment]
strange

**Comment by sawyerzheng** [comment]
![image](https://user-images.githubusercontent.com/44355570/233549205-fda161e4-f553-47fb-a4de-12281b9bdb5f.png)

I print the url and get it as:  http://localhost:50669?input_file=%2Ftmp%2Ftest.md&output_file=%2Ftmp%2Feaf-vfdxbs7s.html&dark_mode=true
And visit the url in browser, I get ok, as following picture:
![image](https://user-images.githubusercontent.com/44355570/233549598-8898290b-998f-4b47-b03e-611d56e3fec2.png)

But I have no clue, why the code cannot execute the line `with urlopen(url) as f:`

**Comment by manateelazycat** [comment]
emacs -Q for compare test

**Comment by sawyerzheng** [comment]
Sorry. emacs -Q will be OK. Its not the eaf's problem.

Its seems some other package effected the url:

- In terminal, `curl url` will result get content: "ok".
- however in my init file + eaf, and call command  `curl url`  inside emacs will get no output.

(Here, the url is the following link generated by eaf-markdown-previewer: http://localhost:50669?input_file=%2Ftmp%2Ftest.md&output_file=%2Ftmp%2Feaf-vfdxbs7s.html&dark_mode=true)

**Comment by sawyerzheng** [comment]
I finally find the reason. Because I enabled proxy before starting eaf.

fix method:
Just disable proxy before starting eaf.
