### ISSUE TITLE
error: gbk codec can't decode byte 0x80 in position 21: illegal multibyte sequence

### ISSUE THREAD

**Issue by ebynapura** [emacs-eaf/emacs-application-framework#1090]
**Describe the bug**
when i open markdown or org file,  the error message in *eaf* is:

  File "~/.emacs.d/site-lisp/emacs-application-framework/app/markdown-previewer/buffer.py", line 53, in __init__
    if "```puml" in f.read() and shutil.which("java") is None:
UnicodeDecodeError: 'gbk' codec can't decode byte 0x80 in position 21: illegal multibyte sequence

**Comment by ebynapura** [comment]
my markdown file code by utf-8, how to change eaf-markdown decode type to utf-8?

**Comment by manateelazycat** [comment]
I have push new commit https://github.com/emacs-eaf/eaf-markdown-previewer/commit/b46af8145007e0d808aaf8f93cb3beb62b5aa630

Update and try again?

**Comment by manateelazycat** [comment]
Please re-open this issue if still have problem.
