### ISSUE TITLE
`eaf-kill-process` doesn't kill all processes

### ISSUE THREAD

**Issue by AndreasMatthias** [emacs-eaf/emacs-application-framework#1096]
**Describe the bug**
From my understanding, `eaf-kill-process` shall kill *all* processes of EAF. But one process survives in my case.

**To Reproduce**
* Start emacs: `emacs -Q`
* Evaluate:

    ```lisp
    (require 'package)
    (package-initialize)
    (use-package eaf
      :load-path "~/.config/emacs/site-lisp/emacs-application-framework")
    ````
* List running processes with `(list-processes)`:
    ```
    *eaf*           84670   run     *eaf*                     /dev/pts/2   Main         python3 /home/andreas/.config/emacs/site-lisp/emacs-application-framework/eaf.py 1216 1065 44557
    EAF EPC Server 2 --      listen   *EAF EPC Server 2*       --           Main         (network server on 127.0.0.1:44557)
    EAF EPC Server 2 <127.0.0.1:41112> --      open     *EAF EPC Server 2* <127.0.0.1:41112> --           Main         (network connection to 127.0.0.1:41112)
    eaf-epc con 4   --      open    *eaf-epc con 4*           --           Main         (network connection to localhost:44207)

    ```
* Kill processes with `(eaf-kill-process)`
* List running processes with `(list-processes`:
    ```
    EAF EPC Server 2 --      listen   *EAF EPC Server 2*       --           Main         (network server on 127.0.0.1:44557)
    ```

**Expected behavior**
I would have expected that, after evaluating `(eaf-kill-process)`, no EAF processes are running any more.

This single remaining process causes `(save-buffers-kill-terminal)` to isssue the warning `Active processes exist, ...`.
Thus I have to call `(delete-process "EAF EPC Server 2")` before killing emacs with `(save-buffers-kill-terminal)`.
Is this the intended behavior?

**Versions (please complete the following info):**
 - Distro and DE/WM: Xubuntu, xfwm4
 - M-x emacs-version: GNU Emacs 28.1

**Comment by manateelazycat** [comment]
Recommand add `(setq confirm-kill-processes nil)` in your config, or PR are welcome!

**Comment by AndreasMatthias** [comment]
See PR #1097.

**Comment by manateelazycat** [comment]
PR is not right, please use `(setq confirm-kill-processes nil)`
