### ISSUE TITLE
EAF 应用抢占焦点

### ISSUE THREAD

**Issue by ententent** [emacs-eaf/emacs-application-framework#1104]
桌面环境：Gnome
操作系统：Arch

复现方式：
全屏打开 Chrome 和 Emacs，Emacs 中启动 EAF 应用如 eaf-pyqterminal，同时 `C-x 3` 左右分屏，可以打开一个 `*dashboard*` 做对比实验

当鼠标悬停在 eaf-pyqterminal 的时候，若用 ALT-TAB 切换到 Chrome，则焦点会立刻回到 Emacs；当鼠标悬停在 `*dashboard*` 时则不会

**Comment by manateelazycat** [comment]
https://github.com/emacs-eaf/emacs-application-framework/blob/07d0515747d91979ff165780fe32ae3e9a7fffb3/core/view.py#L136-#L139

把这几行注释了， 观察一下， 如果抢焦点发生的时候， 事件是什么？

**Comment by ententent** [comment]
鼠标悬停在 EAF 应用时，触发 ALT-TAB 切换到 Chrome 的时候，`*eaf*` 报

1687909131.420022 Leave

松开 ALT-TAB，`*eaf*` 报

1687909132.006536 Enter

**Comment by manateelazycat** [comment]
不应该啊

https://github.com/emacs-eaf/emacs-application-framework/blob/be043317d7dc057298991903c4c8e75964dd85d5/core/view.py#L118

的逻辑是， 只有 PyQt 窗口接收到 Enter 事件才尝试聚焦Emacs， 但是你切换到Chrome浏览器只会触发 Leave 事件

**Comment by ipyffor** [comment]
我也是，连find-file都会触发离开和聚焦，导致我的dock(latte-dock)会重复隐藏和出现

**Comment by manateelazycat** [comment]
@ententent @ipyffor 更新到最新版试试看吧。

**Comment by manateelazycat** [comment]
如果还有问题请随时打开issue
