### ISSUE TITLE
eaf-browser播放B站视频时，CPU占用很高，用其他类chromiumu浏览器播放CPU占用低

### ISSUE THREAD

**Issue by oxsard** [emacs-eaf/emacs-application-framework#1106]
**Describe the bug**
当我使用eaf浏览器播放B站视频，CPU占用在htop里会aa达到150%左右，暂停播放后，占用还是差不多，但是用edge播放就只有50%左右，此时暂停播放，CPU占用为个位数。
**To Reproduce**
Ensure you're on the latest master branch, then note the steps to reproduce the behavior.
已经更新到最新eaf
**Expected behavior**

**Versions (please complete the following info):**
 - Distro and DE/WM: archlinux kde 
 - Versions of Dependencies:
 - M-x emacs-version:30 and 28

**Error logs**
Please check the `*eaf*` buffer, if there is any error in it, paste it here.
没发生什么错误。。。
**Screenshots**
![2023-06-28-215138_2880x1620_scrot](https://github.com/emacs-eaf/emacs-application-framework/assets/1436369/420df351-4745-4782-bc1a-bf40e2c700a7)
![2023-06-28-220122_2880x1620_scrot](https://github.com/emacs-eaf/emacs-application-framework/assets/1436369/2914d6b1-34ac-40df-aa65-addc94c74dee)

**Additional context**
各种依赖已经更新到最新

**Comment by manateelazycat** [comment]
这个没法比

**Comment by oxsard** [comment]
这个以后还有提升的空间吗，理论上，我对python和qt不是很熟悉

Andy Stewart ***@***.***>于2023年6月28日 周三22:14写道：

**Comment by manateelazycat** [comment]
微软和Google是一个团队很多人在优化， 我们只是松散的社区团队， 请不要给我们过高的期待， 至于能不能做到， 要看有意向对这方面有研究的开发者， 目前我不知道有什么方法可以解决这个问题。
