### ISSUE TITLE
打开pdf正常打开docx文件报错

### ISSUE THREAD

**Issue by simpleboy95** [emacs-eaf/emacs-application-framework#1109]
*eaf*中的内容
Traceback (most recent call last):
  File "/home/goodboylqs/.emacs.d/site-lisp/emacs-application-framework/core/utils.py", line 55, in on_signal_received
    self._func(obj, *args, **kwargs)
  File "/home/goodboylqs/.emacs.d/site-lisp/emacs-application-framework/eaf.py", line 155, in new_buffer
    self.create_buffer(buffer_id, url, module_path, arguments)
  File "/home/goodboylqs/.emacs.d/site-lisp/emacs-application-framework/eaf.py", line 168, in create_buffer
    spec = importlib.util.spec_from_file_location("AppBuffer", module_path) # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap_external>", line 802, in spec_from_file_location
TypeError: expected str, bytes or os.PathLike object, not list
请大佬帮忙看一下

**Comment by manateelazycat** [comment]
你安装了 eaf-pdf-viewer 了吗？

**Comment by simpleboy95** [comment]
装了，这是我运行./install-eaf.py后的提示
[EAF] ------------------------------------------
[EAF] Installing core dependencies
[EAF] Running sudo apt -y install wmctrl libxcb-cursor-dev @ /home/goodboylqs/.emacs.d/site-lisp/emacs-application-framework
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libxcb-cursor-dev is already the newest version (0.1.1-4).
wmctrl is already the newest version (1.07-7+b1).
The following packages were automatically installed and are no longer required:
  dc deepin-default-settings-tuning gir1.2-atk-1.0 gir1.2-atspi-2.0 gir1.2-freedesktop gir1.2-gdkpixbuf-2.0 gir1.2-glib-2.0 gir1.2-gtk-3.0 gir1.2-harfbuzz-0.0
  gir1.2-pango-1.0 gir1.2-rsvg-2.0 libblkid-dev libbrotli-dev libbz2-dev libcairo-script-interpreter2 libdjvulibre-dev libegl-dev libegl1-mesa-dev libepoxy-dev
  libexif-dev libexpat1-dev libfontconfig1-dev libfreetype-dev libfreetype6-dev libfribidi-dev libgcrypt20-dev libgirepository-1.0-1 libgl-dev libgl1-mesa-dev
  libgles-dev libgles1 libglvnd-dev libglx-dev libgpg-error-dev libgraphite2-dev libharfbuzz-gobject0 libilmbase-dev libimagequant0 liblcms2-dev liblqr-1-0-dev
  libmagick++-6-headers libmagick++-6.q16-9 libmagickcore-6-arch-config libmagickcore-6-headers libmagickwand-6-headers libmount-dev libopenexr-dev libopengl-dev
  libopenjp2-7-dev libpangoxft-1.0-0 libpixman-1-dev libplist-dev libpython3-dev libpython3.7 libpython3.7-dev libqt5designer5 libqt5help5 libusbmuxd-dev libwayland-bin
  libwayland-dev libwmf-dev libxcomposite-dev libxcursor-dev libxdamage-dev libxfixes-dev libxft-dev libxi-dev libxinerama-dev libxkbcommon-dev libxrandr-dev
  libxrender-dev libxtst-dev libz3-4 libz3-dev pango1.0-tools python-pip-whl python3.7-dev uuid-dev wayland-protocols x11proto-composite-dev x11proto-damage-dev
  x11proto-fixes-dev x11proto-randr-dev x11proto-record-dev x11proto-xinerama-dev
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
[EAF] Running pip3 install --user -U epc sexpdata tld lxml PyQt6==6.5.0 PyQt6-Qt6==6.5.0 PyQt6-sip PyQt6-WebEngine==6.5.0 PyQt6-WebEngine-Qt6==6.5.0 @ /home/goodboylqs/.emacs.d/site-lisp/emacs-application-framework
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Requirement already satisfied: epc in /home/goodboylqs/.local/lib/python3.11/site-packages (0.0.5)
Requirement already satisfied: sexpdata in /home/goodboylqs/.local/lib/python3.11/site-packages (1.0.1)
Requirement already satisfied: tld in /home/goodboylqs/.local/lib/python3.11/site-packages (0.13)
Requirement already satisfied: lxml in /home/goodboylqs/.local/lib/python3.11/site-packages (4.9.3)
Requirement already satisfied: PyQt6==6.5.0 in /home/goodboylqs/.local/lib/python3.11/site-packages (6.5.0)
Requirement already satisfied: PyQt6-Qt6==6.5.0 in /home/goodboylqs/.local/lib/python3.11/site-packages (6.5.0)
Requirement already satisfied: PyQt6-sip in /home/goodboylqs/.local/lib/python3.11/site-packages (13.5.1)
Requirement already satisfied: PyQt6-WebEngine==6.5.0 in /home/goodboylqs/.local/lib/python3.11/site-packages (6.5.0)
Requirement already satisfied: PyQt6-WebEngine-Qt6==6.5.0 in /home/goodboylqs/.local/lib/python3.11/site-packages (6.5.0)
[EAF] Finished installing core dependencies
[EAF] ------------------------------------------
[EAF] ------------------------------------------
[EAF] Installing application dependencies

[EAF] Updating pdf-viewer to newest version...
[EAF] Running git branch @ app/pdf-viewer
[EAF] Running git symbolic-ref HEAD @ app/pdf-viewer
[EAF] Running git pull origin master @ app/pdf-viewer
From https://gitee.com/emacs-eaf/eaf-pdf-viewer
 * branch            master     -> FETCH_HEAD
Already up to date.

[EAF] Updating browser to newest version...
[EAF] Running git branch @ app/browser
[EAF] Running git symbolic-ref HEAD @ app/browser
[EAF] Running git pull origin master @ app/browser
From https://gitee.com/emacs-eaf/eaf-browser
 * branch            master     -> FETCH_HEAD
Already up to date.

[EAF] Installing dependencies for the selected applications

[EAF] Please always ensure the following config are added to your init.el:
(require 'eaf-pdf-viewer)
(require 'eaf-browser)
[EAF] Installation SUCCESS!
[EAF] ------------------------------------------
[EAF] install-eaf.py finished.
eaf-browser可以正常使用，pdf文件也可以正常打开，但是打开doc文件的时候就会出现上述的错误提示

**Comment by manateelazycat** [comment]
装了libreoffice了吗？

**Comment by simpleboy95** [comment]
libreoffice --help
LibreOffice 7.0.4.2 00(Build:2)

Usage: soffice [argument...]
       argument - switches, switch parameters and document URIs (filenames).   

Using without special arguments:                                               
Opens the start center, if it is used without any arguments.                   
   {file}              Tries to open the file (files) in the components        
                       suitable for them.                                      
   {file} {macro:///Library.Module.MacroName}                                  
                       Opens the file and runs specified macros from           
                       the file.
装了，命令也能正常运行= =

**Comment by manateelazycat** [comment]
你是在文件管理器打开 doc 文件还是怎么打开 doc 文件的？ 

提供一下重现步骤吧

**Comment by manateelazycat** [comment]
https://github.com/emacs-eaf/emacs-application-framework/commit/e7cb8f64072e96f42a64a68c98289f9289cdccd4 已经修复了， 更新重启Emacs就好了。
