### ISSUE TITLE
json-read : invalid number format

### ISSUE THREAD

**Issue by balbirthomas** [emacs-eaf/emacs-application-framework#1110]
**Describe the bug**
Launching `eaf-open-jupyter` produces and error "json-read: Invalid number format: 5" and does not  open the jupyter console

**To Reproduce**
On a new Debian/GNU Linux Bookwork (version 12) install, following the README.md file
- clone this git repository
- execute `./install-eaf.py`
- select jupyter console as the application to install

**Expected behavior**
A Jupyter console should have been launched.

**Versions (please complete the following info):**
 - Debian GNU/Linux Version 12
 - List of package installed are
    + lxml                                  4.9.3
    + PyQt6                               6.5.0
    + PyQt6-Qt6                       6.5.0
    + PyQt6-sip                        13.5.1
    + PyQt6-WebEngine         6.5.0
    + PyQt6-WebEngine-Qt6 6.5.0
    + sexpdata                         1.0.1
    + tld                                     0.13

 - M-x emacs-version: 28.2

**Error logs**
Contents of *eaf* buffer are blank.

**Screenshots**
Only one relevant message is seen in *Messages*
```
    json-read: Invalid number format: 5
```

**Additional context**
I am not sure if this is because of a bug in eaf or in the recently released Debian/Bookworm release.

**Comment by manateelazycat** [comment]
Fixed by https://github.com/emacs-eaf/eaf-jupyter/commit/a8e1962d223b443de6151cdd579722bdc054fdd5

Thanks for report.
