### ISSUE TITLE
windows下默认字体大小不对

### ISSUE THREAD

**Issue by heheda123123** [emacs-eaf/emacs-application-framework#1111]
**Describe the bug**
windows上，4k显示器
如图，默认情况下打开eaf-git 和eaf-browser是下面这样的，可以看到比minibuffer中的字体小很多

![image](https://github.com/emacs-eaf/emacs-application-framework/assets/97490782/8dab764d-4cd2-487d-8ac0-c815a13e6b7a)
![image](https://github.com/emacs-eaf/emacs-application-framework/assets/97490782/5852a7d3-db7f-4d72-a68d-96a05299726c)
用-Q启动也存在同样的情况，页面的默认字体比minibuffer小很多
![image](https://github.com/emacs-eaf/emacs-application-framework/assets/97490782/a539b92e-3b72-4991-a17c-b4f04ddebe81)

**To Reproduce**
没有额外配置
```
(add-to-list 'load-path "~/emacs-plugin/emacs-application-framework/")
(require 'eaf)
(require 'eaf-browser)
(require 'eaf-git)
(require 'eaf-pdf-viewer)
```

**Expected behavior**
和我其他字体大小一致，看上面的图可以看到minibuffer的字体大小

**Versions (please complete the following info):**
 - Distro and DE/WM:
 - Versions of Dependencies:
 - M-x emacs-version: GNU Emacs 30.0.50 (build 1, x86_64-w64-mingw32, git sha1 a8056a0) of 2023-07-10

**Error logs**

**Screenshots**

**Additional context**

**Comment by manateelazycat** [comment]
https://github.com/manateelazycat/lazycat-emacs/blob/6f56391c1fe1dd99720448609518dab15a958935/site-lisp/config/init-eaf.el#L132
