### ISSUE TITLE
dbus-call-method: D-Bus error: "org.freedesktop.DBus.Error.UnknownMethod", "Object does not exist at path “/org/eaf/wayland”" [4 times]

### ISSUE THREAD

**Issue by crislar** [emacs-eaf/emacs-application-framework#1116]
On Ubuntu ,22.04.3 LTS Gnome 42.9 Wayland 
GNU Emacs 30.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.33, cairo version 1.16.0) of 2023-09-13

I thought I'd retest whether using eaf is now viable. 
So I reinstalled eaf from git and run install.py from within emacs and on cli 

Gnome Extensions sees EAF Waynland Extensions (sic) 
eaf-wayland@emacs-eaf.org  
with a red symbol and the slider option greyed out. The Description given is
Expose a D-Bus interface to help EAF running on Wayland 
Version 1 

**To Reproduce**
Ensure you're on the latest master branch, then note the steps to reproduce the behavior.
- I think so. Just installed again 

**Expected behavior**

I tested to see if the eaf-browser displays websites - no
Mark set
dbus-call-method: D-Bus error: "org.freedesktop.DBus.Error.UnknownMethod", "Object does not exist at path “/org/eaf/wayland”" [2 times]
[EAF/browser] Opening https://gitlab.com
**Versions (please complete the following info):**
 - Distro and DE/WM:
 - Versions of Dependencies:
 - M-x emacs-version:

**Error logs**
Please check the `*eaf*` buffer, if there is any error in it, paste it here.
current buffer is not supported by eaf 
(it is a bog standard org-mode buffer) 

**Screenshots**

**Additional context**

I've seen reports that some later versions of Gnome may not be supported. But I've not seen info whether this is a permanent situation or if there's a config change to a Dbus config file needed that I've missed.

**Comment by manateelazycat** [comment]
use gnome xorg

wayland code break by gnome change api

**Comment by Vertecedoc4545** [comment]
ive fixed the extension code for gnome 45 @manateelazycat

**Comment by manateelazycat** [comment]
Thanks for patch.
