### ISSUE TITLE
Hyprland 安装更新使用错误

### ISSUE THREAD

**Issue by loverainye** [emacs-eaf/emacs-application-framework#1122]
**Describe the bug**
./install-eaf.py
cc1: 致命错误：main.c：没有那个文件或目录
编译中断。

进入reinput 目录手动编译 （gcc main.c -o reinput `pkg-config --cflags --libs libinput libevdev libudev`）后
打开eaf应用tab图标全变成电池图标，eaf应用不能正常使用，界面卡顿，图像模糊像是使用了滤镜 。

**Versions (please complete the following info):**
 - Distro and DE/WM: Hyprland
 - Versions of Dependencies:
 - M-x emacs-version: 28.2.50

**Error logs**
Please check the `*eaf*` buffer, if there is any error in it, paste it here.

**Screenshots**
![image](https://github.com/emacs-eaf/emacs-application-framework/assets/2232094/2fd134ec-3d09-4238-a231-d44b25293cd8)
![image](https://github.com/emacs-eaf/emacs-application-framework/assets/2232094/ce2d97d6-5d7b-47f2-ac70-2dda4f4c2f94)
![image](https://github.com/emacs-eaf/emacs-application-framework/assets/2232094/5c5436cd-091c-4592-a75a-fbbfcfe20d07)

**Comment by manateelazycat** [comment]
@mumu-lhl 大佬， 能帮忙看一下吗？

**Comment by mumu-lhl** [comment]
试一下 #1124

**Comment by loverainye** [comment]
安装更新已经没有问题， 使用时的卡顿模糊问题依旧存在 ， 在4k显示器不会出现模糊问题，但是如果窗口切换到非4k显示器后会出现字体被拉伸变形 ， md预览会经常出现 libva error: /usr/lib/dri/i965_drv_video.so init failed
  doh set to ""  --  SystemOnly 。终端打开需要一分钟左右，输入延迟也要一分钟， eaf buffer没有异常提示信息。
能不能安装使用提供手动选择桌面环境，能手动选择xwayland  。
  
![image](https://github.com/emacs-eaf/emacs-application-framework/assets/2232094/4b42d66d-0a38-47f2-ae1b-1bc68f55814b)

**Comment by loverainye** [comment]
还是使用了reinput , 执行方式 QT_QPA_PLATFORM=xcb emacs ，需要再设置别的环境变量么 ？ 
libva error: /usr/lib/dri/i965_drv_video.so init failed
doh set to ""  --  SystemOnly
okok
okok
libinput error: client bug: timer event12 hold: scheduled expiry is in the past (-200ms), your system is too slow
reinput: ../libinput-1.24.0/src/libinput.c:2169: libinput_device_unref: Assertion `device->refcount > 0' failed.

**Comment by mumu-lhl** [comment]
你用的 Emacs 是 pgtk 的，不会在 Xwayland 下运行。

> libinput error: client bug: timer event12 hold: scheduled expiry is in the past (-200ms), your system is too slow

这应该就是问题的根源了，你有使用什么修改按键映射的工具吗，如果有的话关一下试试还有没有问题。

**Comment by loverainye** [comment]
没有使用映射工具，好像不是pgtk的 .
emacs-version GNU Emacs 28.2.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.36, cairo version 1.17.6) of 2023-01-08

**Comment by mumu-lhl** [comment]
#1127 现在应该已经好了

**Comment by loverainye** [comment]
可以了。 但是打开eaf应用会打开新窗口， 不知道是不是因为hyprland 的原因 ， 新的窗口xwayland false
{
    "address": "0x5651776f73f0",
    "mapped": false,
    "hidden": false,
    "at": [0, 0],
    "size": [0, 0],
    "workspace": {
        "id": -1,
        "name": ""
    },
    "floating": false,
    "monitor": -1,
    "class": "",
    "title": "",
    "initialClass": "",
    "initialTitle": "",
    "pid": 0,
    "xwayland": true,
    "pinned": false,
    "fullscreen": false,
    "fullscreenMode": 0,
    "fakeFullscreen": false,
    "grouped": [],
    "swallowing": "0x0"
},{
    "address": "0x5651776fc8f0",
    "mapped": true,
    "hidden": false,
    "at": [1371, 1441],
    "size": [931, 491],
    "workspace": {
        "id": 10,
        "name": "10"
    },
    "floating": false,
    "monitor": 1,
    "class": "python3",
    "title": "eaf.py",
    "initialClass": "python3",
    "initialTitle": "eaf.py",
    "pid": 1391243,
    "xwayland": false,
    "pinned": false,
    "fullscreen": false,
    "fullscreenMode": 0,
    "fakeFullscreen": false,
    "grouped": [],
    "swallowing": "0x0"
}

**Comment by mumu-lhl** [comment]
那个补丁有点问题，麻烦再试一下

**Comment by loverainye** [comment]
是一样的， 猜测是 "initialClass": "python3", "initialTitle": "eaf.py"  是这里的问题？ 是不是python eaf.py 获取环境变量导致的 ， 因为我的环境变量都是wayland的  。 所以是不是要用设置全局参数的方式，不要获取环境变量来判断是什么桌面环境 。

**Comment by mumu-lhl** [comment]
运行下 `eaf--build-process-environment`，看下 `QT_QPA_PLATFORM` 是什么吧

**Comment by loverainye** [comment]
QT_QPA_PLATFORM=wayland;xcb  ，  使用QT_QPA_PLATFORM=xcb emacs 方式启动窗口可以在emacs中打开 ，但是终端应用报如下错误 
Traceback (most recent call last):
  File ".emacs.d/elisp/emacs-application-framework/app/pyqterminal/eaf_pyqterm_frontend.py", line 606, in keyPressEvent
    text = chr(ord(text.lower()) - 96)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: chr() arg not in range(0x110000)

Process *eaf* 已放弃 (core dumped)
其它应用
libva error: /usr/lib/dri/i965_drv_video.so init failed

**Comment by mumu-lhl** [comment]
终端的问题已经在 https://github.com/mumu-lhl/eaf-pyqterminal/commit/d1d39c0ffd52a86a5cc25f2c32369d18e6558c01 解决了。

还有别的问题吗？

**Comment by loverainye** [comment]
还有个问题,不确定是 eaf-pyqterminal，还是eaf的  ，打开eaf-pyqterminal   后 emacs 快捷键不能用了 ， 例如meta x ,ctrl c ctrl b  .目前退出使用exit 退出shell后快捷键恢复。

**Comment by manateelazycat** [comment]
pyqterminal 的问题请继续在 pyqterminal 项目中讨论吧， 安装问题解决就先关闭此issue啦。
