### ISSUE TITLE
大佬可不可以考虑一下在eaf-browser、eaf-pdf中实现类似avy的跳转功能

### ISSUE THREAD

**Issue by goodboylqs** [emacs-eaf/emacs-application-framework#1123]
在eaf-browser中想要选中文字、将光标移动到目标位置还是得用鼠标，如果要是能实现avy跳转功能就可以不用鼠标做标记了

**Comment by manateelazycat** [comment]
eaf-browser可以有eww转换得功能，可以通过eww来选文本。

富文本情况下实现任意网页的键盘选择文字工作量很大，我最近没有这么多精力写这种大型插件。

**Comment by goodboylqs** [comment]
好的好的
