### ISSUE TITLE
打开file-manager空白

### ISSUE THREAD

**Issue by feiye13** [emacs-eaf/emacs-application-framework#1131]
**Describe the bug**
打开file-manager是空白的，无法使用。

**To Reproduce**
<M-x> eaf-open-file-manager

**Expected behavior**
file-manager正常显示文件，正常工作。

**Versions (please complete the following info):**
 - Distro and DE/WM: Linux arch 6.1.65-1-lts, kde
 - Versions of Dependencies:
```
local/python-pyqt6 6.6.1-1 (pyqt6)
local/python-pyqt6-sip 13.6.0-1
local/python-pyqt6-webengine 6.6.0-1 (pyqt6)
local/qt6-multimedia 6.6.1-1 (qt6)
local/qt6-svg 6.6.1-1 (qt6)
local/libvdpau 1.5-2
    Nvidia VDPAU library
local/libvdpau-va-gl 0.4.2-3

```
 - M-x emacs-version: GNU Emacs 30.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.38, cairo version 1.18.0) of 2023-12-08

**Error logs**
```
doh set to ""  --  SystemOnly
libva error: vaGetDriverNames() failed with unknown libva error
[JavaScript console]: Uncaught ReferenceError: updateGitLog is not defined
[JavaScript console]: Uncaught TypeError: Cannot read properties of undefined (reading 'install')
[JavaScript console]: Uncaught ReferenceError: init is not defined
[JavaScript console]: Uncaught ReferenceError: changePath is not defined
[JavaScript console]: Uncaught ReferenceError: updateGitLog is not defined
[JavaScript console]: Uncaught ReferenceError: setPreview is not defined

```
使用`emacs -q`加载有和上边相同的错误，
```
(add-to-list 'load-path "~/.emacs.d/lisp/packages/emacs-application-framework/")
(require 'eaf)

(require 'eaf-file-manager)

```

**Screenshots**

**Additional context**
我之前有一段时间没有更新，更新后file-manager就无法使用，但是发现某些能用，有些也是打不开.
eaf-git, browser,pdf可以正常工作。camera之前试的也是空白。
今天把eaf的文件夹删除，重新克隆安装，依然有问题。

**Comment by manateelazycat** [comment]
切换到 emacs-application-framework/app/file-manager 目录
执行命令 rm -rf ./node_modules 删除旧的npm包
git pull --rebase 更新到最新版
npm install ; npm run build 重新构建file-manager的JS部分
重新启动 EAF 就可以了

原因是因为Github机器人提示升级 axios 这个包后， 我在外出差没有重新构建来测试， 引入的新问题。

已经修复了， 感谢提醒。
