### ISSUE TITLE
Grammar improvements in Readme.md

### ISSUE THREAD

**Issue by mohsenBanan** [emacs-eaf/emacs-application-framework#1133]
Change: 

What if Emacs has a real browser?
What if this PDF or video file can be viewed efficiently without leaving Emacs?

to:

What if Emacs had a real browser?
What if this PDF or video file could be viewed efficiently without leaving Emacs?

The expressions if, supposing, if only, what if can be used to introduce hypothetical situations and followed by the simple past tense to indicate that the condition they introduce is imaginary.

**Comment by MatthewZMD** [comment]
Great catch, thanks!
