### ISSUE TITLE
EAF keep warning in emacs daemon

### ISSUE THREAD

**Issue by gyxx-xc** [emacs-eaf/emacs-application-framework#1154]
**Describe the bug**
When emacs run as daemon, every time when forcus changed, it shows the warnning (in Minibuffer):
```
dbus-call-method: D-Bus error: "org.freedesktop.DBus.Error.UnknownMethod", "Object does not exist at path “/org/eaf/wayland”"Error during redisplay: (eval (doom-modeline-segment--check)) signaled (args-out-of-range 1 1)
Error during redisplay: (eval (doom-modeline-segment--check)) signaled (args-out-of-range 1 1) [3 times]
```
The function of the eaf apps is normal.

This problem keep happens in my last system(debain) and in the system I'm using now(arch)

**To Reproduce**
I use `~/.emacs.d/init.el` file as follow to test
```
(add-to-list 'load-path "~/.emacs.d/site-lisp/emacs-application-framework/")
(require 'eaf)
(require 'eaf-image-viewer)
(provide 'init)
```
And open a emacsclient

**Expected behavior**
not showing the warning

**Versions (please complete the following info):**
 - Distro and DE/WM: 6.9.7-Arch1-1 with gnome 46.3.1 in Xorg (Mutter)
 - M-x emacs-version: GNU Emacs 29.4 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.42, cairo version 1.18.0)

**Error logs**
none

**Comment by manateelazycat** [comment]
eaf not support daemon
