### ISSUE TITLE
wsl2 下运行出错

### ISSUE THREAD

**Issue by JuneOx** [emacs-eaf/emacs-application-framework#1156]
**Versions (please complete the following info):**
 - manjaro
   emacs29.4
   gnome 46.4-1

**Error logs**
(gnome-shell:19141): GNOME Shell-CRITICAL **: 17:11:53.168: Exception in method call: get_active_window: TypeError: w.title is null

Stack trace:
  get_windows/<@file:///home/chengliye/.local/share/gnome-shell/extensions/eaf-wayland@emacs-eaf.org/extension.js:43:25
  get_windows@file:///home/chengliye/.local/share/gnome-shell/extensions/eaf-wayland@emacs-eaf.org/extension.js:43:13
  get_active_window@file:///home/chengliye/.local/share/gnome-shell/extensions/eaf-wayland@emacs-eaf.org/extension.js:47:17
  _handleMethodCall@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:329:38
  _wrapJSObject/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:408:34
  @resource:///org/gnome/shell/ui/init.js:21:20

**Comment by manateelazycat** [comment]
不支持 Wayland native
