### ISSUE TITLE
Installation stuck at "netease-cloud-music"

### ISSUE THREAD

**Issue by thyeun** [emacs-eaf/emacs-application-framework#1159]
**Describe the bug**
After install using M-x eaf-installation & update, a message asked to using ```./install-eaf.py --force``` to install some others package.

while using ```./install-eaf.py --force```

Get stuck at below for more than three hours. 
```
[EAF] Running npm install --force @ /home/thyeun/.emacs.d/site-lisp/emacs-application-framework/app/netease-cloud-music
npm warn using --force Recommended protections disabled.
(node:332149) ExperimentalWarning: CommonJS module /usr/lib/node_modules/npm/node_modules/debug/src/node.js is loading ES Module /usr/lib/node_modules/npm/node_modules/supports-color/index.js using require().
Support for loading ES Module in require() is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
npm warn deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
npm warn deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read https://babeljs.io/env to update!
npm warn deprecated chokidar@1.7.0: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm warn deprecated core-js@2.6.12: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
```

Should i ignore it or keep continue? 

But i'm not sure either above related to eaf or not, and some how i cant start using ```eaf-open-browser``` when try it on emacs. i get blank page after try an url.

**To Reproduce**
-

**Expected behavior**
Should continue until all finish.

**Versions (please complete the following info):**
 - Distro and DE/WM: Arch linux/ Hyprland
 - Versions of Dependencies: 6.11.6-arch-1/0.44.1-4
 - M-x emacs-version: emacs-wayland/29.4-3

![241111_17h51m52s_screenshot](https://github.com/user-attachments/assets/b7c55aa7-ca78-42b2-8273-f131f0d296bd)

**Comment by manateelazycat** [comment]
Fixed by https://github.com/emacs-eaf/emacs-application-framework/commit/c7127a07973e4ef3815922cfd34f8795bb8e6aa6
