### ISSUE TITLE
URL support local option, local keybinding and local css style.

### ISSUE THREAD

**Issue by alejandrogallo** [emacs-eaf/emacs-application-framework#545]
I'm a happy user of qutebrowser
https://github.com/qutebrowser/qutebrowser/
and I've used many other similar browsers, and I have to say
that qutebrowser is impressively consistent, fast, well-maintained and stable.

Of course, I'd love to use EAF's browser in emacs with some of the features
of qutebrowser that I think EAF does not support and does not plan on it
either.

# 1. Set options locally matching urls

In qutebrowser you can change some options locally using
**patterns**, i.e., if I don't want to
allow javascript or images in githubs' trending pages, I'd
do something like this

```python
with config.pattern("*://github.com/trending/*") as p:
    p.content.images = False
    p.content.javascript.enabled = False
```

This would be awesome to have.

# 2. Url-based bindings

Something that is yet to be implemented in qutebrowser
are url-dependent keybindings, which to my knowledge no
browser supports (maybe nyxt?).

# 3. Url-dependent css stylesheets

This is not really supported in qutebrowser,
but would also be to my knowledge the only browser supporting this.

# 4. Ivy-like selection of history, bookmarks and quickmarks

An impressive feature of qutebrowser
is the mixing of urls from the history, quickmarks and bookmarks
in the same `M-x`-like interface.
I'm not sure that EAF supports this, specially the difference
between history, quickmarks and bookmarks, but this is definitely
something worth considering.

**Comment by manateelazycat** [comment]
Point 4 has support, please check wiki

**Comment by MatthewZMD** [comment]
> # 4. Ivy-like selection of history, bookmarks and quickmarks
> An impressive feature of qutebrowser
> is the mixing of urls from the history, quickmarks and bookmarks
> in the same `M-x`-like interface.

You can `M-x eaf-open-browser-with-history` to automatically search history using Ivy if you have Ivy configured.

You can also `M-x eaf-open-bookmark` or `C-c b` to automatically search bookmarks using Ivy similarly.

Could you clarify what quickmark is?

> I'm not sure that EAF supports this, specially the difference
> between history, quickmarks and bookmarks, but this is definitely
> something worth considering.

Other than that, great suggestions!

**Comment by alejandrogallo** [comment]
Hi!

Ok let me define some concepts, this is a screenshot that basically
says more than what I can possibly explain 😄 

![image](https://user-images.githubusercontent.com/12715358/106177399-c308f700-6198-11eb-87cc-f4a082048804.png)

- **BOOKMARKS**
  I guess they're the same in every such program.
- **QUICKMARKS**
  They're basically named bookmarks, so you can do
  ```
  :open basis
  ```
  and then you will jump to the url associated with it.
- **SEARCH ENGINES**
  They are search engines :'D
  They're basically the same as the duckduckgo bangs.
  For instance a search engine for french words would be
  ```lisp
  (add-search-engine
    ("fr" . "https://www.le-dictionnaire.com/definition/{}"))
  ```
  and then when you do `M-x open-url`
  you could just type `fr bonjour` and would then replace
  `{}` by bonjour (urlencoded) etc..

I have grown accostumed to this way of presenting all options
that qutebrowser does, and I know that I'm among many people
finding this extremely intuitive and useful.

But I think all this I could hack myself, I wanted specially to get a feeling
of how realistic you think it is to have url-dependent key-bindings, this
would be indeed a killer feature...

**Comment by manateelazycat** [comment]
> Hi!
> 
> Ok let me define some concepts, this is a screenshot that basically
> says more than what I can possibly explain 
> 
> ![image](https://user-images.githubusercontent.com/12715358/106177399-c308f700-6198-11eb-87cc-f4a082048804.png)
> 
> * **BOOKMARKS**
>   I guess they're the same in every such program.
> * **QUICKMARKS**
>   They're basically named bookmarks, so you can do
>   ```
>   :open basis
>   ```
>   
>   
>   and then you will jump to the url associated with it.
> * **SEARCH ENGINES**
>   They are search engines :'D
>   They're basically the same as the duckduckgo bangs.
>   For instance a search engine for french words would be
>   ```lisp
>   (add-search-engine
>     ("fr" . "https://www.le-dictionnaire.com/definition/{}"))
>   ```
>   
>   
>   and then when you do `M-x open-url`
>   you could just type `fr bonjour` and would then replace
>   `{}` by bonjour (urlencoded) etc..
> 
> I have grown accostumed to this way of presenting all options
> that qutebrowser does, and I know that I'm among many people
> finding this extremely intuitive and useful.
> 
> But I think all this I could hack myself, I wanted specially to get a feeling
> of how realistic you think it is to have url-dependent key-bindings, this
> would be indeed a killer feature...

You can play my another plugin snails with EAF.

I believe this feature should finish by completion plugin, such as, ivy, helm, snails, not should add in EAF, EAF has provide enough interface use for completion.

**Comment by manateelazycat** [comment]
I haven't plan to develop those features.

Point 4 has implement by EAF with Snails.

Point 1 ~ Point 3 is cool, but those not useful to me, PR are welcome, I don't want develop the features I'm not use, sorry.

**Comment by MatthewZMD** [comment]
> * **QUICKMARKS**
>   They're basically named bookmarks, so you can do
>   ```
>   :open basis
>   ```
>   
>   
>   and then you will jump to the url associated with it.

The EAF bookmark uses the default Emacs bookmark interface, which means you can `C-x r m` to store (and give a name for) a bookmark, and either use `C-x r l` to view all of your bookmarks (including non-EAF ones) or `C-c b` for EAF-specific bookmarks. I guess it suffices for your example of quickmark.

**Comment by MatthewZMD** [comment]
> * **SEARCH ENGINES**
>   They are search engines :'D
>   They're basically the same as the duckduckgo bangs.
>   For instance a search engine for french words would be
>   ```lisp
>   (add-search-engine
>     ("fr" . "https://www.le-dictionnaire.com/definition/{}"))
>   ```
>   
>   
>   and then when you do `M-x open-url`
>   you could just type `fr bonjour` and would then replace
>   `{}` by bonjour (urlencoded) etc..

Similar implementations are the `eaf-browser-search-engines` and `eaf-browser-default-search-engine` variables.

**Comment by alejandrogallo** [comment]
What about url-dependent bindings, is this something
that you think it's implementable?

**Comment by MatthewZMD** [comment]
> What about url-dependent bindings, is this something that you think it's implementable?

Yes, and it shouldn't be very difficult, just need someone with enough time to work on it. I personally am very busy this week, I can take a look maybe next week, when I have time.

**Comment by c1-g** [comment]
> What about url-dependent bindings, is this something that you think it's implementable?

Possible but, can you give me some realistic use cases or scenarios where this will actually be used? I also use qutebrowser and I can't think of any time that I needed this feature at all.

**Comment by c1-g** [comment]
> # 3. Url-dependent css stylesheets
> This is not really supported in qutebrowser,
> but would also be to my knowledge the only browser supporting this.

Qutebrowser have this functionality. See [content.user_stylesheets](https://qutebrowser.org/doc/help/settings.html#content.user_stylesheets) or Search for `content.user_stylesheets` in its [FAQ](https://qutebrowser.org/doc/faq.html)

But, you can see its rough implementation on my fork [here](https://github.com/c1-g/eaf-browser/tree/user-css).
I've used the `load_css` function from [webengine.py](https://github.com/emacs-eaf/emacs-application-framework/search?q=load_css) to load the css file matching a url regexp from the variable `eaf-browser-user-css-alist`. Here is the result from using a css file from [solarized-everywhere](https://github.com/alphapapa/solarized-everything-css/blob/master/css/solarized-dark/solarized-dark-all-sites.css)
![user-css branch](https://z.zz.fo/wcYHt.png "EAF Browser + solarized everywhere")

**Comment by manateelazycat** [comment]
If someone need those features, please send PR, I'm glad to merge, thanks. ;)
