### ISSUE TITLE
Command eaf-open-browser disappeared

### ISSUE THREAD

**Issue by tvraman** [emacs-eaf/emacs-application-framework#775]
- If EAF was working correctly until a recent `git pull`, please refer to [Mandatory Procedures to Keep Your EAF Up-to-Date](https://github.com/manateelazycat/emacs-application-framework/discussions/527?sort=new) first.
- Please check the `*eaf*` buffer, if there is any error shown in the `*eaf*` buffer, paste it here.
How do I open a URL? Command eaf-open-browser has disappeared.

**Describe the bug**

**To Reproduce**
Ensure you're on the latest master branch, then note the steps to reproduce the behavior.

**Expected behavior**

**Versions (please complete the following info):**
 - Distro and DE/WM:
 - Versions of Dependencies:
 - M-x emacs-version:

**Screenshots**

**Additional context**

**Comment by manateelazycat** [comment]
Follow below step:
1. Download emacs-application-framework
2. ./install-eaf.py
3. Then add below require commands in your .emacs

(require 'eaf-js-video-player)
(require 'eaf-org-previewer)
(require 'eaf-image-viewer)
(require 'eaf-music-player)
(require 'eaf-file-sender)
(require 'eaf-file-browser)
(require 'eaf-airshare)
(require 'eaf-system-monitor)
(require 'eaf-browser)
(require 'eaf-jupyter)
(require 'eaf-pdf-viewer)
(require 'eaf-video-player)
(require 'eaf-demo)
(require 'eaf-netease-cloud-music)
(require 'eaf-mindmap)
(require 'eaf-terminal)
(require 'eaf-markdown-previewer)
(require 'eaf-vue-demo)
(require 'eaf-file-manager)
(require 'eaf-camera)

**Comment by MatthewZMD** [comment]
If EAF was working correctly until a recent git pull, please refer to Mandatory Procedures to Keep Your EAF Up-to-Date first.

**Comment by tvraman** [comment]
None of those files for those requires are in the git checkout ...

-- 

Thanks,

--Raman(I Search, I Find, I Misplace, I Research)
♈ Id: kg:/m/0285kf1  🦮

**Comment by MatthewZMD** [comment]
Please read carefully again.

**Comment by MatthewZMD** [comment]
You need to run the new `install-eaf.py` script, which will interactively lets you install EAF applications, including the browser application from its own repository.

**Comment by MatthewZMD** [comment]
Out of pure curiosity, since I see you reply through the email, are you not using the Github website to submit this issue? When you submit the issue, are you able to see the issue template?

Because I see the issue template is left empty, and I intentionally added to the first line to the issue template directing users to the [Mandatory Procedures to Keep Your EAF Up-To-Date](https://github.com/emacs-eaf/emacs-application-framework/discussions/527?sort=new) page, to help users like you avoid getting lost after a `git pull`, and avoid frustration and needless issues to both of us.

If this is not working out, I may have to think about implementing a reply bot that will redirect users to the that webpage.

**Comment by tvraman** [comment]
Matthew Zeng ***@***.***> writes:

I had done that and answered "y" but it did not work.

I finally blew away my git clone, cloned afresh and built it, now it all
works :-)

> You need to run the new install-eaf.py script, which will
> interactively lets you install EAF applications, including the browser
> application from its own repository.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android.
>

-- 

Thanks,

--Raman(I Search, I Find, I Misplace, I Research)
♈ Id: kg:/m/0285kf1  🦮

**Comment by tvraman** [comment]
Matthew Zeng ***@***.***> writes:

Github web site doesn't work well for me (I cannot see). I use Magit and
Forge for everything; I apologise for these things being beyond my
control.
> Out of pure curiosity, since I see you reply through the email, are
> you not using the Github website to submit this issue? When you submit
> the issue, are you able to see the issue template?
>
> Because I see the issue template is left empty, and I intentionally
> added to the first line to the issue template directing users to the
> Mandatory Procedures to Keep Your EAF Up-To-Date page, to help users
> like you avoid getting lost after a git pull, and avoid frustration
> and needless issues to both of us.
>
> If this is not working out, I may have to think about implementing a
> reply bot that will redirect users to the that webpage.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android.
>

-- 

Thanks,

--Raman(I Search, I Find, I Misplace, I Research)
♈ Id: kg:/m/0285kf1  🦮

**Comment by MatthewZMD** [comment]
No problem, you don't need to apologize! Glad it finally works for you.
