### ISSUE TITLE
EAF-Browser: allow to open link in other window

### ISSUE THREAD

**Issue by taquangtrung** [emacs-eaf/emacs-application-framework#793]
**Is your feature request related to a problem? Please describe.**

When using EAF Browser for googling, everything I click on a link or use the shortcut key `f`, `F` to examine a result, the new webpage is open exactly on the same window with the Google webpage.

**Describe the solution you'd like**

I'd like that EAF-Browser can open the selected link in a separate window. This will be helpful when I have 2 windows side by side, so I can quickly switch between the Google page and the page related to the selected link.

**Describe alternatives you've considered**

I think it needs to be implemented in the `webengine.py` file.

I tried to hack on the Emacs code, such as advising the function when `RET` is entered in the minibuffer, but not successfully.

**Comment by manateelazycat** [comment]
You need 

```
def open_url_in_new_tab(url):
    eval_in_emacs('eaf-open-browser', [url])
```

You only need write some javascript to parse link in selected area, then call above API.

**Comment by taquangtrung** [comment]
Hi, do you think it is worth to implement a feature like that?

I figured out how to implement it, and I can create a PR too.

**Comment by MatthewZMD** [comment]
Definitely, bind it to some key and open a PR :)
