### ISSUE TITLE
running ./install-eaf.py give KeyError: 'openbsd6'  on openbsd

### ISSUE THREAD

**Issue by bubblessed** [emacs-eaf/emacs-application-framework#847]
./install-eaf.py                                                                                                                                                      
[EAF] ------------------------------------------
[EAF] Installing core dependencies
Traceback (most recent call last):
  File "./install-eaf.py", line 373, in <module>
    main()
  File "./install-eaf.py", line 358, in main
    install_core_deps(distro, deps_dict)
  File "./install-eaf.py", line 215, in install_core_deps
    install_py_deps(deps_dict["pip"][sys.platform])
KeyError: 'openbsd6'

**Comment by MatthewZMD** [comment]
Thanks for the report. This error will not happen in the latest commit anymore. Please `git pull`, run this script again, and re-open if EAF isn't working on OpenBSD.
