### ISSUE TITLE
logging feature for emacs-eaf 

### ISSUE THREAD

**Issue by bubblessed** [emacs-eaf/emacs-application-framework#849]
Within emacs27.2: below message is seen, everything looks as if it is working, all the apps are installed on local computer yet eaf is unable to open, for example "eaf-browser" with no errors or messages of its status on OpenBSD 6.9. Same thing for all the other apps in the list

[EAF] Installing dependencies for installed applications
[EAF] Finished installing applications and their dependencies
[EAF] Please ensure the following are added to your init.el:
(require 'eaf-airshare)
(require 'eaf-browser)
(require 'eaf-camera)
(require 'eaf-demo)
(require 'eaf-file-browser)
(require 'eaf-file-manager)
(require 'eaf-file-sender)
(require 'eaf-image-viewer)
(require 'eaf-jupyter)
(require 'eaf-markdown-previewer)
(require 'eaf-mermaid)
(require 'eaf-mindmap)
(require 'eaf-music-player)
(require 'eaf-org-previewer)
(require 'eaf-pdf-viewer)
(require 'eaf-system-monitor)
(require 'eaf-terminal)
(require 'eaf-video-player)
(require 'eaf-vue-demo)
(require 'eaf-netease-cloud-music)
[EAF] Please run both 'git pull' and 'install-eaf.py' (M-x eaf-install-and-update) to update EAF, applications and their dependencies.
[EAF] Use the flag '--install-new-apps' to install previously uninstalled or new apps.
[EAF] ------------------------------------------
[EAF] install-eaf.py finished.

**Comment by MatthewZMD** [comment]
This is verifying that the dependencies that is specified had been installed successfully. There is no way of knowing whether that's *all* the dependencies unless explicitly specified and working condition unless you test it by `M-x eaf-open`. This is not what the install script is designed to do.
