### ISSUE TITLE
Missing "pkg_add" for OpenBSD6.9 in dependencies.json file in emacs-application-framework folder

### ISSUE THREAD

**Issue by bubblessed** [emacs-eaf/emacs-application-framework#850]
"pkg": [
        "wmctrl",
        "node",
        "npm",
        "glib",
        "py38-qt5-sip",
        "py38-qt5-webengine"

], 
emacs version 27.2, no error messages in eaf-buffer

**Comment by MatthewZMD** [comment]
Feel free to create a PR

**Comment by manateelazycat** [comment]
> ```
> "pkg": [
>     "wmctrl",
>     "node",
>     "npm",
>     "glib",
>     "py38-qt5-sip",
>     "py38-qt5-webengine"
> ```
> 
> ],
> emacs version 27.2, no error messages in eaf-buffer

OpenBSD just need use pkg_add instead pkg ?

**Comment by MatthewZMD** [comment]
Are the dependencies the same?

**Comment by manateelazycat** [comment]
> Are the dependencies the same?

don't know, haven't environment

**Comment by manateelazycat** [comment]
@bubblessed Can you help use add pkg_add support ?

**Comment by c1-g** [comment]
I just checked the OpenBSD ports collection [here](https://openports.se/) and found these packages
[py-qt5](https://openports.se/x11/py-qt5)
[py-sip-qt5](https://openports.se/x11/py-sip-qt5)
[glib2](https://openports.se/devel/glib2)
[node](https://openports.se/lang/node)
[wmctrl](https://openports.se/x11/wmctrl)
[py-qtwebengine](https://openports.se/www/py-qtwebengine)

Can someone with an OpenBSD machine try installing these and see if EAF works?

**Comment by manateelazycat** [comment]
Welcome OpenBSD guys send new PR, close this issue. ;)
