### ISSUE TITLE
eaf-browser GLX error

### ISSUE THREAD

**Issue by timlod** [emacs-eaf/emacs-application-framework#871]
**Describe the bug**
I get an error when running `eaf-browser`.

**To Reproduce**
`eaf-open-browser` and then some URL, although this is probably specific to my setup (see Versions and Additional context).

**Expected behavior**
The browser opens.

**Versions (please complete the following info):**
 - Distro and DE/WM: Debian 11, headless (not sure which DE/WM would be used )
 - M-x emacs-version: GNU Emacs 27.1 (build 1, x86_64-pc-linux-gnu, X toolkit, Xaw3d scroll bars) of 2021-03-28, modified by Debian

**Error logs**
```qt.qpa.xcb: X server does not support XInput 2
qt.qpa.xcb: QXcbConnection: XCB error: 1 (BadRequest), sequence: 169, resource id: 133, major code: 130 (Unknown), minor code: 47
WARNING: Application calling GLX 1.3 function "glXCreatePbuffer" when GLX 1.3 is not supported!  This is an application bug!
[2968479:2968791:1109/145354.487042:ERROR:gl_surface_glx_qt.cpp(141)] GLX 1.3 or later is required.
[2968479:2968791:1109/145354.487070:ERROR:gl_ozone_glx_qt.cpp(57)] GLSurfaceGLXQt::InitializeOneOff failed.

Process *eaf* segmentation fault
```

**Additional context**
The server is headless (which could be an issue? `eaf-demo` runs though).
Emacs is started with `emacs --daemon` and its GUI accessed through X2Go with `emacsclient -c`.

I realize this isn't exactly reproducible as this is likely something specific to my setup (I'm not well-versed as to how DE/WMs work under a headless, remote server), but perhaps this is enough information to point me in the right direction.

The goal is to open local HTML files for interactive plots inside Emacs.

**Comment by manateelazycat** [comment]
Looks something wrong with Qt, can you test EAF with normal environment, such as Gnome or KDE, for test compare?

**Comment by dotgreg** [comment]
Not sure it is the same issue but I had something similar, to me related to qt and amd64, I could reproduce it on qutebrowser too.
Maybe that thread can help : https://github.com/qutebrowser/qutebrowser/issues/4429
What I did was to was adding export QT_XCB_GL_INTEGRATION=none inside ~/.bash_profile and /etc/profile.d/qt_gl.sh then logout/login

**Comment by manateelazycat** [comment]
EAF just develop for normal DE, not support headless sistuation, sorry that I can't help you.
