### ISSUE TITLE
npm : Depends: node-gyp (>= 3.6.2~) but it is not going to be installed

### ISSUE THREAD

**Issue by scofild429** [emacs-eaf/emacs-application-framework#872]
Ubuntu 20.04
python 3.8
node 16.13.0
npm 8.1.0
sudo npm install -g node-gyp
sudo ln -s  /cd /opt/node-v16.13.0-linux-x64/lib/node_modules/node-gyp/lib/node-gyp.js /user/local/bin/node-gyp
$ node-gyp --version v8.4.0

clone from Git, Bash: sudo ./install-eaf.py
still get folllowing
....................................................
[EAF] ------------------------------------------
[EAF] Installing core dependencies
[EAF] Running sudo apt -y install wmctrl nodejs npm libglib2.0-dev python3-pyqt5 python3-sip python3-pyqt5.qtwebengine python3-pygit2 @ /home/si/.emacs.d/site-lisp/emacs-application-framework
Reading package lists... Done
Building dependency tree       
Reading state information... Done
nodejs is already the newest version (14.18.1-deb-1nodesource1).
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 nodejs : Conflicts: npm
 npm : Depends: node-gyp (>= 3.6.2~) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

can someone please give me a hit?

**Comment by manateelazycat** [comment]
just install-eaf.el , not need sudo

**Comment by scofild429** [comment]
thanks for your answer, it's not helpful.
without sudo, the password of user will be still asked at the first time, 
then comes the same issue, still looking...

**Comment by manateelazycat** [comment]
It's looks like your system package conflict, not problem of EAF, sorry can't help.

**Comment by autarch** [comment]
The problem is that EAF is trying to install a package named `npm`, but if you're using the nodesource debian packages, then you already have npm installed as part of the `nodejs` package.

I think the fix is probably for EAF to check to see if an `npm` executable is already present and not try to install that package if it is. I worked around this with the `--ignore-core-deps`, but only after it had already installed all the _other_ packages it needs and then failed with npm.

**Comment by MatthewZMD** [comment]
> The problem is that EAF is trying to install a package named `npm`, but if you're using the nodesource debian packages, then you already have npm installed as part of the `nodejs` package.
> 
> I think the fix is probably for EAF to check to see if an `npm` executable is already present and not try to install that package if it is.

Fair point, I've added this functionality to the install script. It currently checks for `node` and `npm`.
