### ISSUE TITLE
Type error on eaf-open-browser

### ISSUE THREAD

**Issue by Cons-Cat** [emacs-eaf/emacs-application-framework#873]
**Describe the bug**
I open any website with ``M-x eaf-open-browser``, and get an error in ``*eaf*``, and nothing renders.

**To Reproduce**
I'm on 40a4f5f all I do is run ``eaf-open-browser``, and put input a url (excluding the ``https://``) like ``xahlee.info``.

**Expected behavior**
A website starts to render.

**Versions (please complete the following info):**
 - Distro and DE/WM: Void Linux / Openbox
 - Versions of Dependencies: Python 3.10
 - M-x emacs-version: ``GNU Emacs 29.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.29, cairo version 1.16.0) of 2021-10-03``

**Error logs**
```
Process *eaf* aborted
Traceback (most recent call last):
  File "/home/conscat/.emacs.d/eaf-browser/buffer.py", line 154, in drawForeground
    painter.drawRect(0, 0, rect.width() * self.progressbar_progress * 1.0 / 100, self.progressbar_height)
TypeError: arguments did not match any overloaded call:
  drawRect(self, QRectF): argument 1 has unexpected type 'int'
  drawRect(self, int, int, int, int): argument 3 has unexpected type 'float'
  drawRect(self, QRect): argument 1 has unexpected type 'int'

Process *eaf* aborted
```

**Comment by manateelazycat** [comment]
Please update eaf-browser to newest version.

Please re-open issue if have any other problem, thanks for report.

**Comment by Cons-Cat** [comment]
It works for me now. Thank you a lot!
