### ISSUE TITLE
with-no-warnings: Symbol’s value as variable is void: eaf-browser-keybinding

### ISSUE THREAD

**Issue by damoncro** [emacs-eaf/emacs-application-framework#879]
**Describe the bug**
```with-no-warnings: Symbol’s value as variable is void: eaf-browser-keybinding```

**To Reproduce**
If I load `eaf-evil` but not `eaf-browser`, will get the warning.

https://github.com/emacs-eaf/emacs-application-framework/blob/master/extension/eaf-evil.el#L61

**Expected behavior**

**Versions (please complete the following info):**
 - Distro and DE/WM:
 - Versions of Dependencies:
 - M-x emacs-version:

**Error logs**
Please check the `*eaf*` buffer, if there is any error in it, paste it here.

**Screenshots**

**Additional context**

**Comment by manateelazycat** [comment]
load eaf-browser ;）
