### ISSUE TITLE
No yay in arch linux, please let users specify the AUR helper

### ISSUE THREAD

**Issue by VitalyAnkh** [emacs-eaf/emacs-application-framework#880]
**Describe the bug**
The `install-eaf.py` suppose there is a yay in my Arch Linux, but there is not. Thus install failed.

**To Reproduce**
Obviously.

**Expected behavior**
Install EAF successfully.

**Versions (please complete the following info):**
 - Distro and DE/WM: Arch Linux

**Comment by manateelazycat** [comment]
you need install yay first
