### ISSUE TITLE
EAF Browser how use and configure adblocker?

### ISSUE THREAD

**Issue by poulpoulsen** [emacs-eaf/emacs-application-framework#881]
hello,
i just installed and tested your package (eaf with extensions).
until now all works! very good.
now i want to configure the browser like i use to with chrome and vivaldi.
therefore i first set the adblocker to t.
but how could i see in detail, in which way the adblock works.
i can not see any lists to choose, or any logs to see what gets blocked.

any clearance will be helpful.

Thanks
Poul

**Comment by manateelazycat** [comment]
https://github.com/emacs-eaf/emacs-application-framework/blob/master/core/adblocker.css
