### ISSUE TITLE
MacOS: Python quit unexpectedly when opening PDF files

### ISSUE THREAD

**Issue by XushanLu** [emacs-eaf/emacs-application-framework#882]
**Describe the bug**
I often face the problem of "Python quit unexpectedly" when trying to open PDF files. It happens a lot when I was using Python 3.8 and now all the time when I updated to Python 3.9

**To Reproduce**
Directly open a PDF file in `Dired` mode or use `Spc a a f` (I am using Spacemacs with EAF layer) to open the PDF file.

**Expected behavior**
PDF file opens without any issue

**Versions (please complete the following info):**
 - Distro and DE/WM: Mac OS 12.0.1
 - Versions of Dependencies:
 - M-x emacs-version: GNU Emacs 27.2 (build 1, x86_64-apple-darwin18.7.0, Carbon Version 158 AppKit 1671.6) of 2021-03-27

**Error logs**
Traceback (most recent call last):
  File "/Users/xsl/.emacs.d/elpa/27.2/develop/eaf-20211020.1503/core/utils.py", line 60, in on_signal_received
    self._func(obj, *args, **kwargs)
  File "/Users/xsl/.emacs.d/elpa/27.2/develop/eaf-20211020.1503/eaf.py", line 170, in new_buffer
    self.create_buffer(buffer_id, url, module_path, arguments)
  File "/Users/xsl/.emacs.d/elpa/27.2/develop/eaf-20211020.1503/eaf.py", line 183, in create_buffer
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/xsl/.emacs.d/elpa/27.2/develop/eaf-20211020.1503/app/pdf-viewer/buffer.py", line 29, in <module>
    from core.utils import touch, interactive, eval_in_emacs, message_to_emacs, open_url_in_new_tab, translate_text, atomic_edit, get_emacs_var, get_emacs_vars, get_emacs_func_result, get_emacs_config_dir, get_emacs_theme_mode, get_emacs_theme_foreground, get_emacs_theme_background
ImportError: cannot import name 'get_emacs_theme_mode' from 'core.utils' (/Users/xsl/.emacs.d/elpa/27.2/develop/eaf-20211020.1503/core/utils.py)

Process *eaf* abort trap: 6

**Screenshots**
![image](https://user-images.githubusercontent.com/7824380/143468056-f803d0fc-23fe-4519-9989-38c188bd86a0.png)

**Comment by XushanLu** [comment]
Interesting, I don't find these functions at all in my utils.py file:

```Python
  
def get_emacs_theme_mode():
    return get_emacs_func_result("eaf-get-theme-mode", [])

def get_emacs_theme_background():
    return get_emacs_func_result("eaf-get-theme-background-color", [])

def get_emacs_theme_foreground():
    return get_emacs_func_result("eaf-get-theme-foreground-color", [])
       epc_client.call("eval-in-emacs", args)

```

**Comment by manateelazycat** [comment]
Please install EAF follow README, don't use EAF layer, it's not maintain by me, won't works.

**Comment by manateelazycat** [comment]
EAF not support tramp now
