### ISSUE TITLE
EAF Browser Can add some special mark in proxy mode ?

### ISSUE THREAD

**Issue by EdmondFrank** [emacs-eaf/emacs-application-framework#883]
During development, I need to occasionally access our company’s LAN service, and at the same time I need to use Google. 

At present, I started by setting up a proxy as default. When i need access the LAN environment i will disable the proxy by use `eaf-toggle-proxy`, and then turn on the proxy in same way to browse Google . 

After switching back and forth several times, I sometimes forget the proxy status of the current browser, 

I think Is it by adding a special mark to the ui when the proxy is turned on is better?

**Comment by manateelazycat** [comment]
@EdmondFrank Thanks for suggestion.

Current, EAF use Qt proxy API that effect whole process, not some url.

I have no idea that how to make proxy match url rule now.

PR are welcome if you know how to do.

**Comment by manateelazycat** [comment]
@EdmondFrank Best way is use some proxy software.

One proxy for customize rule, another proxy for connect network.

Welcome to add Wiki page. ;)

**Comment by manateelazycat** [comment]
Add Wiki https://github.com/emacs-eaf/emacs-application-framework/wiki/%E8%87%AA%E5%AE%9A%E4%B9%89%E8%A7%84%E5%88%99%E4%BB%A3%E7%90%86 

Thanks @EdmondFrank for solution. ;)
