### ISSUE TITLE
pdf-viewer crashes on trying to open files

### ISSUE THREAD

**Issue by dalanicolai** [emacs-eaf/emacs-application-framework#886]
**Describe the bug**
PDF viewer crashes when trying to open a PDF in pdf-reader (using `eaf-open`) 
The \*eaf\* buffer shows the following:

**To Reproduce**
- Update EAF
- Try to open a pdf

**Expected behavior**
File opens successfully

**Versions (please complete the following info):**
 - Distro and DE/WM: Fedora 35, Gnome 41.1 (error occurs on both Wayland and X11)
 - Versions of Dependencies: QT-version 5.15.2
 - M-x emacs-version: 27.2

**Error logs**
Qt: Session management error: Could not open network socket
Deprecation: 'pageCropBox' removed from class 'Document' after v1.19.0 - use 'page_cropbox'.
Deprecation: 'setCropBox' removed from class 'Page' after v1.19.0 - use 'set_cropbox'.
Deprecation: 'getImageList' removed from class 'Page' after v1.19.0 - use 'get_images'.
Traceback (most recent call last):
  File "/home/dalanicolai/spacemacs/elpa/27.2/develop/eaf-20211201.312/app/pdf-viewer/buffer.py", line 1089, in paintEvent
    rect = QRect(render_x, render_y, render_width, render_height)
TypeError: arguments did not match any overloaded call:
  QRect(): too many arguments
  QRect(int, int, int, int): argument 1 has unexpected type 'float'
  QRect(QPoint, QPoint): argument 1 has unexpected type 'float'
  QRect(QPoint, QSize): argument 1 has unexpected type 'float'
  QRect(QRect): argument 1 has unexpected type 'float'
QBackingStore::endPaint() called with active painter; did you forget to destroy it or call QPainter::end() on it?
QPainter::end: Painter ended with 2 saved states
Traceback (most recent call last):
  File "/home/dalanicolai/spacemacs/elpa/27.2/develop/eaf-20211201.312/app/pdf-viewer/buffer.py", line 1089, in paintEvent
    rect = QRect(render_x, render_y, render_width, render_height)
TypeError: arguments did not match any overloaded call:
  QRect(): too many arguments
  QRect(int, int, int, int): argument 1 has unexpected type 'float'
  QRect(QPoint, QPoint): argument 1 has unexpected type 'float'
  QRect(QPoint, QSize): argument 1 has unexpected type 'float'
  QRect(QRect): argument 1 has unexpected type 'float'

Process *eaf* aborted (core dumped)

**Additional context**
The `Qt: Session management error: Could not open network socket` can be suppressed by setting the `SESSION_MANAGER` environment variable to "" (using `M-x setenv`), but then another error is shown, namely `Qt: Session management error: networkIdsList argument is NULL`. However, I think these errors are not the culprit (just informing you about, in any case).

Also, the eaf-browser works just great as usual (so it is not a general eaf problem)

**Comment by manateelazycat** [comment]
Fix by https://github.com/emacs-eaf/eaf-pdf-viewer/commit/2a10aff54dd45d626344675a1d6d0e7943662fa3 thanks for report.
