### ISSUE TITLE
The eaf window position is abnormal in NixOS

### ISSUE THREAD

**Issue by wineee** [emacs-eaf/emacs-application-framework#887]
**Describe the bug**
The window of eaf separates from emacs [See Screenshots]

**To Reproduce**
Every eaf application can reproduce this bug

**Versions (please complete the following info):**
 - Distro: NixOS 22.05 (Quokka) x86_64
 - DE/WM: kde/kwin, none+xmonad
 - Versions of Dependencies:
My config about eaf:
```nix
let 
  my-python-packages = python3Packages: with python3Packages; [
      # for eaf
      pyqt5 
      pyqtwebengine
      #qtconsole
      sip qrcode
      epc
      retry

      # eaf-filemanger
      lxml

      # eaf-system-monitor
      psutil
  ]; 
  python-with-my-packages = python3.withPackages my-python-packages;
in
[
    environment.systemPackages = with pkgs; [
        git nodejs wmctrl aria xdotool
        python-with-my-packages
    ];

]
```
python 3.9
PyQt5-5.15.4
PyQt5_sip-12.9.0
epc-0.0.5
wmctrl-1.07

 - M-x emacs-version: 29.0.50 (Doom Emacs 21.12.0)

**Error logs**
Please check the `*eaf*` buffer, if there is any error in it, paste it here.

Qt: Session management error: Could not open network socket
> disappear after executing the code "export -n SESSION_MANAGER"

qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 415, resource id: 36053648, major code: 7 (ReparentWindow), minor code: 0
![b](https://user-images.githubusercontent.com/22803888/144443111-18f2830a-472e-454e-baf7-884ae411177e.png)

**Screenshots**
KDE:
eaf-open-demo
![a](https://user-images.githubusercontent.com/22803888/144443170-3d3dfd1f-1ee5-4212-9b49-cfd5f00904b7.png)
eaf-open-system-monitor
![c](https://user-images.githubusercontent.com/22803888/144443199-fe166c50-aa92-46bd-bb11-f76fbfd51e5b.png)

The size of window is correct.

---
XMonad:
![2021-10-07-161254_1920x1080_scrot](https://user-images.githubusercontent.com/22803888/144448132-a355a0c2-9631-4761-9d60-d38ccbec5ddd.png)

**Additional context**
popweb seems to be working fine，maybe since it's "pop"
![image](https://user-images.githubusercontent.com/22803888/144439397-dee73a03-d57c-4d79-9c9f-a6301672af66.png)

**Comment by wineee** [comment]
> EAF just works with X11 or XWayland, can not work with native Wayland.

I didn't use Wayland，it‘s X11

**Comment by manateelazycat** [comment]
> > EAF just works with X11 or XWayland, can not work with native Wayland.
> 
> I didn't use Wayland，it‘s X11

Looks your WM not support XReparent somehow, I believe KDE and Gnome3 works with Arch, please check NixOS package.

I don't use Nix, can't help you, sorry.

**Comment by wineee** [comment]
It seems to be a problem with environment variables in NixOS.

I remove `qt5Full`  from `environment.systemPackages`, and set ` environment.variables = { QT_QPA_PLATFORM_PLUGIN_PATH = "${pkgs.qt5.qtbase.bin.outPath}/lib/qt-${pkgs.qt5.qtbase.version}/plugins";};`

eaf looks working fine now.

**Comment by manateelazycat** [comment]
> It seems to be a problem with environment variables in NixOS.
> 
> I remove `qt5Full` from `environment.systemPackages`, and set ` environment.variables = { QT_QPA_PLATFORM_PLUGIN_PATH = "${pkgs.qt5.qtbase.bin.outPath}/lib/qt-${pkgs.qt5.qtbase.version}/plugins";};`
> 
> eaf looks working fine now.

Can you write those in Wiki page? Wiki page is public, anyone can edit, thanks. ;)

**Comment by wineee** [comment]
> Can you write those in Wiki page? Wiki page is public, anyone can edit, thanks. ;)

Wiki page has been added. This is not the best method, but it works.
[Here are some related discussions](https://www.reddit.com/r/emacs/comments/m12r7v/emacs_application_framework_nixos/)

**Comment by manateelazycat** [comment]
thanks

**Comment by moritzschaefer** [comment]
@wineee sorry to hijacking the discussion. Is there a ressource somewhere that explains how to install eaf on a nixos system?

**Comment by manateelazycat** [comment]
> @wineee sorry to hijacking the discussion. Is there a ressource somewhere that explains how to install eaf on a nixos system?

https://github.com/emacs-eaf/emacs-application-framework/wiki/NixOS

**Comment by wineee** [comment]
> @wineee sorry to hijacking the discussion. Is there a ressource somewhere that explains how to install eaf on a nixos system?

If you need nix wrapper, [here](https://gist.github.com/adisbladis/c605d40c3e06f4c4af4bed94233c4d1e) is a unfinished work.
And eaf wiki describes how to install dependencies globally

**Comment by moritzschaefer** [comment]
It runs now, but I face the same problem as you (with EXWM, I'll check KDE later)

**Comment by wineee** [comment]
> It runs now, but I face the same problem as you (the PDF does not show within the window, using EXWM, I'll check KDE later)

- Did you install `qt5Full`?
- Maybe you need `export -n SESSION_MANAGER`

I'm not sure what exactly I did that solved the problem，I use Emacs 27.2 and NixOS 22.05

**Comment by moritzschaefer** [comment]
No luck with qt5Full installation..
The variable "SESSION_MANAGER" is not defined in my shell. what does it reflect and where do you run the export command?

**Comment by wineee** [comment]
> No luck with qt5Full installation.

（Probably because）The Qt version used by pyqt in Nixpkgs is not guaranteed to be strictly consistent with qt5Full， install qt5Full  will set unreliable environment variables for pyqt. I recommend only use qt5Full in `shell.nix` or `nix-shell -p qt5Full`, do not install globally 

```nix
   environment.variables = {
     QT_QPA_PLATFORM_PLUGIN_PATH = "${pkgs.qt5.qtbase.bin.outPath}/lib/qt-${pkgs.qt5.qtbase.version}/plugins";
   };
```

> The variable "SESSION_MANAGER" is not defined 
This is the correct state.

I get `Qt: Session management error: Could not open network socket` in *eaf* buffer，it disappear after executing the code "export -n SESSION_MANAGER"，but this happened many months ago.

**Comment by moritzschaefer** [comment]
@wineee thanks for explaining. 

Variables and package versions seem to be set correctly in my case:

```
[ins] In [13]: from PyQt5 import QtCore

[ins] In [14]: print(QtCore.qVersion())
5.15.3
```

```
[I] moritz@moxps ~> echo $QT_QPA_PLATFORM_PLUGIN_PATH
/nix/store/2mg3i2xxvm1jyxjrx89m7syf2w7nhmbp-qtbase-5.15.3-bin/lib/qt-5.15.3/plugins

```

Also I was wondering how pyqt5 should be able to gain "access" to qt5full if it's installed within a separate nix environment?

**Comment by wineee** [comment]
I used to use [emacs-overlay](https://github.com/nix-community/emacs-overlay)，because of the incompatibility of doom, I switched back to the nixpkgs version.

AAccording to https://github.com/emacs-eaf/emacs-application-framework/issues/927 ，maybe pgtk is the real cause

**Comment by wineee** [comment]
This is a sad story，QT6 on NixOS still not merged，and EAF dropped compatibility with QT5

**Comment by manateelazycat** [comment]
> This is a sad story，QT6 on NixOS still not merged，and EAF dropped compatibility with QT5

@MatthewZMD Will build Qt5 branch recently.

**Comment by MatthewZMD** [comment]
@wineee I've created this `qt5-legacy` branch, please switch to that branch and re-run `install-eaf.py`. Please use this branch until you can switch to Qt6. I'll try my best to maintain this branch until everyone moves on to Qt6.

**Comment by wineee** [comment]
> @wineee I've created this `qt5-legacy` branch, please switch to that branch and re-run `install-eaf.py`. Please use this branch until you can switch to Qt6. I'll try my best to maintain this branch until everyone moves on to Qt6.

That is good news，I think qt5 will not be eliminated in a short time. It would be nice to have a qt5-compatible branch
