### ISSUE TITLE
Install error on MacOS 

### ISSUE THREAD

**Issue by sutzig** [emacs-eaf/emacs-application-framework#888]
Running into an error trying to execute the `./install-eaf.py` step.

**Describe the bug**
When executing `./install-eaf.py` from the terminal, the build fails with the following error: FileNotFoundError: [Errno 2] No such file or directory: 'pip'. The same error occurs when executing  `M-x eaf-install-and-update`  from the Emacs GUI and when launching Emacs from the Terminal and trying to execute `eaf-install-and-update` from the terminal

**To Reproduce**
cd emacs-application-framework
chmod +x ./install-eaf.py
./install-eaf.py

**Versions (please complete the following info):**
 - Distro and DE/WM: N/A
 - Versions of Dependencies: N/A
 - M-x emacs-version:
    - GNU Emacs 27.2 (build 1, x86_64-apple-darwin18.7.0)
 - MacOS: Monterey 12.0.1
 - Python: 3.9.9

**Error logs**
[EAF] ------------------------------------------
[EAF] Installing core dependencies
[EAF] Running pip install --user epc pyqt5 pyqt5-sip pyqtwebengine mac-app-frontmost @ /Users/steveutzig/.emacs.d/site-lisp/emacs-application-framework
Traceback (most recent call last):
  File "/Users/steveutzig/.emacs.d/site-lisp/emacs-application-framework/./install-eaf.py", line 386, in <module>
    main()
  File "/Users/steveutzig/.emacs.d/site-lisp/emacs-application-framework/./install-eaf.py", line 371, in main
    install_core_deps(distro, deps_dict)
  File "/Users/steveutzig/.emacs.d/site-lisp/emacs-application-framework/./install-eaf.py", line 228, in install_core_deps
    install_py_deps(deps_dict["pip"][sys.platform])
  File "/Users/steveutzig/.emacs.d/site-lisp/emacs-application-framework/./install-eaf.py", line 123, in install_py_deps
    return run_command(command)
  File "/Users/steveutzig/.emacs.d/site-lisp/emacs-application-framework/./install-eaf.py", line 85, in run_command
    process = subprocess.Popen(command, env = english_env, stdin = subprocess.PIPE,
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'pip'

**Screenshots**

**Additional context**

**Comment by manateelazycat** [comment]
Please install ```pip``` first in your macOS, then try ./install-eaf.py agian, thanks! ;)

**Comment by sutzig** [comment]
Thank you for your immediate response! I'm not a python user and understood pip was installed with python. I've download pip and, not surprisingly, the process is firing away.

**Comment by manateelazycat** [comment]
> 

Problem resolve now? ;)

**Comment by sutzig** [comment]
Unfortunately, no. When I try to open a file nothing happens. 

I evaluated the lines 
(add-to-list 'load-path "~/.emacs.d/site-lisp/emacs-application-framework/")
(require 'eaf)
(require 'eaf-pdf-viewer)

No error is presented. But when browsing to and selecting a PDF file, nothing happens,. The mini buffer reads, [EAF/pdf-view] Opening file name, but no file open and no error message is offered.

**Comment by manateelazycat** [comment]
What is output of ```*eaf*``` buffer ?

**Comment by sutzig** [comment]
There is no `eaf` buffer. Literally, nothing happens.

**Comment by manateelazycat** [comment]
./install-eaf.py no error? Looks you not need PyQt5 correctly.

**Comment by sutzig** [comment]
I understood from your readme that all the dependencies were installed with your python script. Is that not the case?
