### ISSUE TITLE
Installing EAF fails with npm version 8.3.0 due to `xterm-addon-web-links` returning 404 from the npm registry

### ISSUE THREAD

**Issue by roygbyte** [emacs-eaf/emacs-application-framework#893]
**Describe the bug**
Installing EAF fails with npm version 8.3.0 due to `xterm-addon-web-links` returning 404 from the npm registry. However, this can be resolved (although I'm not sure with what consequences) by changing the dependency version listed in `app/terminal/package.json` to `npm:null@*`. E.g.:

``` js
"dependencies" : {
   ...
   "xterm-addon-web-links": "npm:null@*"
   ...
}
``` 

**To Reproduce**
```
# After downloading repo and adjusting permissions, run:
./install-eaf.py
```

**Expected behavior**
Expectation is that npm dependencies install and EAF can be launched from Emacs.

**Versions (please complete the following info):**
 - Distro and DE/WM: Not sure
 - Versions of Dependencies: Not sure
 - M-x emacs-version: 26.3

**Error logs**
```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for xterm@^0.4.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/scarlett/.npm/_logs/2021-12-15T16_05_18_744Z-debug-0.log
```

**Screenshots**
N/A

**Additional context**
The xterm project indicates that addons have been moved to the main repo. Maybe this is affecting the availability of [xterm-addon-web-links](https://github.com/xtermjs/xterm-addon-web-links)?

**Comment by manateelazycat** [comment]
Yes, looks xterm developer move addon to main repo.
@roygbyte Can you help us commit a patch to fix this issue ? Thanks.

**Comment by roygbyte** [comment]
Tried again today and the installer works without error. Also checked with the docs of `xterm` and it does look like you have the addons properly added.
