### ISSUE TITLE
EAF-browser cannot click some buttons

### ISSUE THREAD

**Issue by daehwannam** [emacs-eaf/emacs-application-framework#896]
**Describe the bug**
My EAF-browser cannot click buttons of "Accept all cookies" and "Customize settings" in https://stackoverflow.com/
Neither mouse clicking nor `open_link` (`M-s`) is working.

**To Reproduce**
1. install EAF of branch 1896ee34f554424cc85a1b85b1e9880b04503e37
2. M-x eaf-open-browser https://stackoverflow.com/
3. Click the button "Accept all cookies" (or "Customize settings") at the left bottom corner

**Expected behavior**
Clicking "Accept all cookies" doesn't work and changes nothing.

**Versions (please complete the following info):**
 - Distro and DE/WM: Ubuntu 20.04.3 LTS / GNOME Shell
 - Versions of Dependencies: EAF of branch 1896ee34f554424cc85a1b85b1e9880b04503e37
 - M-x emacs-version: GNU Emacs 27.2 (build 1, x86_64-conda-linux-gnu, GTK+ Version 3.24.29, cairo version 1.16.0) of 2021-10-06

**Error logs**
Below is the log after I run "M-x eaf-open-browser https://stackoverflow.com/"
```
Uncaught ReferenceError: globalThis is not defined
Uncaught TypeError: StackExchange.ready is not a function
Uncaught TypeError: StackExchange.ready is not a function
Uncaught TypeError: StackExchange.init is not a function
Uncaught TypeError: Cannot read property 'setCacheBreakers' of undefined
Uncaught TypeError: StackExchange.ready is not a function
Uncaught TypeError: StackExchange.ready is not a function
Uncaught TypeError: StackExchange.ready is not a function
[EAF] Browser https://stackoverflow.com/ loading time: 4.591040134429932s
[EAF] Browser https://stackoverflow.com/ loading time: 5.007278680801392s
```

**Screenshots**
![Screenshot 2021-12-21 07:06:49](https://user-images.githubusercontent.com/35688291/146840709-15de196a-5aef-42c4-8cfb-0c3fb6a1e9e2.png)

**Comment by MatthewZMD** [comment]
> Neither mouse clicking nor `open_link` (`M-s`) is working.

Does a link tag show up near the button?

**Comment by daehwannam** [comment]
Yes, tags are properly attached, but nothing happens when choosing tags.

- before choosing a tag
![Screenshot 2021-12-21 12:09:20](https://user-images.githubusercontent.com/35688291/146864560-f8ad1b56-2677-435b-b1a0-def99c640add.png)

- after choosing a tag ("W" is chosen)
![Screenshot 2021-12-21 12:11:36](https://user-images.githubusercontent.com/35688291/146864901-b24fb773-a609-488f-8581-78b52276b901.png)

-

**Comment by manateelazycat** [comment]
@daehwannam I have test your problem, haven't this issue.
