### ISSUE TITLE
Adding tip for virtual/conda envirments to README.md or Wiki

### ISSUE THREAD

**Issue by daehwannam** [emacs-eaf/emacs-application-framework#897]
**Is your feature request related to a problem? Please describe.**
I'm using conda envirments (with Miniconda), and tried to setup EAF by following [README.md](https://github.com/emacs-eaf/emacs-application-framework/blob/master/README.md) and [Wiki](https://github.com/emacs-eaf/emacs-application-framework/wiki/Python-Virtual-Environment).
However, I couldn't install EAF with these guidelines.
Running install-eaf.py installed packages for /usr/bin/python3 then my conda environment couldn't work for EAF.

**Describe the solution you'd like**
I fixed the problem by adding `(setq eaf-python-command "/usr/bin/python3")` in my emacs config, then EAF interacted with /usr/bin/python3 instead of python in a conda environment.
I think that adding this or similar information to guidelines would help newcomers like me.

**Comment by manateelazycat** [comment]
wiki is public,anyone can edit ;)
