### ISSUE TITLE
Would it be possible to open EAF buffers via pop-to-buffer with its window restore functionality?

### ISSUE THREAD

**Issue by Gira-X** [emacs-eaf/emacs-application-framework#900]
I tried to use the code below, but it does not work. It just opens the EAF buffers in the same window (at least when there are 2 splits) and behaves incorrectly when there is only a single window.

```emacs-lisp
(defun eaf--preview-display-buffer (app-name buffer)
  "Display specified APP-NAME's app buffer in BUFFER."
  (pop-to-buffer buffer))
```

`eaf-open-browser-other-window` does not work for me as a following call to `(quit-window t)` in the EAF buffer does not restore the initial buffer/window config as one would expect.

**Comment by manateelazycat** [comment]
I don't understand your application scenario, what problems did you want to solve?

**Comment by Gira-X** [comment]
Let me demonstrate with how `describe-function` behaves which uses `pop-to-buffer`:

Here starting with a single window:

https://user-images.githubusercontent.com/15002298/147057104-96e784fd-f8de-421a-8a59-c43974c57b03.mov

And here starting with 2 windows:




https://user-images.githubusercontent.com/15002298/147057132-002b9bbd-5379-4b8c-acc8-d26f379169ca.mov

---

`pop-to-buffer` restores the previous window configuration nicely, so I wondered if it could be used with EAF buffers as well.

My use-case is a bit similar to how https://github.com/manateelazycat/popweb behaves, just that I want a full-fledged buffer for interacting with the buffer.

**Comment by Gira-X** [comment]
Hold on, I think the `eaf--preview-display-buffer` in the issue description actually works as advertised. So closing this. Sorry for the noise!
