### ISSUE TITLE
Sometimes, emacs   locks up when eaf-open is launched

### ISSUE THREAD

**Issue by tvraman** [emacs-eaf/emacs-application-framework#904]
Happens about 50% of the time for me. Only remedy seems to be to kill the eaf process when this happens

**Comment by MatthewZMD** [comment]
I've never encounter this problem. What is your configuration? does it happen immediately or after some time of use? What is the CPU/memory usage when it happens?

**Comment by manateelazycat** [comment]
EAF browser will hang-on (Emacs can response) when the network signal is very poor, I haven't figure out which code is wrong, thank you feedback.

**Comment by tvraman** [comment]
Matthew Zeng ***@***.***> writes:


If it blocks it happens the first time I use eaf in an emacs session,
sometimes subsequently as well.

No CPU load, the emacs window is just frozen until I go to a different
xterm and nuke the eaf process.

I dont know how to answer the "what is my configuration" question in
this context;  the error happens on something as simple as eaf-open on a
youtube link

> I've never encounter this problem. What is your configuration? does it
> happen immediately or after some time of use? What is the CPU/memory
> usage when it happens?
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android. 
> You are receiving this because you authored the thread.
>

-- 

Thanks,

--Raman(I Search, I Find, I Misplace, I Research)
♈ Id: kg:/m/0285kf1  🦮

**Comment by tvraman** [comment]
no, this is not a networking issue --

-- 

Thanks,

--Raman(I Search, I Find, I Misplace, I Research)
♈ Id: kg:/m/0285kf1  🦮

**Comment by manateelazycat** [comment]
Can you get content of eaf buffer?

**Comment by manateelazycat** [comment]
> 

xterm? Did you use EAF with terminal emulator?

**Comment by tvraman** [comment]
No

because emacs was hung, I created a separate xterm from where I killed
the EAF process.

-- 

Thanks,

--Raman(I Search, I Find, I Misplace, I Research)
♈ Id: kg:/m/0285kf1  🦮

**Comment by manateelazycat** [comment]
> No because emacs was hung, I created a separate xterm from where I killed the EAF process.
> […](#)
> -- Thanks,
> --Raman(I Search, I Find, I Misplace, I Research) ♈ Id: kg:/m/0285kf1 🦮

I suggest you use strace to track which API emacs hung on

**Comment by manateelazycat** [comment]
You can try ```emacs -Q``` with EAF, exclude your config file from being affected

**Comment by tvraman** [comment]
Andy Stewart ***@***.***> writes:

Doesn't appear to make a difference

> You can try emacs -Q with EAF, exclude your config file from being
> affected
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android. 
> You are receiving this because you authored the thread.
>

-- 

Thanks,

--Raman(I Search, I Find, I Misplace, I Research)
♈ Id: kg:/m/0285kf1  🦮

**Comment by MatthewZMD** [comment]
I'd suggest using `strace` to diagnose the system calls when Emacs is locked up and report back to us. At this point, we cannot reproduce your issue and don't know how to help.

**Comment by manateelazycat** [comment]
@tvraman Sorry, we can't reproduce this issue, please re-open this issue if you have any clue.
