### ISSUE TITLE
Using Mathlive as a latex equation editor

### ISSUE THREAD

**Issue by fbob** [emacs-eaf/emacs-application-framework#906]
I've asked this on popweb github repository and it looks like this feature request is more targeted to EAF (https://github.com/manateelazycat/popweb/issues/23)

I'm wondering if EAF features could be used in conjunction with Mathlive to build the best latex equation editor inside Emacs.
Matlive is indeed an excellent web component for math input: https://github.com/arnog/mathlive 

**Describe the solution you'd like**
Start a server listening on local port. 
Send the latex text to the server, which will open a mathlive window in where one can edit math equations. 
When the matlive window is closed or a particular keychord is send the modified content is printed to standard output or replace the selected one.

**Describe alternatives you've considered**
https://github.com/casouri/quick-mathlive may be a good starting point here.

**Additional context**
Gif from https://github.com/casouri/quick-mathlive
![quick-mathlive](https://user-images.githubusercontent.com/8211124/147599594-e674d8f0-4347-4d4f-97d2-e1ed1d883088.gif)

**Comment by manateelazycat** [comment]
It's easy to do in EAF, just need use mathlive create new EAF app.

I haven't time works on this, but it's really easy to develop this feature.

**Comment by manateelazycat** [comment]
Sorry, It looks like popweb is better solution.
