### ISSUE TITLE
[EAF] Unsupported Linux distribution/package manager.

### ISSUE THREAD

**Issue by wereket** [emacs-eaf/emacs-application-framework#913]
Hello, I am using Voidlinux 
I have installed all the dependencies
I get
[EAF] Unsupported Linux distribution/package manager.
 Please see dependencies.json for list of dependencies.

Thank you for your time

**Comment by MatthewZMD** [comment]
> I have installed all the dependencies

If you see this error, that means you *didn't* install all the dependencies, at least through our provided install script.

What install manager does voidlinux use?

**Comment by wineee** [comment]
Did you add `ignore-sys-deps` argument
```bash
./install-eaf.py --ignore-sys-deps
```

**Comment by wereket** [comment]
Thank you, --ignore-sys-deps solved the issue

**Comment by wereket** [comment]
./install-eaf.py --ignore-sys-deps solved the issue
