### ISSUE TITLE
Python :can't  find libQt5QmlModels.so.5

### ISSUE THREAD

**Issue by e665107** [emacs-eaf/emacs-application-framework#914]
Hi
Now I have get stuck in the python environment set up. If i want to use the eaf,  the version of python i need to use is which one. And I can't solve the problem 
below:
Traceback (most recent call last):
  File "/home/e66/.emacs.d/lisp/emacs-application-framework/eaf.py", line 25, in <module>
    from PyQt5 import QtWebEngineWidgets as NeverUsed # noqa
ImportError: libQt5QmlModels.so.5: cannot open shared object file: No such file or directory

**Comment by MatthewZMD** [comment]
If you can't uograde your python to greater than 3.7, you cant run the install script successfully, so non of these dependencies are installed.

Second, you shouldn't need to create a new issue, just use the last one you created.

**Comment by MatthewZMD** [comment]
我是说的不够清楚吗，更新python重新跑一边install-eaf.py，你不成功运行install-eaf.py就没安装好依赖，EAF怎么可能成功运行，有那么难吗？

**Comment by e665107** [comment]
你好，我现在的python版本已经升级到了3.8.6：
e66@ubuntu:~/git_work/linux_kernel_drv_prj/hrtimer$ python3 --version
Python 3.8.6
e66@ubuntu:~/git_work/linux_kernel_drv_prj/hrtimer$ 
同时也按照网上的教程安装了python依赖库，但是当我执行eaf-open-browser的时候，还是有问题，我用的是ubuntu16.04,可能我们用的发型版不太一样吧，我去网上找过这个错误的解决办法，但是，都没有给出明确的解决办法，现在想将python升级到3.9试试，不知道能不能解决

**Comment by MatthewZMD** [comment]
不用升3.9，只要大于3.7，你上次po的install-eaf.py的log的错误就不会有了。你现在再跑一次install-eaf.py，然后把log发来看看

**Comment by e665107** [comment]
新的日志，install-eaf.py这个过了，但是执行eaf-open-browser会报标题的提示！
e66@ubuntu:~/.emacs.d/lisp/emacs-application-framework$ ./install-eaf.py 
[EAF] ------------------------------------------
[EAF] Installing core dependencies
[EAF] Running sudo apt -y install python3-pyqt5.qtwebengine wmctrl libglib2.0-dev python3-pyqt5 python3-sip python3-pygit2 @ /home/e66/.emacs.d/lisp/emacs-application-framework
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python3-pygit2 is already the newest version (0.26.2-2).
python3-pyqt5 is already the newest version (5.10.1+dfsg-1ubuntu2).
python3-pyqt5.qtwebengine is already the newest version (5.10.1+dfsg-1ubuntu2).
wmctrl is already the newest version (1.07-7build1).
python3-sip is already the newest version (4.19.7+dfsg-1ubuntu0.1).
libglib2.0-dev is already the newest version (2.56.4-0ubuntu0.18.04.9).
0 upgraded, 0 newly installed, 0 to remove and 636 not upgraded.
[EAF] Running pip install --user epc lxml @ /home/e66/.emacs.d/lisp/emacs-application-framework
Requirement already satisfied: epc in /home/e66/.local/lib/python3.8/site-packages (0.0.5)
Requirement already satisfied: lxml in /home/e66/.local/lib/python3.8/site-packages (4.7.1)
Requirement already satisfied: sexpdata>=0.0.3 in /home/e66/.local/lib/python3.8/site-packages (from epc) (0.0.3)
[EAF] Finished installing core dependencies
[EAF] ------------------------------------------
[EAF] ------------------------------------------
[EAF] Installing application dependencies
[EAF] Updating airshare to newest version...
[EAF] Running git pull @ app/airshare
Already up to date.
[EAF] Updating browser to newest version...
[EAF] Running git pull @ app/browser
Already up to date.

[EAF] Installing dependencies for installed applications
[EAF] Finished installing applications and their dependencies
[EAF] Please ensure the following are added to your init.el:
(require 'eaf-airshare)
(require 'eaf-browser)
[EAF] Please run both 'git pull' and 'install-eaf.py' (M-x eaf-install-and-update) to update EAF, applications and their dependencies.
[EAF] Use the flag '--install-new-apps' to install previously uninstalled or new apps.
[EAF] ------------------------------------------
[EAF] install-eaf.py finished.
e66@ubuntu:~/.emacs.d/lisp/emacs-application-framework$

**Comment by MatthewZMD** [comment]
> 但是执行eaf-open-browser会报标题的提示！

Ok，现在麻烦发一下这个报错的log

**Comment by e665107** [comment]
下面就是：
Process *eaf* exited abnormally with code 1
Traceback (most recent call last):
  File "/home/e66/.emacs.d/lisp/emacs-application-framework/eaf.py", line 25, in <module>
    from PyQt5 import QtWebEngineWidgets as NeverUsed # noqa
ImportError: libQt5QmlModels.so.5: cannot open shared object file: No such file or directory

Process *eaf* exited abnormally with code 1

**Comment by MatthewZMD** [comment]
依赖还是有点问题。你可以自己尝试一下跑apt或者网上搜一下吧。我用的Manjaro，帮不到你的忙。

**Comment by manateelazycat** [comment]
> 你好，我现在的python版本已经升级到了3.8.6： e66@ubuntu:~/git_work/linux_kernel_drv_prj/hrtimer$ python3 --version Python 3.8.6 e66@ubuntu:~/git_work/linux_kernel_drv_prj/hrtimer$ 同时也按照网上的教程安装了python依赖库，但是当我执行eaf-open-browser的时候，还是有问题，我用的是ubuntu16.04,可能我们用的发型版不太一样吧，我去网上找过这个错误的解决办法，但是，都没有给出明确的解决办法，现在想将python升级到3.9试试，不知道能不能解决

ubuntu版本升级一下吧，这个最简单

**Comment by e665107** [comment]
我看到gitee上也有clone版本，如果能支持从gitee更新组件就好了，国内的github太慢了，现在好像不能将包直接下载放到指定位置自动查找，如果这样做的话，我发现执行./install-eaf.py后会报错

**Comment by e665107** [comment]
有没有Ubuntu用户，你知道的，我现在已经用Ubuntu20.04了，还是不行，报其他的错误
Traceback (most recent call last):
  File "/home/e665106/.emacs.d/lisp/emacs-application-framework/core/utils.py", line 61, in on_signal_received
    self._func(obj, *args, **kwargs)
  File "/home/e665106/.emacs.d/lisp/emacs-application-framework/eaf.py", line 158, in new_buffer
    self.create_buffer(buffer_id, url, module_path, arguments)
  File "/home/e665106/.emacs.d/lisp/emacs-application-framework/eaf.py", line 175, in create_buffer
    app_buffer = module.AppBuffer(buffer_id, url, arguments)
  File "/home/e665106/.emacs.d/lisp/emacs-application-framework/app/browser/buffer.py", line 79, in __init__
    self.buffer_widget.dark_mode_js = open(os.path.join(os.path.dirname(__file__),
FileNotFoundError: [Errno 2] No such file or directory: '/home/e665106/.emacs.d/lisp/emacs-application-framework/app/browser/node_modules/darkreader/darkreader.js'

**Comment by MatthewZMD** [comment]
> 你不成功运行install-eaf.py就没安装好依赖，EAF怎么可能成功运行，有那么难吗？

**Comment by manateelazycat** [comment]
> 我看到gitee上也有clone版本，如果能支持从gitee更新组件就好了，国内的github太慢了，现在好像不能将包直接下载放到指定位置自动查找，如果这样做的话，我发现执行./install-eaf.py后会报错

有 --use-gitee 选项

**Comment by e665107** [comment]
嗯，使用--use-gitee快了很多，但是又报了如下的log
Preparing metadata (setup.py) ... done
     Building wheels for collected packages: retrying, pytaglib, sgmllib3k
     Building wheel for retrying (setup.py) ... done
     Created wheel for retrying: filename=retrying-1.3.3-py3-none-any.whl size=11447 sha256=f7a8df359956c3ce487e701f425581be27a3285c8b5eee678dbbcf6fc9f56319
     Stored in directory: /home/e665106/.cache/pip/wheels/c4/a7/48/0a434133f6d56e878ca511c0e6c38326907c0792f67b476e56
     Building wheel for pytaglib (setup.py) ... error
     ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-1t16p2zq/pytaglib_da602a5df95c4946ade1e7c60fe93b92/setup.py'"'"'; __file__='"'"'/tmp/pip-install-1t16p2zq/pytaglib_da602a5df95c4946ade1e7c60fe93b92/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-29z1t9nw
     cwd: /tmp/pip-install-1t16p2zq/pytaglib_da602a5df95c4946ade1e7c60fe93b92/
     Complete output (17 lines):
     running bdist_wheel
     running build
     running build_py
     file src/pytaglib.py (for module pytaglib) not found
     creating build
     creating build/lib.linux-x86_64-3.8
     copying src/pyprinttags.py -> build/lib.linux-x86_64-3.8
     file src/pytaglib.py (for module pytaglib) not found
     running build_ext
     creating build/temp.linux-x86_64-3.8
     creating build/temp.linux-x86_64-3.8/src
     x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -I/usr/include/python3.8 -c src/taglib.cpp -o build/temp.linux-x86_64-3.8/src/taglib.o
     src/taglib.cpp:23:10: fatal error: Python.h: No such file or directory
     23 | #include "Python.h"
     |          ^~~~~~~~~~
     compilation terminated.
     error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
     ----------------------------------------
     ERROR: Failed building wheel for pytaglib
     Running setup.py clean for pytaglib
     Building wheel for sgmllib3k (setup.py) ... done
     Created wheel for sgmllib3k: filename=sgmllib3k-1.0.0-py3-none-any.whl size=6066 sha256=975ecdb5fd8cabd33a1a1ec72dcdb06266199a5e281931cb87829e9cd9f86aa1
     Stored in directory: /home/e665106/.cache/pip/wheels/83/63/2f/117884c3b19d46b64d3d61690333aa80c88dc14050e269c546
     Successfully built retrying sgmllib3k
     Failed to build pytaglib
     Installing collected packages: sgmllib3k, retrying, pytaglib, pysocks, pypinyin, pymupdf, feedparser
     Running setup.py install for pytaglib ... error
     ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-1t16p2zq/pytaglib_da602a5df95c4946ade1e7c60fe93b92/setup.py'"'"'; __file__='"'"'/tmp/pip-install-1t16p2zq/pytaglib_da602a5df95c4946ade1e7c60fe93b92/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-5y6rd53b/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/e665106/.local/include/python3.8/pytaglib
     cwd: /tmp/pip-install-1t16p2zq/pytaglib_da602a5df95c4946ade1e7c60fe93b92/
     Complete output (19 lines):
     running install
     /usr/local/lib/python3.8/dist-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
     warnings.warn(
     running build
     running build_py
     file src/pytaglib.py (for module pytaglib) not found
     creating build
     creating build/lib.linux-x86_64-3.8
     copying src/pyprinttags.py -> build/lib.linux-x86_64-3.8
     file src/pytaglib.py (for module pytaglib) not found
     running build_ext
     creating build/temp.linux-x86_64-3.8
     creating build/temp.linux-x86_64-3.8/src
     x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -I/usr/include/python3.8 -c src/taglib.cpp -o build/temp.linux-x86_64-3.8/src/taglib.o
     src/taglib.cpp:23:10: fatal error: Python.h: No such file or directory
     23 | #include "Python.h"
     |          ^~~~~~~~~~
     compilation terminated.
     error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
     ----------------------------------------
     ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-1t16p2zq/pytaglib_da602a5df95c4946ade1e7c60fe93b92/setup.py'"'"'; __file__='"'"'/tmp/pip-install-1t16p2zq/pytaglib_da602a5df95c4946ade1e7c60fe93b92/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-5y6rd53b/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/e665106/.local/include/python3.8/pytaglib Check the logs for full command output.

**Comment by e665107** [comment]
我用的全新的Ubuntu20.04做的测试

**Comment by e665107** [comment]
修复了 这个问题，现在ok了

**Comment by MatthewZMD** [comment]
能用了？

**Comment by e665107** [comment]
ubuntu20.04可以了，windows版本的要求是？还有windows下的emacs版本要求是？

**Comment by MatthewZMD** [comment]
既没有Windows版本的要求也没有Emacs版本的要求，最主要就是你电脑Python依赖没问题就行，在Linux上也是这个道理。

**Comment by e665107** [comment]
Ok

**Comment by e665107** [comment]
eaf file sender qrcode, 这个怎么扫二维码，有的时候扫不开啊，对文件格式有要求？目前在同网段内的

**Comment by e665107** [comment]
我虚拟机和win10一个网段，win10用猎豹免费wifi共享一个热点，然后连到我的手机上，然后用手机去扫虚拟机文件的码，扫不出来居然
