### ISSUE TITLE
Integration of emacs-application-framework with org-noter

### ISSUE THREAD

**Issue by Jdogzz** [emacs-eaf/emacs-application-framework#915]
Hi, I know that the [org-noter repository](https://github.com/weirdNox/org-noter) has been very quiet so I'm not expecting there to be any activity on the [direct issue](https://github.com/weirdNox/org-noter/issues/92). However, I have seen some interest from others in this repo (#521 and #532) by @fuxialexander to use the EAF PDF viewer in org-noter. Is this now possible? I have scanned through the [mentioned repo](https://github.com/fuxialexander/org-pdftools) but I'm not seeing any explicit mention of using the EAF PDF viewer with org-noter.

**Comment by manateelazycat** [comment]
https://github.com/emacs-eaf/emacs-application-framework/blob/master/extension/eaf-interleave.el is your need ? 

Sorry, I don't use org-mode too much.

**Comment by Jdogzz** [comment]
That will have to suffice for now since the original interleave is now officially unmaintained and org-noter seems to not be receiving any updates anymore, thank you for directing me to eaf-interleave. I may add in a wiki page soon since I had some trouble getting it up and running until I found the original pull request.

**Comment by Aneeqasif** [comment]
> https://github.com/emacs-eaf/emacs-application-framework/blob/master/extension/eaf-interleave.el is your need ?
> 
> Sorry, I don't use org-mode too much.

hi is it possible to use eaf with org noter ?
