### ISSUE TITLE
EAF not capturing keyboard events on Fluxbox

### ISSUE THREAD

**Issue by Jdogzz** [emacs-eaf/emacs-application-framework#916]
**Describe the bug**
I am unable to use keyboard short cuts, for example in the PDF reader, unless I first click in the minibuffer first. This appears to be a recurrence of #657 and #237 (where I initially had fixed this with Xpra). wmctrl -m outputs

```
Name: Fluxbox
Class: N/A
PID: N/A
Window manager's "showing the desktop" mode: N/A
```
I have added it to the eaf-wm-focus-fix-wms option:

```
'("i3" "LG3D" "Xpra" "EXWM" "Xfwm4" "Fluxbox")
```

The problem persists despite this addition.

**To Reproduce**
I have the latest git copy of EAF and open up a random PDF. I press random keyboard shortcuts, such as i for inverting the color.

**Expected behavior**
It would respond to keyboard shortcuts.

**Versions (please complete the following info):**
 - Distro and DE/WM: Turnkey Linux 16.1 and Fluxbox
 - Versions of Dependencies:
python3-pyqt5: 5.11.3+dfsg-1+b3
python3-dbus: 1.2.8-3
python3-pyqt5.qtwebengine: 5.11.3+dfsg-1+b3
 - M-x emacs-version: GNU Emacs 29.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.5, cairo version 1.16.0) of 2022-01-26

**Error logs**
Please check the `*eaf*` buffer, if there is any error in it, paste it here.

```
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-mymailuser'
Traceback (most recent call last):
  File "/home/mymailuser/emacs/emacs-application-framework/core/utils.py", line 61, in on_signal_received
    self._func(obj, *args, **kwargs)
  File "/home/mymailuser/emacs/emacs-application-framework/eaf.py", line 357, in eval_function
    buffer.eval_function(function_name)
  File "/home/mymailuser/emacs/emacs-application-framework/core/buffer.py", line 322, in eval_function
    getattr(self, function_name)()
  File "/home/mymailuser/emacs/emacs-application-framework/core/buffer.py", line 186, in move_cursor_to_corner
    QCursor().setPos(screen, screen.size().width(), screen.size().height())
TypeError: arguments did not match any overloaded call:
  setPos(int, int): argument 1 has unexpected type 'QScreen'
  setPos(QPoint): argument 1 has unexpected type 'QScreen'
```

**Screenshots**

**Additional context**

**Comment by manateelazycat** [comment]
I'm on vacation. I won't have time to read it for another half a month. Sorry.

**Comment by manateelazycat** [comment]
@Jdogzz I have push new patch https://github.com/emacs-eaf/emacs-application-framework/commit/28d001946bffeb58bf62b70328cd733593a1c8fb

Can you pull newest version and try again?

Thanks

**Comment by manateelazycat** [comment]
@Jdogzz Please re-open this issue if still have problem, thanks.

**Comment by Jdogzz** [comment]
@manateelazycat Thanks for taking a look at this. Not long after I submitted the original bug report I encountered an unusual GTK bug in the (older) version of fluxbox I had in my distro's repository, so I was forced to abandon fluxbox and replaced it with Xfce4, which had the same eaf cursor focus bug. But I believe your patch has corrected the issue and now all keyboard shortcuts respond correctly in Xfce4. Thank you very much!

**Comment by manateelazycat** [comment]
> @manateelazycat Thanks for taking a look at this. Not long after I submitted the original bug report I encountered an unusual GTK bug in the (older) version of fluxbox I had in my distro's repository, so I was forced to abandon fluxbox and replaced it with Xfce4, which had the same eaf cursor focus bug. But I believe your patch has corrected the issue and now all keyboard shortcuts respond correctly in Xfce4. Thank you very much!

Thanks for report, enjoy EAF. ;)
