### ISSUE TITLE
NixOS support

### ISSUE THREAD

**Issue by moritzschaefer** [emacs-eaf/emacs-application-framework#918]
**Is your feature request related to a problem? Please describe.**

EAF is not packaged within NixOS and is hard to be installed on NixOS

**Describe the solution you'd like**

- EAF (and its applications) could provide nix packaging files, which would facilitate incorporation into the nixpkgs repository

**Comment by manateelazycat** [comment]
https://github.com/emacs-eaf/emacs-application-framework/wiki/NixOS

**Comment by uselessabraincella** [comment]
THX !!!
