### ISSUE TITLE
Screen is floating on top

### ISSUE THREAD

**Issue by lazyskulptor** [emacs-eaf/emacs-application-framework#921]
**Describe the bug**
Even I chang the app from emacs to firefox, screen of eaf is floating on top of screen
<img width="917" alt="Screen Shot 2022-02-12 at 11 20 31 PM" src="https://user-images.githubusercontent.com/11717059/153715111-1afcb3dc-2728-4c01-83d1-4ebbbc423cb4.png">

**To Reproduce**
open browser or pdf and change the any app not emacs.

**Expected behavior**
it's hidden with emacs together.

**Versions (please complete the following info):**
 - Distro and DE/WM: MacOS Montery, Macbook pro 2015 mid.
 - Versions of Dependencies: 0.5;; Last-Updated: Sun Nov 21 03:38:17 2021 (-0500)
 - M-x emacs-version:
```
GNU Emacs 28.0.91 (build 1, x86_64-apple-darwin21.2.0, NS appkit-2113.20 Version 12.1 (Build 21C52)) of 2022-02-12
```
**Error logs**
There is none. That's all.
```
[EAF] Browser https://www.google.com/ loading time: 0.6032602787017822s
```

**Comment by manateelazycat** [comment]
Can you test (eaf-call-async "hide_top_views") ? EAF will hide after this command?

**Comment by manateelazycat** [comment]
> It hides then. And when I switch buffer it hides peroperly. <img alt="Screen Shot 2022-02-13 at 12 17 15 AM" width="744" src="https://user-images.githubusercontent.com/11717059/153717075-817ac4d3-127e-4615-9e4f-e1934dd07702.png">

Looks eaf--mac-unsafe-focus-out not running

**Comment by lazyskulptor** [comment]
> > It hides then. And when I switch buffer it hides peroperly. <img alt="Screen Shot 2022-02-13 at 12 17 15 AM" width="744" src="https://user-images.githubusercontent.com/11717059/153717075-817ac4d3-127e-4615-9e4f-e1934dd07702.png">
> 
> Looks eaf--mac-unsafe-focus-out not running expected, can you test eaf.el for your environment.

Okay, I'll try. When I meet difficuties, I'll ask help.  😀

**Comment by lazyskulptor** [comment]
@manateelazycat 
I put logging at function `eaf--mac-unsafe-focus-out` and I tried to check it's activated by switching buffer, focusing other window and finally chaing app with cmd+tab, mouse. But it's never activated. 
It there other way to check? I'm sorry, I'm not very familiar with Emacs, So please let me know things I need to check.

**Comment by manateelazycat** [comment]
@lhpfvs Can you help check this issue? I don't have MacOS for test. Thanks.

**Comment by manateelazycat** [comment]
> @manateelazycat I put logging at function `eaf--mac-unsafe-focus-out` and I tried to check it's activated by switching buffer, focusing other window and finally chaing app with cmd+tab, mouse. But it's never activated. It there other way to check? I'm sorry, I'm not very familiar with Emacs, So please let me know things I need to check.

When EAF window not hidden expected, what's the result of command ```app-frontmost --name``` ?

**Comment by lazyskulptor** [comment]
> `app-frontmost --name`

Sorry, I can't find command `app-frontmost --name` from emacs and terminal. 
Did I omit any dependencies?

**Comment by lhpfvs** [comment]
mac-app-frontmost is a mandatory dependency. I guess installing it correctly solves the problem.
https://pypi.org/project/mac-app-frontmost/

**Comment by manateelazycat** [comment]
> > `app-frontmost --name`
> 
> Sorry, I can't find command `app-frontmost --name` from emacs and terminal. Did I omit any dependencies?

We have add dependency ```map-app-frontmost``` in file emacs-application-framework/dependencies.json,
```map-app-frontmost``` not install when you run script ```install-eaf.py``` ?

**Comment by manateelazycat** [comment]
> > `app-frontmost --name`
> 
> Sorry, I can't find command `app-frontmost --name` from emacs and terminal. Did I omit any dependencies?

I have push commit https://github.com/emacs-eaf/emacs-application-framework/commit/44a207e07381feaab698a4a4dff2975617b44578 to check app-frontmost is exist.

Please install app-frontmost and test again, thanks. ;)

**Comment by MatthewZMD** [comment]
> I have push commit [44a207e](https://github.com/emacs-eaf/emacs-application-framework/commit/44a207e07381feaab698a4a4dff2975617b44578) to check app-frontmost is exist.

app-frontmost should be installed if the user uses our install script... Did it fail for OP?

**Comment by manateelazycat** [comment]
> > I have push commit [44a207e](https://github.com/emacs-eaf/emacs-application-framework/commit/44a207e07381feaab698a4a4dff2975617b44578) to check app-frontmost is exist.
> 
> app-frontmost should be installed if the user uses our install script... Did it fail for OP?

I haven't macOS, don't know install script is ok.

**Comment by lazyskulptor** [comment]
@lhpfvs,  @manateelazycat 
Thank you. I think it works now. when it's in behind other app browser screen is completely hidden. 
Do you think does it work as it does at Linux?
<img width="438" alt="Screen Shot 2022-02-14 at 10 16 54 PM" src="https://user-images.githubusercontent.com/11717059/153871856-383f6136-819c-42e0-af66-6e17e52856f3.png">


@manateelazycat 
I tried to install `mac-app-frontmost` manually with pip but it keeps failing. So I donwloaded compressed file and install with script in homepage.

I think app-frontmost is written in your commit, but it kept failing without log in my PC. 

Thanks again.
