### ISSUE TITLE
EAF apps open in a new window, instead of a buffer (Arch Linux + KDE)

### ISSUE THREAD

**Issue by marslayr** [emacs-eaf/emacs-application-framework#927]
**Describe the bug**
Similar to #887, but I am on Arch Linux.

**To Reproduce**
Any EAF command.

**Expected behavior**
Open in the same window, as a buffer.

**Versions (please complete the following info):**
 - Distro and DE/WM: Arch Linux and KDE Plasma 5.24.2 (KWin) 
 - Versions of Dependencies: *Probably* Latest, ran pacman -Syu 
 - M-x emacs-version: `GNU Emacs 29.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.31, cairo version 1.17.4) of 2022-03-03`

**Error logs**
Please check the `*eaf*` buffer, if there is any error in it, paste it here.

**Screenshots**
Similar to #887. The new window size is also the same as the split window in Emacs.

**Additional context**
Any eaf app also doesn't seem to open a second time, that is, after right-clicking and clicking close

**Comment by MatthewZMD** [comment]
> * M-x emacs-version: `GNU Emacs 29.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.31, cairo version 1.17.4) of 2022-03-03`

Can you try to see if this is reproducible in 27.2 or 28?

**Comment by manateelazycat** [comment]
Please use emacs-git from repo `archlinuxcn` (see also issue https://github.com/archlinuxcn/repo/issues/2613)

The emacs-git in arch repo is not follow upstream config, developers opened the pgtk option have privately, and pgtk is disable by default.

Please follow patch https://github.com/archlinuxcn/repo/commit/064952bdab85f697f97f110113eeca5ac40151ac to disable pgtk option, I believe EAF can works agian.

**Comment by marslayr** [comment]
> Can you try to see if this is reproducible in 27.2 or 28?

Yes, that does fix it, but it misses native-compiling.

> Please use emacs-git from repo `archlinuxcn` (see also issue [archlinuxcn/repo#2613](https://github.com/archlinuxcn/repo/issues/2613))
> 
> The emacs-git in arch repo is not follow upstream config, developers opened the pgtk option privately, and pgtk is disable by default.
> 
> Please follow patch [archlinuxcn/repo@064952b](https://github.com/archlinuxcn/repo/commit/064952bdab85f697f97f110113eeca5ac40151ac) to disable pgtk option, I believe EAF can works agian.

So, I am assuming that disabling PGTK in `emacs-git` `PKGBUILD` makes it work for X?

**Comment by manateelazycat** [comment]
> 

yes，just disable pgtk

**Comment by marslayr** [comment]
> > 
> 
> yes，just disable pgtk

Okay. Thanks! Closing...

**Comment by seblemaguer** [comment]
@manateelazycat do you know if there is any plan to support pgtk in the future ?
