### ISSUE TITLE
It seems emacs-application-framework does not support emacs 29.0.05

### ISSUE THREAD

**Issue by AndyVerne** [emacs-eaf/emacs-application-framework#928]
**Describe the bug**
Install the emacs-application-framework on emacs 29.0.05 version ( with doom configuration)

**To Reproduce**
Ensure you're on the latest master branch, then note the steps to reproduce the behavior.
after install the framework, use the `eaf` package, the error just shows up:
```
Error in private config: config.el, (void-function json-parse-buffer)
```
It seems this function  is just supported on emacs 27.

**Expected behavior**
What I want is to make the eaf can run without the json-parse-buffer function or provide a method which can work around by installing extra packages.

**Versions (please complete the following info):**
 - Distro and DE/WM: Ubuntu 20.04.4
 - Versions of Dependencies: 
 - M-x emacs-version: GNU Emacs 29.0.50

**Error logs**
Please check the `*eaf*` buffer, if there is any error in it, paste it here.
```
Debugger entered--Lisp error: (void-function json-parse-buffer)
  (json-parse-buffer :object-type 'alist)
  (progn (insert-file-contents (concat eaf-build-dir "applications.json")) (goto-char 0) (json-parse-buffer :object-type 'alist))
  (unwind-protect (progn (insert-file-contents (concat eaf-build-dir "applications.json")) (goto-char 0) (json-parse-buffer :object-type 'alist)) (and (buffer-name temp-buffer) (kill-buffer temp-buffer)))
  (save-current-buffer (set-buffer temp-buffer) (unwind-protect (progn (insert-file-contents (concat eaf-build-dir "applications.json")) (goto-char 0) (json-parse-buffer :object-type 'alist)) (and (buffer-name temp-buffer) (kill-buffer temp-buffer))))
  (let ((temp-buffer (generate-new-buffer " *temp*" t))) (save-current-buffer (set-buffer temp-buffer) (unwind-protect (progn (insert-file-contents (concat eaf-build-dir "applications.json")) (goto-char 0) (json-parse-buffer :object-type 'alist)) (and (buffer-name temp-buffer) (kill-buffer temp-buffer)))))
  (let ((apps-alist (let ((temp-buffer (generate-new-buffer " *temp*" t))) (save-current-buffer (set-buffer temp-buffer) (unwind-protect (progn (insert-file-contents ...) (goto-char 0) (json-parse-buffer :object-type ...)) (and (buffer-name temp-buffer) (kill-buffer temp-buffer))))))) (cons 'set (mapcar 'eaf--alist-to-defcustom-const (cdr apps-alist))))
  eaf--json-to-defcustom-set()
  (custom-declare-variable 'eaf-apps-to-install (list 'funcall (list 'function #'(lambda nil "" nil))) "List of applications to install" :group 'eaf :type (eaf--json-to-defcustom-set))
```

**Screenshots**

**Additional context**

**Comment by seblemaguer** [comment]
Hello, 

I am using emacs 29.0.50[1] and `json-parse-buffer` is part of the code. I don't know you installed emacs, but json support needs to be activated during the configuration/compilation with the option `--with-json` when running `./configure`

[1] GNU Emacs 29.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.31, cairo version 1.17.4) of 2022-03-02

**Comment by MatthewZMD** [comment]
Aside from the helpful note by @seblemaguer (thanks!! btw), I'd like to emphasize that the latest Emacs bleading edge master (right now 29.0.50) will always have major changes *every single day*. It is far from mature, things are breaking from one day to another, or may even be just a few hours apart. EAF as an independent package doesn't have time to keep up with every commit in the Emacs master, please re-open if you can reproduce the issue in a released version (27) or even 28 as it is in the final state for releasing preparation.

**Comment by AndyVerne** [comment]
Thanks for the replies.  I will try to work it out by following the advice.
