### ISSUE TITLE
Technical background of EAF

### ISSUE THREAD

**Issue by Codeberg-AsGithubAlternative-buhtz** [emacs-eaf/emacs-application-framework#932]
Your "Vision" section is nice but take a bit to much space to make sure that you do not bash Emacs. ;)
But you missed to explain the technical background of EAF.

What is EAF? Even the Install EAF section does not make clear what it does in the background.

What I understand so far is that EAF does not run in Emacs. It is a external process, right?
And EAF is something with Python, right?
All EAF packages are using the external EAF process.

**Comment by MatthewZMD** [comment]
https://github.com/emacs-eaf/emacs-application-framework/wiki/EAF-Framework
