### ISSUE TITLE
Switch to pyqt6

### ISSUE THREAD

**Issue by jinder1s** [emacs-eaf/emacs-application-framework#938]
**Is your feature request related to a problem? Please describe.**
I am unable to install eaf on mac m1 laptop. So far, Mac M1 laptops don't have pyqt5 support. I'd love to used EAF and make it part of my daily workflow.

**Describe the solution you'd like**
Switch to pyqt6 instead of pyqt5. From the documentation I've read, its suppose to be a drop in replacement. However, I'm unfamiliar with both EAF and pyqt, so unsure how true that would hold in this situation.

**Describe alternatives you've considered**
I've tried various ways to install eaf on Mac m1 laptops and none work.

**Comment by manateelazycat** [comment]
Switch pyqt5 will break all EAF apps perhaps.

I haven't time for this recently, any PR are welcome. ;)

**Comment by MatthewZMD** [comment]
It's always a danger to chase after new versions, extensive testing would be needed to move to Qt6. Is there a reason why M1 doesn't have Qt5?

**Comment by jinder1s** [comment]
The underlying qt5 libraries don't support Apple M1 systems. The QT aimed to support Apple M1 systems starting qt6.

**Comment by jinder1s** [comment]
Accoring to following article:  [PyQt5 vs PyQt6](https://www.pythonguis.com/faq/pyqt5-vs-pyqt6/), the upgrade to qt6 might be trivial. 

I can try to implement the change locally and see how it goes.

However, I am very unfamiliar with this codebase, so I'll likely have questions. What is the best method to reach out to the community about questions?

**Comment by manateelazycat** [comment]
> trivial

No, it's not trivial, PyQt6 break many APIs, I try to switch PyQt6 today, I have leave message here if PyQt6 can work or not.

**Comment by manateelazycat** [comment]
@jinder1s EAF has support PyQt6 now!

**Comment by jinder1s** [comment]
Wow, I just saw the changes you made. My god, you are amazing!

**Comment by jinder1s** [comment]
@manateelazycat Thank you for the amazing work. 

When I tried it, I was able to install most of the dependencies, but I failed on installing pyqtwebengine. pyqtwebengine is built on top of pyqt5, so it still fails. It looks like you need [PyQt6-WebEngine](https://pypi.org/project/PyQt6-WebEngine/) to get the pyqt6 version.

**Comment by jinder1s** [comment]
I created a PR to switch to pyqty-webengine in darwin and windows systems: https://github.com/emacs-eaf/emacs-application-framework/pull/939

**Comment by manateelazycat** [comment]
> I created a PR to switch to pyqty-webengine in darwin and windows systems: #939

Merged, thanks for patch. ;)
