### ISSUE TITLE
M-x eaf-install-and-update and install-eaf.py not working

### ISSUE THREAD

**Issue by James-Hanson** [emacs-eaf/emacs-application-framework#940]
**Describe the bug**
Emacs does not recognize the command `M-x eaf-install-and-update` after cloning EAF with Git. Running the `install-eaf.py` script manually also fails:
```
[EAF] ------------------------------------------
[EAF] Installing core dependencies
[EAF] Running sudo apt -y install nodejs libglib2.0-dev python3-pyqt6 python3-sip wmctrl python3-pyqt6.qtwebengine npm @ /home/james/.emacs.d/site-lisp/emacs-application-framework
[sudo] password for james: 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package python3-pyqt6
E: Unable to locate package python3-pyqt6.qtwebengine
E: Couldn't find any package by glob 'python3-pyqt6.qtwebengine'
``` 

**To Reproduce**
Fresh Ubuntu 21.10 installation. 
Install Git and Emacs.
Run `git clone --depth=1 -b master https://github.com/emacs-eaf/emacs-application-framework.git ~/.emacs.d/site-lisp/emacs-application-framework/`.
Open Emacs. Enter `M-x eaf-install-and-update`.
Emacs responds with `[No match]`.
Go to `~/.emacs.d/site-lisp/emacs-application-framework/` in terminal. Enter `chmod +x ./install-eaf.py` and `./install-eaf.py`.
`install-eaf.py` is unable to find certain packages and fails.

**Expected behavior**
`M-x eaf-install-and-update` and `install-eaf.py` are both able to finish the installation of EAF.

**Versions (please complete the following info):**
 - Distro and DE/WM: Ubuntu 21.10.
 - M-x emacs-version: `GNU Emacs 27.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.23, cairo version 1.16.0) of 2021-01-18, modified by Debian`

**Comment by manateelazycat** [comment]
Ubuntu haven't PyQt6, I have commit new patch to fix PyQt6 install by pip repo.

Please git pull and try again, thanks for report. ;)

**Comment by manateelazycat** [comment]
Sorry PIP WebEngine always crash when you login website, I will revert those patches.

**Comment by manateelazycat** [comment]
@James-Hanson 

1. Update EAF newest version, EAF will install PyQt6 from PIP repo
2. Download package https://packages.ubuntu.com/jammy/libqt6webenginecore6 and find file ```libQt6WebEngineCore.so.6```, then symlink to ```/usr/lib/python3.10/site-packages/PyQt6/Qt6/lib/libQt6WebEngineCore.so.6```
3. Restart EAF, I believe EAF will works well with PyQt6.
