### ISSUE TITLE
Blank pages on starting eaf apps ...

### ISSUE THREAD

**Issue by akhil3417** [emacs-eaf/emacs-application-framework#943]
I am using doom emacs.Earlier it was working fine but after a fresh install of doom and eaf it is'nt

**Additional context**
Below you can see *eaf* buffer contents
![maim-window-20220405-004649](https://user-images.githubusercontent.com/92385307/161616511-ce15ce35-a088-4eca-9d79-0ed60419c875.png)

**Comment by manateelazycat** [comment]
please update EAF

**Comment by manateelazycat** [comment]
Try change permission that post in https://stackoverflow.com/questions/49886483/python-sqlite3-connect-unable-to-open-database-file

**Comment by manateelazycat** [comment]
Fix by https://github.com/emacs-eaf/emacs-application-framework/pull/944#event-6369760101
