### ISSUE TITLE
mac 运行 eaf 后，输入回车就崩溃，python 崩溃

### ISSUE THREAD

**Issue by zy9306** [emacs-eaf/emacs-application-framework#947]
emacs -Q 

虚拟环境和非虚拟环境都试过了，都会出问题，emacs27 和 28 都试过
```
(setq eaf-python-command "/Users/zy/Envs/venv38-eaf/bin/python")
(add-to-list 'load-path "/Users/zy/projects/my/emacs-application-framework")

(require 'eaf)
(require 'eaf-demo)
(require 'eaf-browser)
(require 'eaf-terminal)
(require 'eaf-file-browser)
(require 'eaf-file-manager)
(require 'eaf-org-previewer)
```

可以正常打开 demo，也可以打开 terminal

这是正常打开的 terminal，但是当我按下回车，就崩溃了

![图片](https://user-images.githubusercontent.com/18747432/162660069-6dbf0ad4-e47a-4174-8f66-6c5149cf123f.png)

```
qt.webenginecontext: 

GLImplementation: core_profile
Surface Type: OpenGL
Surface Profile: CoreProfile
Surface Version: 4.1
Using Default SG Backend: yes
Using Software Dynamic GL: no
Using Angle: no

Init Parameters:
  *  application-name Python 
  *  browser-subprocess-path /Users/zy/Envs/venv38-eaf/lib/python3.8/site-packages/PyQt6/Qt6/lib/QtWebEngineCore.framework/Helpers/QtWebEngineProcess.app/Contents/MacOS/QtWebEngineProcess 
  *  disable-features DnsOverHttpsUpgrade,ConsolidatedMovementXY,InstalledApp,BackgroundFetch,WebOTP,WebPayments,WebUSB,PictureInPicture 
  *  disable-speech-api  
  *  disable-web-security  
  *  enable-features NetworkServiceInProcess,TracingServiceInProcess 
  *  enable-gpu-rasterization  
  *  enable-native-gpu-memory-buffers  
  *  enable-threaded-compositing  
  *  ignore-gpu-blocklist  
  *  in-process-gpu  
  *  use-gl core_profile 

Terminal: timed out when communicating with server.js.
127.0.0.1 - - [11/Apr/2022 11:10:11] "GET /index.html HTTP/1.1" 200 -
Uncaught ReferenceError: title is not defined
Uncaught ReferenceError: executing_command is not defined
127.0.0.1 - - [11/Apr/2022 11:10:11] "GET /node_modules/xterm/lib/xterm.js HTTP/1.1" 200 -
127.0.0.1 - - [11/Apr/2022 11:10:11] "GET /node_modules/xterm-addon-attach/lib/xterm-addon-attach.js HTTP/1.1" 200 -
The website requested a subresource from a network that it could only access because of its users' privileged network position. These requests expose non-public devices and servers to the internet, increasing the risk of a cross-site request forgery (CSRF) attack, and/or information leakage. To mitigate these risks, Chrome deprecates requests to non-public subresources when initiated from non-secure contexts, and will start blocking them in Chrome 92 (July 2021). See https://chromestatus.com/feature/5436853517811712 for more details.
127.0.0.1 - - [11/Apr/2022 11:10:11] "GET /node_modules/xterm-addon-fit/lib/xterm-addon-fit.js HTTP/1.1" 200 -
127.0.0.1 - - [11/Apr/2022 11:10:11] "GET /node_modules/xterm-addon-search/lib/xterm-addon-search.js HTTP/1.1" 200 -
Uncaught ReferenceError: title is not defined
127.0.0.1 - - [11/Apr/2022 11:10:12] "GET /node_modules/xterm-addon-web-links/lib/xterm-addon-web-links.js HTTP/1.1" 200 -
127.0.0.1 - - [11/Apr/2022 11:10:12] "GET /node_modules/xterm/css/xterm.css HTTP/1.1" 200 -
127.0.0.1 - - [11/Apr/2022 11:10:12] "GET /light_theme.js HTTP/1.1" 200 -
Uncaught ReferenceError: executing_command is not defined

Process *eaf* trace/BPT trap: 5
```

这是 python 崩溃的日志，比较长，就放到 pastebin 了

https://pastebin.com/qwd77ajb

**Comment by manateelazycat** [comment]
terminal 目录尝试一下 npm_rebuild

**Comment by zy9306** [comment]
试过了，还是一样的问题，感觉问题在 mac 的 QtWebEngine 上，不过我对这个没啥了解，mac 上有啥需要配置的地方吗，昨天网上查了下也没啥头绪，晚上回家我试试在家里 debian 上试试，感觉还是系统问题 @manateelazycat

**Comment by manateelazycat** [comment]
> 试过了，还是一样的问题，感觉问题在 mac 的 QtWebEngine 上，不过我对这个没啥了解，mac 上有啥需要配置的地方吗，昨天网上查了下也没啥头绪，晚上回家我试试在家里 debian 上试试，感觉还是系统问题 @manateelazycat
> 
> ```python
> import sys
> from PyQt6.QtCore import *
> from PyQt6.QtWidgets import QApplication
> from PyQt6.QtWebEngineWidgets import *
> 
> my_app = QApplication(sys.argv)
> my_web = QWebEngineView()
> my_web.load(QUrl("https://www.google.com"))
> my_web.show()
> sys.exit(my_app.exec())
> ```
> 
> 我刚刚跑了下以面这段代码，能正常使用，是不是能说明 QtWebEngine 没啥问题

这是终端 node xterm 版本低导致的，但是升级后也会挂，暂时没升级，以后准备用python替代nodejs server

**Comment by manateelazycat** [comment]
什么linux发行版？

**Comment by manateelazycat** [comment]
那是pyqt6的问题

**Comment by zy9306** [comment]
但是直接用上面的那段代码直接用 QWebEngineView，弹出的浏览器各种操作又是正常的，应该都是 pyqt6吧

**Comment by manateelazycat** [comment]
> 但是直接用上面的那段代码直接用 QWebEngineView，弹出的浏览器各种操作又是正常的，应该都是 pyqt6吧

PyQt6 目前测试的情况是Arch系统自带的包没有段错误的问题， mac是因为 m1 只有PyQt6才升级的，如果可以用 PyQt5 的话，建议先切换到 PyQt5.

这个问题有几个调研结论：
1. 默认打开一个简单的网页，PyQt6是没有问题的
2. 在按回车和Backspace键的时候，PyQt6会崩溃，因为PIP的PyQt6带的 libWebEngineCore.so.6 动态库没有链接很多系统底层库，这个在Arch Linux上验证通过安装系统仓库构建的PyQt6而不用 pip 的方式，libWebEngineCore.so.6 是正常的，崩溃的根源也是 libWebEngineCore.so.6 

我没有mac系统，mac支持主要是社区开发者支持的，解决mac的方法有几个：
1. 如果不是m1芯片的mac, 是可以用PyQt5的
2. 如果只有 PIP PyQt6, 就需要想办法看看mac上系统有没有自带 libQt6WebEngineCore.so.6，把系统的库软链接到 /usr/lib/python3.10/site-packages/PyQt6/Qt6/lib/libQt6WebEngineCore.so.6 后就可以解决崩溃的问题
3. 自己在mac上手动编译 PyQt6 应该也可以解决，但是耗时太长，没有试过。

**Comment by zy9306** [comment]
可以了！pyqt5 一切良好，libWebEngineCore 有空我也再看看，感谢。

题外话，有兴趣 format 下 python 代码吗，我看代码里有些风格不一致的，可以统一 format 下，后面加个 pre-commit，风格一致的话处理 pr， code review 之类的会比较方便，python format 推荐 black。只是提一下，如果不在意这个请忽略

**Comment by manateelazycat** [comment]
> 可以了！pyqt5 一切良好，libWebEngineCore 有空我也再看看，感谢。
> 
> 题外话，有兴趣 format 下 python 代码吗，我看代码里有些风格不一致的，可以统一 format 下，后面加个 pre-commit，风格一致的话处理 pr， code review 之类的会比较方便，python format 推荐 black。只是提一下，如果不在意这个请忽略

不要 format 了，每个人的编辑器风格不一样， python 和 C 这种带括号的不一样，format 容易出逻辑错误，原来 format 过一次， format 后代码也可以跑，但是bug太隐蔽了。

遇到有问题的文件，改的时候再 format 吧，感谢建议。
