### ISSUE TITLE
EAF should not change the global value of confirm-kill-processes

### ISSUE THREAD

**Issue by ThibautVerron** [emacs-eaf/emacs-application-framework#948]
Hi,

EAF sets `confirm-kill-processes` to nil globally, in order to avoid the prompt when killing EAF buffers:
https://github.com/emacs-eaf/emacs-application-framework/blob/abba72d8b4494c859b00fc202f483cf3692386cb/eaf.el#L1776

But it is not right, as it will also disable the confirmation prompt for other processes.

The correct way would be to set it as a local variable in `eaf-mode`, so that the value is only used when killing an eaf buffer.

**Comment by manateelazycat** [comment]
Done, thanks for suggestion. ;)
