### ISSUE TITLE
`Wrong type argument: eaf-epc-manager, nil` when closing or resizing emacs window

### ISSUE THREAD

**Issue by leoc** [emacs-eaf/emacs-application-framework#950]
**Describe the bug**
I have reinstalled eaf as described by the README:

**To Reproduce**

```elisp
  (use-package eaf
    :load-path "/home/arthur/.emacs.d/vendor/emacs-application-framework"
    :init
    (require 'eaf)
    (require 'eaf-mindmap)
    (require 'eaf-markdown-previewer)
    (require 'eaf-org-previewer)
    (require 'eaf-system-monitor)
    (require 'eaf-browser)
    (require 'eaf-music-player)
    (require 'eaf-file-manager)
    (require 'eaf-jupyter)
    (require 'eaf-rss-reader)
    (require 'eaf-git)
    (require 'eaf-video-player)
    (require 'eaf-image-viewer)
    (require 'eaf-file-sender)
    (require 'eaf-demo)
    (require 'eaf-terminal)
    (require 'eaf-file-browser)
    (require 'eaf-camera)
    (setq eaf-mindmap-extension-list '("emm"))
    :custom
	;; See https://github.com/emacs-eaf/emacs-application-framework/wiki/Customization
    (eaf-browser-continue-where-left-off t)
    (eaf-browser-enable-adblocker t)
    (browse-url-browser-function 'eaf-open-browser)
    :config
    (defalias 'browse-web #'eaf-open-browser)
    (eaf-bind-key nil "M-q" eaf-browser-keybinding))
```

Whenever I try to close the frame I get the issue attached below as screenshot.

**Expected behavior**

Close the frame, man!

**Versions (please complete the following info):**
 - Distro and DE/WM: Archlinux with AwesomeWM
 - Versions of Dependencies:
 - M-x emacs-version: 28.0.50

**Error logs**
Please check the `*eaf*` buffer, if there is any error in it, paste it here.

**Screenshots**

![2022-04-14-143915_3844x2109_scrot](https://user-images.githubusercontent.com/184696/163392356-51da3681-ad28-493d-86ce-c7d4849768fb.png)

**Additional context**

**Comment by manateelazycat** [comment]
Wayland native is currently only partial support, please use xwayland first.

**Comment by leoc** [comment]
I am not using wayland. It is installed, yes, but only as dependency of gtk4 and such. 

I start X11 session as documented by Archlinux docs

**Comment by manateelazycat** [comment]
EAF use 

```
(defun eaf-emacs-running-in-wayland-native ()
  (and (eq window-system 'pgtk)
       (fboundp 'pgtk-backend-display-class)
       (string-equal (pgtk-backend-display-class) "GdkWaylandDisplay")))
```

check wayland enviroment, ```eaf-emacs-running-in-wayland-native``` return non-nil ?

**Comment by vale46** [comment]
Hi - not trying to detract from @leoc issue, but I'm seeing the same error when starting Emacs, but only in server mode. In my case, I'm running Emacs 29.0.50 complied on Windows 10 with MSYS2 (mingw64) where Emacs server is invoked from running emacsclientw.exe with switches -n -a "" -e "(raise-frame)".

Evaluating `eaf-emacs-running-in-wayland-native` returns `nil`.

If needed, happy to open under a new issue and link here.

Thx

**Comment by allenryb** [comment]
When I start the first `emacsclient` after `emacs --daemon`, the following message will come out

> or: Wrong type argument: eaf-epc-manager, nil

I am using Archlinux with Gnome and Wayland, but `eaf-emacs-running-in-wayland-native` return `nil` too.

**Comment by manateelazycat** [comment]
Don't use EAF with emacsclient.

**Comment by yuuyins** [comment]
> Don't use EAF with emacsclient.

oh no. Please, then add a disclaimer in the README about that, because this makes using EAF unfeasible for users like me. And I already had it all setup...

**Comment by yuuyins** [comment]
@manateelazycat or was that only for wayland? Does EAF supports emacsclient on X?

**Comment by manateelazycat** [comment]
> > Don't use EAF with emacsclient.
> 
> oh no. @manateelazycat Please, then add a disclaimer in the README about that, because this makes using EAF unfeasible for users like me. And I already had it all setup...

I haven't time digg why emacsclient cannot work, anyway, any PR  are welcome

**Comment by manateelazycat** [comment]
emacsclient is not support, PR are welcome.
