### ISSUE TITLE
`symlink_webengine_library ` doesn't exist in the `qt5-legacy` branch's `install-eaf.py`

### ISSUE THREAD

**Issue by AndyVerne** [emacs-eaf/emacs-application-framework#952]
**Describe the bug**

As I observe,`symlink_webengine_library` only exists in the install-eaf.py of master branch.

**To Reproduce**
Ensure you're on the latest master branch, then note the steps to reproduce the behavior.

Not in the latest master branch, but in the `qt5-legacy` branch, when the `if sys.platform != "win32" and sys.platform != "cygwin":` meets the condition, the error of not define the `symlink_webengine_library` function pops up.

**Expected behavior**

**Versions (please complete the following info):**
 - Distro and DE/WM:
 - Versions of Dependencies:
 - M-x emacs-version:

**Error logs**
Please check the `*eaf*` buffer, if there is any error in it, paste it here.

**Screenshots**

**Additional context**

**Comment by manateelazycat** [comment]
Fixed by https://github.com/emacs-eaf/emacs-application-framework/commit/0a018e420fe36eed930f1b59aba5a3314bb12d1c , thanks for report. ;)
