### ISSUE TITLE
markdown-previewer should ignore proxy

### ISSUE THREAD

**Issue by shrubbroom** [emacs-eaf/emacs-application-framework#959]
**Describe the bug**
The markdown-previewer would be unable to render if proxy is set.

**To Reproduce**
The minimal emacs setup to reproduce this bug

``` emacs-lisp
;; setup packages
(package-initialize)
(add-to-list 'load-path
             (concat user-emacs-directory
                     "site-packages/eaf"))
(setq eaf-python-command "/usr/bin/python3")
(require 'eaf)
(require 'eaf-pdf-viewer)
(require 'eaf-system-monitor)
(require 'eaf-image-viewer)
(require 'eaf-markdown-previewer)
(require 'eaf-org-previewer)
(require 'eaf-file-manager)

;; setup proxy
(setenv "socks5_proxy" "socks5://127.0.0.1:1089")
(setenv "http_proxy" "http://127.0.0.1:8889")
(setenv "https_proxy" (getenv "http_proxy"))
(setenv "all_proxy" (getenv "http_proxy"))
```

The process throw exception at [`app/markdown-previewer/buffer.py`, line 58](https://github.com/emacs-eaf/eaf-markdown-previewer/blob/2e7e3b234acde2d61c6ca410d1092e11117442f6/buffer.py#L58).

**Expected behavior**
The process should be unable to start and crash with white screen.

**Versions (please complete the following info):**
 - Distro and DE/WM: i3wm
 - Versions of Dependencies: 
 ```
local/python-pyqt6 6.3.0-1 (pyqt6)
    A set of Python bindings for the Qt6 toolkit
local/python-pyqt6-sip 13.3.1-1
    The sip module support for PyQt6
local/python-pyqt6-webengine 6.3.0-1 (pyqt6)
    Python bindings for QtWebEngine
```
 - M-x emacs-version: GNU Emacs 28.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.33, cairo version 1.17.6) of 2022-04-05

**Error logs**
``` shell
  Using host libthread_db library "/usr/lib/libthread_db.so.1".
  [New Thread 0x7fffd6a04640 (LWP 72593)]
  [New Thread 0x7fffd5fbb640 (LWP 72594)]
  [New Thread 0x7fffd53ca640 (LWP 72595)]
  [New Thread 0x7fffce573640 (LWP 72596)]
  [New Thread 0x7fffcdbe3640 (LWP 72597)]
  [New Thread 0x7fffcd253640 (LWP 72598)]
  [New Thread 0x7fffc16e9640 (LWP 72599)]
  [New Thread 0x7fffc0d59640 (LWP 72600)]
  [New Thread 0x7fffabfff640 (LWP 72601)]
  [New Thread 0x7fffab66f640 (LWP 72602)]
  [New Thread 0x7fffaacdf640 (LWP 72603)]
  [New Thread 0x7fffaa34f640 (LWP 72604)]
  [New Thread 0x7fffa99bf640 (LWP 72605)]
  [New Thread 0x7fffa902f640 (LWP 72606)]
  [New Thread 0x7fff8bfff640 (LWP 72607)]
  [New Thread 0x7fff8366f640 (LWP 72608)]
  [New Thread 0x7fff8b66f640 (LWP 72609)]
  [New Thread 0x7fff8acdf640 (LWP 72610)]
  [New Thread 0x7fff8a34f640 (LWP 72611)]
  [New Thread 0x7fff899bf640 (LWP 72612)]
  [New Thread 0x7fff8902f640 (LWP 72613)]
  [Thread 0x7fff8902f640 (LWP 72613) exited]
  [New Thread 0x7fff8902f640 (LWP 72614)]
  [New Thread 0x7fff83fff640 (LWP 72615)]
  [New Thread 0x7fff82cdf640 (LWP 72616)]
  [Thread 0x7fff82cdf640 (LWP 72616) exited]
  [New Thread 0x7fff82cdf640 (LWP 72617)]
  [Thread 0x7fff82cdf640 (LWP 72617) exited]
  [New Thread 0x7fff82cdf640 (LWP 72618)]
  [Thread 0x7fff82cdf640 (LWP 72618) exited]
  [New Thread 0x7fff82cdf640 (LWP 72619)]
  [New Thread 0x7fff8234f640 (LWP 72620)]
  [Thread 0x7fff8234f640 (LWP 72620) exited]
  [Thread 0x7fff82cdf640 (LWP 72619) exited]
  [New Thread 0x7fff82cdf640 (LWP 72621)]
  [Thread 0x7fff82cdf640 (LWP 72621) exited]
  [New Thread 0x7fff82cdf640 (LWP 72622)]
  [Thread 0x7fff82cdf640 (LWP 72622) exited]
  [New Thread 0x7fff82cdf640 (LWP 72623)]
  [Thread 0x7fff82cdf640 (LWP 72623) exited]
  [New Thread 0x7fff82cdf640 (LWP 72624)]
  [Thread 0x7fff82cdf640 (LWP 72624) exited]
  qt.webenginecontext: 

  GL Type: desktop
  Surface Type: OpenGL
  Surface Profile: CompatibilityProfile
  Surface Version: 4.6
  QSG RHI Backend: OpenGL
  Using Supported QSG Backend: yes
  Using Software Dynamic GL: no
  Using Multithreaded OpenGL: yes

  Init Parameters:
    ,*  application-name eaf.py 
    ,*  browser-subprocess-path /usr/lib/qt6/QtWebEngineProcess 
    ,*  create-default-gl-context  
    ,*  disable-features ConsolidatedMovementXY,InstalledApp,BackgroundFetch,WebOTP,WebPayments,WebUSB,PictureInPicture 
    ,*  disable-setuid-sandbox  
    ,*  disable-speech-api  
    ,*  disable-web-security  
    ,*  enable-features NetworkServiceInProcess,TracingServiceInProcess 
    ,*  enable-gpu-rasterization  
    ,*  enable-native-gpu-memory-buffers  
    ,*  enable-threaded-compositing  
    ,*  ignore-gpu-blocklist  
    ,*  in-process-gpu  
    ,*  use-gl desktop 

  [New Thread 0x7fff82cdf640 (LWP 72625)]
  [Detaching after fork from child process 72626]
  [Detaching after fork from child process 72627]
  [Detaching after fork from child process 72628]
  [New Thread 0x7fff8234f640 (LWP 72631)]
  [New Thread 0x7fff811b9640 (LWP 72632)]
  [New Thread 0x7fff5bfff640 (LWP 72633)]
  [New Thread 0x7fff5b66f640 (LWP 72634)]
  [New Thread 0x7fff5acdf640 (LWP 72635)]
  [New Thread 0x7fff5a34f640 (LWP 72636)]
  [New Thread 0x7fff599bf640 (LWP 72637)]
  [New Thread 0x7fff5902f640 (LWP 72638)]
  [New Thread 0x7fff43fff640 (LWP 72639)]
  [New Thread 0x7fff4366f640 (LWP 72640)]
  [New Thread 0x7fff42cdf640 (LWP 72641)]
  [New Thread 0x7fff4234f640 (LWP 72642)]
  [New Thread 0x7fff419bf640 (LWP 72643)]
  [New Thread 0x7fff4102f640 (LWP 72644)]
  [New Thread 0x7fff23fff640 (LWP 72645)]
  [Thread 0x7fff23fff640 (LWP 72645) exited]
  [New Thread 0x7fff23fff640 (LWP 72646)]
  [Thread 0x7fff23fff640 (LWP 72646) exited]
  [New Thread 0x7fff23fff640 (LWP 72647)]
  [New Thread 0x7fff2366f640 (LWP 72648)]
  [New Thread 0x7fff22cdf640 (LWP 72649)]
  [Thread 0x7fff22cdf640 (LWP 72649) exited]
  [New Thread 0x7fff22cdf640 (LWP 72650)]
  [Thread 0x7fff22cdf640 (LWP 72650) exited]
  [New Thread 0x7fff22cdf640 (LWP 72651)]
  [Thread 0x7fff22cdf640 (LWP 72651) exited]
  [New Thread 0x7fff22cdf640 (LWP 72652)]
  [Thread 0x7fff22cdf640 (LWP 72652) exited]
  [Detaching after vfork from child process 72653]
  [New Thread 0x7fff22cdf640 (LWP 72660)]
  [Thread 0x7fff22cdf640 (LWP 72660) exited]
  [New Thread 0x7fff22cdf640 (LWP 72663)]
  [Thread 0x7fff22cdf640 (LWP 72663) exited]
  [New Thread 0x7fff22cdf640 (LWP 72666)]
  [Thread 0x7fff22cdf640 (LWP 72666) exited]
  [New Thread 0x7fff22cdf640 (LWP 72667)]
  [Thread 0x7fff22cdf640 (LWP 72667) exited]
  Traceback (most recent call last):
    File "/home/shrubbroom/.config/emacs/site-packages/eaf/core/utils.py", line 50, in on_signal_received
      self._func(obj, *args, **kwargs)
    File "/home/shrubbroom/.emacs.d/site-packages/eaf/eaf.py", line 153, in new_buffer
      self.create_buffer(buffer_id, url, module_path, arguments)
    File "/home/shrubbroom/.emacs.d/site-packages/eaf/eaf.py", line 171, in create_buffer
      app_buffer = module.AppBuffer(buffer_id, url, arguments)
    File "/home/shrubbroom/.emacs.d/site-packages/eaf/app/markdown-previewer/buffer.py", line 58, in __init__
      self.render()
    File "/usr/lib/python3.10/site-packages/retrying.py", line 49, in wrapped_f
      return Retrying(*dargs, **dkw).call(f, *args, **kw)
    File "/usr/lib/python3.10/site-packages/retrying.py", line 206, in call
      return attempt.get(self._wrap_exception)
    File "/usr/lib/python3.10/site-packages/retrying.py", line 247, in get
      six.reraise(self.value[0], self.value[1], self.value[2])
    File "/usr/lib/python3.10/site-packages/six.py", line 719, in reraise
      raise value
    File "/usr/lib/python3.10/site-packages/retrying.py", line 200, in call
      attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
    File "/home/shrubbroom/.emacs.d/site-packages/eaf/app/markdown-previewer/buffer.py", line 82, in render
      with urlopen(url) as f:
    File "/usr/lib/python3.10/urllib/request.py", line 216, in urlopen
      return opener.open(url, data, timeout)
    File "/usr/lib/python3.10/urllib/request.py", line 525, in open
      response = meth(req, response)
    File "/usr/lib/python3.10/urllib/request.py", line 634, in http_response
      response = self.parent.error(
    File "/usr/lib/python3.10/urllib/request.py", line 563, in error
      return self._call_chain(*args)
    File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
      result = func(*args)
    File "/usr/lib/python3.10/urllib/request.py", line 643, in http_error_default
      raise HTTPError(req.full_url, code, msg, hdrs, fp)
  urllib.error.HTTPError: HTTP Error 503: Service Unavailable
  Traceback (most recent call last):
    File "/home/shrubbroom/.config/emacs/site-packages/eaf/core/utils.py", line 50, in on_signal_received
      self._func(obj, *args, **kwargs)
    File "/home/shrubbroom/.emacs.d/site-packages/eaf/eaf.py", line 236, in update_views
      view = View(self.buffer_dict[buffer_id], view_info)
  KeyError: '5390-be30-cb39-ea8c-9c28-210f-8343'
  Traceback (most recent call last):
    File "/home/shrubbroom/.config/emacs/site-packages/eaf/core/utils.py", line 50, in on_signal_received
      self._func(obj, *args, **kwargs)
    File "/home/shrubbroom/.emacs.d/site-packages/eaf/eaf.py", line 236, in update_views
      view = View(self.buffer_dict[buffer_id], view_info)
  KeyError: '5390-be30-cb39-ea8c-9c28-210f-8343'
  Traceback (most recent call last):
    File "/home/shrubbroom/.config/emacs/site-packages/eaf/core/utils.py", line 50, in on_signal_received
      self._func(obj, *args, **kwargs)
    File "/home/shrubbroom/.emacs.d/site-packages/eaf/eaf.py", line 236, in update_views
      view = View(self.buffer_dict[buffer_id], view_info)
  KeyError: '5390-be30-cb39-ea8c-9c28-210f-8343'
  Traceback (most recent call last):
    File "/home/shrubbroom/.config/emacs/site-packages/eaf/core/utils.py", line 50, in on_signal_received
      self._func(obj, *args, **kwargs)
    File "/home/shrubbroom/.emacs.d/site-packages/eaf/eaf.py", line 236, in update_views
      view = View(self.buffer_dict[buffer_id], view_info)
  KeyError: '5390-be30-cb39-ea8c-9c28-210f-8343'
  Traceback (most recent call last):
    File "/home/shrubbroom/.config/emacs/site-packages/eaf/core/utils.py", line 50, in on_signal_received
      self._func(obj, *args, **kwargs)
    File "/home/shrubbroom/.emacs.d/site-packages/eaf/eaf.py", line 236, in update_views
      view = View(self.buffer_dict[buffer_id], view_info)
  KeyError: '5390-be30-cb39-ea8c-9c28-210f-8343'
  [New Thread 0x7fff22cdf640 (LWP 72679)]
  [New Thread 0x7fff2234f640 (LWP 72680)]
  [New Thread 0x7fff219bf640 (LWP 72681)]
  [New Thread 0x7fff2102f640 (LWP 72683)]
  [Thread 0x7fff2102f640 (LWP 72683) exited]
  [New Thread 0x7fff2102f640 (LWP 72696)]
  [New Thread 0x7fff07fff640 (LWP 72697)]
  [New Thread 0x7fff0766f640 (LWP 72698)]
  [New Thread 0x7fff06cdf640 (LWP 72699)]
  [New Thread 0x7fff0634f640 (LWP 72707)]
  Traceback (most recent call last):
  [Thread 0x7fff0634f640 (LWP 72707) exited]
    File "/home/shrubbroom/.config/emacs/site-packages/eaf/core/utils.py", line 50, in on_signal_received
      self._func(obj, *args, **kwargs)
    File "/home/shrubbroom/.emacs.d/site-packages/eaf/eaf.py", line 236, in update_views
      view = View(self.buffer_dict[buffer_id], view_info)
  KeyError: '5390-be30-cb39-ea8c-9c28-210f-8343'
  [New Thread 0x7fff0634f640 (LWP 72710)]
  Traceback (most recent call last):
    File "/home/shrubbroom/.config/emacs/site-packages/eaf/core/utils.py", line 50, in on_signal_received
      self._func(obj, *args, **kwargs)
    File "/home/shrubbroom/.emacs.d/site-packages/eaf/eaf.py", line 236, in update_views
      view = View(self.buffer_dict[buffer_id], view_info)
  KeyError: '5390-be30-cb39-ea8c-9c28-210f-8343'
  [Thread 0x7fff0634f640 (LWP 72710) exited]
```
**Screenshots**
The application crashes with white screen

**Comment by manateelazycat** [comment]
> **Describe the bug** The markdown-previewer would be unable to render if proxy is set.
> 
> **To Reproduce** The minimal emacs setup to reproduce this bug
> 
> ```emacs-lisp
> ;; setup packages
> (package-initialize)
> (add-to-list 'load-path
>              (concat user-emacs-directory
>                      "site-packages/eaf"))
> (setq eaf-python-command "/usr/bin/python3")
> (require 'eaf)
> (require 'eaf-pdf-viewer)
> (require 'eaf-system-monitor)
> (require 'eaf-image-viewer)
> (require 'eaf-markdown-previewer)
> (require 'eaf-org-previewer)
> (require 'eaf-file-manager)
> 
> ;; setup proxy
> (setenv "socks5_proxy" "socks5://127.0.0.1:1089")
> (setenv "http_proxy" "http://127.0.0.1:8889")
> (setenv "https_proxy" (getenv "http_proxy"))
> (setenv "all_proxy" (getenv "http_proxy"))
> ```
> 
> The process throw exception at [`app/markdown-previewer/buffer.py`, line 58](https://github.com/emacs-eaf/eaf-markdown-previewer/blob/2e7e3b234acde2d61c6ca410d1092e11117442f6/buffer.py#L58).
> 
> **Expected behavior** The process should be unable to start and crash with white screen.
> 
> **Versions (please complete the following info):**
> 
> * Distro and DE/WM: i3wm
> * Versions of Dependencies:
> 
> ```
> local/python-pyqt6 6.3.0-1 (pyqt6)
>    A set of Python bindings for the Qt6 toolkit
> local/python-pyqt6-sip 13.3.1-1
>    The sip module support for PyQt6
> local/python-pyqt6-webengine 6.3.0-1 (pyqt6)
>    Python bindings for QtWebEngine
> ```
> 
> * M-x emacs-version: GNU Emacs 28.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.33, cairo version 1.17.6) of 2022-04-05
> 
> **Error logs**
> 
> ```shell
>   Using host libthread_db library "/usr/lib/libthread_db.so.1".
>   [New Thread 0x7fffd6a04640 (LWP 72593)]
>   [New Thread 0x7fffd5fbb640 (LWP 72594)]
>   [New Thread 0x7fffd53ca640 (LWP 72595)]
>   [New Thread 0x7fffce573640 (LWP 72596)]
>   [New Thread 0x7fffcdbe3640 (LWP 72597)]
>   [New Thread 0x7fffcd253640 (LWP 72598)]
>   [New Thread 0x7fffc16e9640 (LWP 72599)]
>   [New Thread 0x7fffc0d59640 (LWP 72600)]
>   [New Thread 0x7fffabfff640 (LWP 72601)]
>   [New Thread 0x7fffab66f640 (LWP 72602)]
>   [New Thread 0x7fffaacdf640 (LWP 72603)]
>   [New Thread 0x7fffaa34f640 (LWP 72604)]
>   [New Thread 0x7fffa99bf640 (LWP 72605)]
>   [New Thread 0x7fffa902f640 (LWP 72606)]
>   [New Thread 0x7fff8bfff640 (LWP 72607)]
>   [New Thread 0x7fff8366f640 (LWP 72608)]
>   [New Thread 0x7fff8b66f640 (LWP 72609)]
>   [New Thread 0x7fff8acdf640 (LWP 72610)]
>   [New Thread 0x7fff8a34f640 (LWP 72611)]
>   [New Thread 0x7fff899bf640 (LWP 72612)]
>   [New Thread 0x7fff8902f640 (LWP 72613)]
>   [Thread 0x7fff8902f640 (LWP 72613) exited]
>   [New Thread 0x7fff8902f640 (LWP 72614)]
>   [New Thread 0x7fff83fff640 (LWP 72615)]
>   [New Thread 0x7fff82cdf640 (LWP 72616)]
>   [Thread 0x7fff82cdf640 (LWP 72616) exited]
>   [New Thread 0x7fff82cdf640 (LWP 72617)]
>   [Thread 0x7fff82cdf640 (LWP 72617) exited]
>   [New Thread 0x7fff82cdf640 (LWP 72618)]
>   [Thread 0x7fff82cdf640 (LWP 72618) exited]
>   [New Thread 0x7fff82cdf640 (LWP 72619)]
>   [New Thread 0x7fff8234f640 (LWP 72620)]
>   [Thread 0x7fff8234f640 (LWP 72620) exited]
>   [Thread 0x7fff82cdf640 (LWP 72619) exited]
>   [New Thread 0x7fff82cdf640 (LWP 72621)]
>   [Thread 0x7fff82cdf640 (LWP 72621) exited]
>   [New Thread 0x7fff82cdf640 (LWP 72622)]
>   [Thread 0x7fff82cdf640 (LWP 72622) exited]
>   [New Thread 0x7fff82cdf640 (LWP 72623)]
>   [Thread 0x7fff82cdf640 (LWP 72623) exited]
>   [New Thread 0x7fff82cdf640 (LWP 72624)]
>   [Thread 0x7fff82cdf640 (LWP 72624) exited]
>   qt.webenginecontext: 
> 
>   GL Type: desktop
>   Surface Type: OpenGL
>   Surface Profile: CompatibilityProfile
>   Surface Version: 4.6
>   QSG RHI Backend: OpenGL
>   Using Supported QSG Backend: yes
>   Using Software Dynamic GL: no
>   Using Multithreaded OpenGL: yes
> 
>   Init Parameters:
>     ,*  application-name eaf.py 
>     ,*  browser-subprocess-path /usr/lib/qt6/QtWebEngineProcess 
>     ,*  create-default-gl-context  
>     ,*  disable-features ConsolidatedMovementXY,InstalledApp,BackgroundFetch,WebOTP,WebPayments,WebUSB,PictureInPicture 
>     ,*  disable-setuid-sandbox  
>     ,*  disable-speech-api  
>     ,*  disable-web-security  
>     ,*  enable-features NetworkServiceInProcess,TracingServiceInProcess 
>     ,*  enable-gpu-rasterization  
>     ,*  enable-native-gpu-memory-buffers  
>     ,*  enable-threaded-compositing  
>     ,*  ignore-gpu-blocklist  
>     ,*  in-process-gpu  
>     ,*  use-gl desktop 
> 
>   [New Thread 0x7fff82cdf640 (LWP 72625)]
>   [Detaching after fork from child process 72626]
>   [Detaching after fork from child process 72627]
>   [Detaching after fork from child process 72628]
>   [New Thread 0x7fff8234f640 (LWP 72631)]
>   [New Thread 0x7fff811b9640 (LWP 72632)]
>   [New Thread 0x7fff5bfff640 (LWP 72633)]
>   [New Thread 0x7fff5b66f640 (LWP 72634)]
>   [New Thread 0x7fff5acdf640 (LWP 72635)]
>   [New Thread 0x7fff5a34f640 (LWP 72636)]
>   [New Thread 0x7fff599bf640 (LWP 72637)]
>   [New Thread 0x7fff5902f640 (LWP 72638)]
>   [New Thread 0x7fff43fff640 (LWP 72639)]
>   [New Thread 0x7fff4366f640 (LWP 72640)]
>   [New Thread 0x7fff42cdf640 (LWP 72641)]
>   [New Thread 0x7fff4234f640 (LWP 72642)]
>   [New Thread 0x7fff419bf640 (LWP 72643)]
>   [New Thread 0x7fff4102f640 (LWP 72644)]
>   [New Thread 0x7fff23fff640 (LWP 72645)]
>   [Thread 0x7fff23fff640 (LWP 72645) exited]
>   [New Thread 0x7fff23fff640 (LWP 72646)]
>   [Thread 0x7fff23fff640 (LWP 72646) exited]
>   [New Thread 0x7fff23fff640 (LWP 72647)]
>   [New Thread 0x7fff2366f640 (LWP 72648)]
>   [New Thread 0x7fff22cdf640 (LWP 72649)]
>   [Thread 0x7fff22cdf640 (LWP 72649) exited]
>   [New Thread 0x7fff22cdf640 (LWP 72650)]
>   [Thread 0x7fff22cdf640 (LWP 72650) exited]
>   [New Thread 0x7fff22cdf640 (LWP 72651)]
>   [Thread 0x7fff22cdf640 (LWP 72651) exited]
>   [New Thread 0x7fff22cdf640 (LWP 72652)]
>   [Thread 0x7fff22cdf640 (LWP 72652) exited]
>   [Detaching after vfork from child process 72653]
>   [New Thread 0x7fff22cdf640 (LWP 72660)]
>   [Thread 0x7fff22cdf640 (LWP 72660) exited]
>   [New Thread 0x7fff22cdf640 (LWP 72663)]
>   [Thread 0x7fff22cdf640 (LWP 72663) exited]
>   [New Thread 0x7fff22cdf640 (LWP 72666)]
>   [Thread 0x7fff22cdf640 (LWP 72666) exited]
>   [New Thread 0x7fff22cdf640 (LWP 72667)]
>   [Thread 0x7fff22cdf640 (LWP 72667) exited]
>   Traceback (most recent call last):
>     File "/home/shrubbroom/.config/emacs/site-packages/eaf/core/utils.py", line 50, in on_signal_received
>       self._func(obj, *args, **kwargs)
>     File "/home/shrubbroom/.emacs.d/site-packages/eaf/eaf.py", line 153, in new_buffer
>       self.create_buffer(buffer_id, url, module_path, arguments)
>     File "/home/shrubbroom/.emacs.d/site-packages/eaf/eaf.py", line 171, in create_buffer
>       app_buffer = module.AppBuffer(buffer_id, url, arguments)
>     File "/home/shrubbroom/.emacs.d/site-packages/eaf/app/markdown-previewer/buffer.py", line 58, in __init__
>       self.render()
>     File "/usr/lib/python3.10/site-packages/retrying.py", line 49, in wrapped_f
>       return Retrying(*dargs, **dkw).call(f, *args, **kw)
>     File "/usr/lib/python3.10/site-packages/retrying.py", line 206, in call
>       return attempt.get(self._wrap_exception)
>     File "/usr/lib/python3.10/site-packages/retrying.py", line 247, in get
>       six.reraise(self.value[0], self.value[1], self.value[2])
>     File "/usr/lib/python3.10/site-packages/six.py", line 719, in reraise
>       raise value
>     File "/usr/lib/python3.10/site-packages/retrying.py", line 200, in call
>       attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
>     File "/home/shrubbroom/.emacs.d/site-packages/eaf/app/markdown-previewer/buffer.py", line 82, in render
>       with urlopen(url) as f:
>     File "/usr/lib/python3.10/urllib/request.py", line 216, in urlopen
>       return opener.open(url, data, timeout)
>     File "/usr/lib/python3.10/urllib/request.py", line 525, in open
>       response = meth(req, response)
>     File "/usr/lib/python3.10/urllib/request.py", line 634, in http_response
>       response = self.parent.error(
>     File "/usr/lib/python3.10/urllib/request.py", line 563, in error
>       return self._call_chain(*args)
>     File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
>       result = func(*args)
>     File "/usr/lib/python3.10/urllib/request.py", line 643, in http_error_default
>       raise HTTPError(req.full_url, code, msg, hdrs, fp)
>   urllib.error.HTTPError: HTTP Error 503: Service Unavailable
>   Traceback (most recent call last):
>     File "/home/shrubbroom/.config/emacs/site-packages/eaf/core/utils.py", line 50, in on_signal_received
>       self._func(obj, *args, **kwargs)
>     File "/home/shrubbroom/.emacs.d/site-packages/eaf/eaf.py", line 236, in update_views
>       view = View(self.buffer_dict[buffer_id], view_info)
>   KeyError: '5390-be30-cb39-ea8c-9c28-210f-8343'
>   Traceback (most recent call last):
>     File "/home/shrubbroom/.config/emacs/site-packages/eaf/core/utils.py", line 50, in on_signal_received
>       self._func(obj, *args, **kwargs)
>     File "/home/shrubbroom/.emacs.d/site-packages/eaf/eaf.py", line 236, in update_views
>       view = View(self.buffer_dict[buffer_id], view_info)
>   KeyError: '5390-be30-cb39-ea8c-9c28-210f-8343'
>   Traceback (most recent call last):
>     File "/home/shrubbroom/.config/emacs/site-packages/eaf/core/utils.py", line 50, in on_signal_received
>       self._func(obj, *args, **kwargs)
>     File "/home/shrubbroom/.emacs.d/site-packages/eaf/eaf.py", line 236, in update_views
>       view = View(self.buffer_dict[buffer_id], view_info)
>   KeyError: '5390-be30-cb39-ea8c-9c28-210f-8343'
>   Traceback (most recent call last):
>     File "/home/shrubbroom/.config/emacs/site-packages/eaf/core/utils.py", line 50, in on_signal_received
>       self._func(obj, *args, **kwargs)
>     File "/home/shrubbroom/.emacs.d/site-packages/eaf/eaf.py", line 236, in update_views
>       view = View(self.buffer_dict[buffer_id], view_info)
>   KeyError: '5390-be30-cb39-ea8c-9c28-210f-8343'
>   Traceback (most recent call last):
>     File "/home/shrubbroom/.config/emacs/site-packages/eaf/core/utils.py", line 50, in on_signal_received
>       self._func(obj, *args, **kwargs)
>     File "/home/shrubbroom/.emacs.d/site-packages/eaf/eaf.py", line 236, in update_views
>       view = View(self.buffer_dict[buffer_id], view_info)
>   KeyError: '5390-be30-cb39-ea8c-9c28-210f-8343'
>   [New Thread 0x7fff22cdf640 (LWP 72679)]
>   [New Thread 0x7fff2234f640 (LWP 72680)]
>   [New Thread 0x7fff219bf640 (LWP 72681)]
>   [New Thread 0x7fff2102f640 (LWP 72683)]
>   [Thread 0x7fff2102f640 (LWP 72683) exited]
>   [New Thread 0x7fff2102f640 (LWP 72696)]
>   [New Thread 0x7fff07fff640 (LWP 72697)]
>   [New Thread 0x7fff0766f640 (LWP 72698)]
>   [New Thread 0x7fff06cdf640 (LWP 72699)]
>   [New Thread 0x7fff0634f640 (LWP 72707)]
>   Traceback (most recent call last):
>   [Thread 0x7fff0634f640 (LWP 72707) exited]
>     File "/home/shrubbroom/.config/emacs/site-packages/eaf/core/utils.py", line 50, in on_signal_received
>       self._func(obj, *args, **kwargs)
>     File "/home/shrubbroom/.emacs.d/site-packages/eaf/eaf.py", line 236, in update_views
>       view = View(self.buffer_dict[buffer_id], view_info)
>   KeyError: '5390-be30-cb39-ea8c-9c28-210f-8343'
>   [New Thread 0x7fff0634f640 (LWP 72710)]
>   Traceback (most recent call last):
>     File "/home/shrubbroom/.config/emacs/site-packages/eaf/core/utils.py", line 50, in on_signal_received
>       self._func(obj, *args, **kwargs)
>     File "/home/shrubbroom/.emacs.d/site-packages/eaf/eaf.py", line 236, in update_views
>       view = View(self.buffer_dict[buffer_id], view_info)
>   KeyError: '5390-be30-cb39-ea8c-9c28-210f-8343'
>   [Thread 0x7fff0634f640 (LWP 72710) exited]
> ```
> 
> **Screenshots** The application crashes with white screen

why add proxy on localhost ?

**Comment by shrubbroom** [comment]
These proxies are useful in eshell.  Programs run from eshell can benefit from these configurations.

**Comment by shrubbroom** [comment]
I think this is a `markdown-previewer` specific problem since the localhost is not under proxy and can be accessed with `eaf-browser` in my machine.  However, with `markdown-previewer` this problem can be steadily reproduced.

**Comment by manateelazycat** [comment]
> I think this is a `markdown-previewer` specific problem since the localhost is not under proxy and can be accessed with `eaf-browser` in my machine. However, with `markdown-previewer` this problem can be steadily reproduced.

No, I can't reproduced this, I also use proxy for eaf-browser

**Comment by manateelazycat** [comment]
Markdown-Previewer open localhost address, no effect by proxy.
