### ISSUE TITLE
How to enable smooth scroll?

### ISSUE THREAD

**Issue by Dima-369** [emacs-eaf/emacs-application-framework#960]
I tried this in `core/webengine.py`, but it does not seem to do anything?

```python
self.settings.setAttribute(QWebEngineSettings.ScrollAnimatorEnabled, True)
```

Or is this only an macOS issue? Does it work for someone else?

I want `eaf-py-proxy-scroll_up_page` to have smooth scroll (similar to how Firefox does it), as right now it just jumps around the page.

**Comment by manateelazycat** [comment]
Smooth scroll will slow down when you hold down the key, it need you implement scroll function that control y offset yourself, eval_js is slow.

**Comment by Dima-369** [comment]
Okay, I was hoping that it would be as smooth as in Firefox, but that is apparently not the case.

Closing this, as the smooth scroll code from above works and the sluggishness is not that bad.

**Comment by manateelazycat** [comment]
@Dima-369 Hi bro, I just use postEvent instead sendEvent in newest version, can you upgrade EAF and test again?

sendEvent will blocking event and wait for the event to be executed to complete, and postEvent just send event to Qt event loop, won't block event loop.

Your problem perhaps fix upgrade EAF. ;)

**Comment by Dima-369** [comment]
I would love to try it out, but apparently I have a problem with the current `master` on PyQt6: https://github.com/emacs-eaf/emacs-application-framework/issues/967

**Comment by Dima-369** [comment]
@manateelazycat Hey, I updated to the latest version, but I noticed how the code in https://github.com/emacs-eaf/emacs-application-framework/issues/960#issuecomment-1108611065 does not result in smooth scroll anymore on Qt6? Can you confirm?

Even with `QWebEngineSettings.ScrollAnimatorEnabled` enabled, there is no smooth scroll.

**Comment by Dima-369** [comment]
I figured it out!

With Qt 6 on the latest `master`, one needs to use `self.settings.setAttribute(QWebEngineSettings.WebAttribute.ScrollAnimatorEnabled, True)` (with `.WebAttribute` added) to have smooth scroll plus the `eval_js` calls as outlined above.

**Comment by Dima-369** [comment]
> I just use postEvent instead sendEvent in newest version, can you upgrade EAF and test again?

I can confirm that it behaves a lot nicer now! Perfect, thanks!

**Comment by Dima-369** [comment]
> With Qt 6 on the latest master, one needs to use self.settings.setAttribute(QWebEngineSettings.WebAttribute.ScrollAnimatorEnabled, True) (with .WebAttribute added) to have smooth scroll plus the eval_js calls as outlined above.

Actually, the `eval_js` calls are no longer necessary, since the setting seems to apply 'globally' since it applies to all `self.scroll_wheel()` calls. Amazing!
