### ISSUE TITLE
Unable to use since PyQt6 is used due to being unable to import QtWebEngineWidgets

### ISSUE THREAD

**Issue by Dima-369** [emacs-eaf/emacs-application-framework#967]
Since PyQt6 is used, I get this error in the `*eaf*` buffer on the latest EAF commit, even after running `install-eaf.py`:

```bash
Process *eaf* exited abnormally with code 1
Traceback (most recent call last):
  File "/Users/Gira/.emacs.d/site-lisp/emacs-application-framework/eaf.py", line 25, in <module>
    from PyQt6 import QtWebEngineWidgets as NeverUsed # noqa
ImportError: cannot import name 'QtWebEngineWidgets' from 'PyQt6' (/usr/local/lib/python3.9/site-packages/PyQt6/__init__.py)
```

---

I tried to remove the `from PyQt6 import QtWebEngineWidgets as NeverUsed # noqa` line from `eaf.py`, but this results in this error instead:

```bash
Process *eaf* exited abnormally with code 1
qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: cocoa, minimal, offscreen.
```

**Versions (please complete the following info):**
 - M-x emacs-version: `GNU Emacs 28.1 (build 2, x86_64-apple-darwin18.7.0, NS appkit-1671.60 Version 10.14.6 (Build 18G9216)) of 2022-04-13`
 - OS: macOS 10.14.6

---

Does anyone know of a fix?

**Comment by manateelazycat** [comment]
> Since PyQt6 is used, I get this error in the `*eaf*` buffer on the latest EAF commit, even after running `install-eaf.py`:
> 
> ```shell
> Process *eaf* exited abnormally with code 1
> Traceback (most recent call last):
>   File "/Users/Gira/.emacs.d/site-lisp/emacs-application-framework/eaf.py", line 25, in <module>
>     from PyQt6 import QtWebEngineWidgets as NeverUsed # noqa
> ImportError: cannot import name 'QtWebEngineWidgets' from 'PyQt6' (/usr/local/lib/python3.9/site-packages/PyQt6/__init__.py)
> ```
> 
> I tried to remove the `from PyQt6 import QtWebEngineWidgets as NeverUsed # noqa` line from `eaf.py`, but this results in this error instead:
> 
> ```shell
> Process *eaf* exited abnormally with code 1
> qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""
> This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
> 
> Available platform plugins are: cocoa, minimal, offscreen.
> ```
> 
> **Versions (please complete the following info):**
> 
> * M-x emacs-version: `GNU Emacs 28.1 (build 2, x86_64-apple-darwin18.7.0, NS appkit-1671.60 Version 10.14.6 (Build 18G9216)) of 2022-04-13`
> * OS: macOS 10.14.6
> 
> Does anyone know of a fix?

did you run install-eaf.py again after you switch to qt6 branch?

**Comment by Dima-369** [comment]
> did you run install-eaf.py again after you switch to qt6 branch?

Yeah, I did.

I just now tried the `qt5-legacy` branch but there I get a different error:

```
Traceback (most recent call last):
  File "/Users/Gira/.emacs.d/site-lisp/emacs-application-framework/eaf.py", line 25, in <module>
    from PyQt5 import QtWebEngineWidgets as NeverUsed # noqa
ImportError: cannot import name 'QtWebEngineWidgets' from 'PyQt5' (unknown location)
```

I get the idea that I broke some Python paths. Maybe it's just on my side.

**Comment by Dima-369** [comment]
I found other issues online with the `qt.qpa.plugin: Could not find the Qt platform plugin "xcb"` error, but this is not related to EAF at all, so closing this.

**Comment by wowhxj** [comment]
I encountered the same issue today when I reinstalled emacs and eaf in my Macbook Pro.

MacOS version: 12.3.1
Emacs version: GNU Emacs 29.0.50 (build 1, x86_64-apple-darwin21.4.0, NS appkit-2113.40 Version 12.3.1 (Build 21E258)) of 2022-05-02
Python version: Python 3.9.12 (new venv environment without any package installed)

`./install-eaf.py` results:
```
$ ./install-eaf.py
[EAF] ------------------------------------------
[EAF] Installing core dependencies
[EAF] Running pip install epc tld lxml mac-app-frontmost PyQt6 PyQt6-Qt6 PyQt6-sip PyQt6-WebEngine PyQt6-WebEngine-Qt6 @ /Users/randolph/.emacs.d/site-lisp/emacs-application-framework
Requirement already satisfied: epc in /Users/randolph/.venv/py39/lib/python3.9/site-packages (0.0.5)
Requirement already satisfied: tld in /Users/randolph/.venv/py39/lib/python3.9/site-packages (0.12.6)
Requirement already satisfied: lxml in /Users/randolph/.venv/py39/lib/python3.9/site-packages (4.8.0)
Requirement already satisfied: mac-app-frontmost in /Users/randolph/.venv/py39/lib/python3.9/site-packages (2020.12.3)
Requirement already satisfied: PyQt6 in /Users/randolph/.venv/py39/lib/python3.9/site-packages (6.3.0)
Requirement already satisfied: PyQt6-Qt6 in /Users/randolph/.venv/py39/lib/python3.9/site-packages (6.3.0)
Requirement already satisfied: PyQt6-sip in /Users/randolph/.venv/py39/lib/python3.9/site-packages (13.3.1)
Requirement already satisfied: PyQt6-WebEngine in /Users/randolph/.venv/py39/lib/python3.9/site-packages (6.3.0)
Requirement already satisfied: PyQt6-WebEngine-Qt6 in /Users/randolph/.venv/py39/lib/python3.9/site-packages (6.3.0)
Requirement already satisfied: sexpdata>=0.0.3 in /Users/randolph/.venv/py39/lib/python3.9/site-packages (from epc) (0.0.3)
[EAF] Finished installing core dependencies
[EAF] ------------------------------------------
[EAF] ------------------------------------------
[EAF] Installing application dependencies

[EAF] Updating browser to newest version...
[EAF] Running git branch @ app/browser
[EAF] Running git symbolic-ref HEAD @ app/browser
[EAF] Running git pull origin master @ app/browser
From https://github.com/emacs-eaf/eaf-browser
 * branch            master     -> FETCH_HEAD
Already up to date.

[EAF] Installing dependencies for installed applications
[EAF] Finished installing applications and their dependencies

[EAF] Please ensure the following are added to your init.el:
(require 'eaf-browser)
[EAF] ------------------------------------------
[EAF] install-eaf.py finished.

[EAF] Please run 'git pull ; ./install-eaf.py' (M-x eaf-install-and-update) to update EAF, applications and their dependencies.
[EAF] Use the flag '--install-new-apps' to install previously uninstalled or new apps.
```
My eaf config:
```emacs-lisp
(use-package eaf
  :load-path "~/.emacs.d/site-lisp/emacs-application-framework"
  :after exec-path-from-shell
  :bind (("C-c M-o" . eaf-open-url-at-point)
         ("\e\e b"  . eaf-open-browser-with-history))
  :config
  (require 'eaf-browser)
  (when (display-graphic-p)
    (require 'eaf-all-the-icons))
  (setq eaf-start-python-process-when-require nil)
  (setq eaf-browser-default-search-engine "google")
  (setq eaf-browser-continue-where-left-off t)
  (setq eaf-chrome-bookmark-file "~/Library/Application Support/Microsoft Edge/Default/Bookmarks")
  (setq eaf-browser-chrome-history-file "~/Library/Caches/Microsoft Edge/Default/Cache")
  (setq eaf-browser-dark-mode t)
  (setq eaf-browser-enable-adblocker t)
  (setq eaf-browser-enable-autofill t)
  (setq eaf-browser-translate-language "zh-CN")
  (defalias 'eafs #'eaf-search-it)
  (eaf-bind-key nil "M-q" eaf-browser-keybinding) ;; unbind, see more in the Wiki
  (eaf-bind-key eaf-previous-buffer-same-app  "E" eaf-browser-keybinding)
  (eaf-bind-key eaf-next-buffer-same-app      "R" eaf-browser-keybinding)
  (eaf-bind-key eaf-py-proxy-history_backward "S" eaf-browser-keybinding)
  (eaf-bind-key eaf-py-proxy-history_forward  "D" eaf-browser-keybinding)
  (eaf-bind-key eaf-py-proxy-insert_or_recover_prev_close_page "X" eaf-browser-keybinding)
  (eaf-bind-key eaf-get-path-or-url "s-/" eaf-browser-keybinding)
  )
```

When I run `eaf-open-browser-with-history` command, I cannot open the browser with the following error:
```
Traceback (most recent call last):
  File "/Users/randolph/.emacs.d/site-lisp/emacs-application-framework/eaf.py", line 25, in <module>
    from PyQt6 import QtWebEngineWidgets as NeverUsed # noqa
ModuleNotFoundError: No module named 'PyQt6'

Process *eaf* exited abnormally with code 1
```

Please help to look at it. Thanks a lot.

**Comment by manateelazycat** [comment]
> I encountered the same issue today when I reinstalled emacs and eaf in my Macbook Pro.
> 
> MacOS version: 12.3.1 Emacs version: GNU Emacs 29.0.50 (build 1, x86_64-apple-darwin21.4.0, NS appkit-2113.40 Version 12.3.1 (Build 21E258)) of 2022-05-02 Python version: Python 3.9.12 (new venv environment without any package installed)
> 
> `./install-eaf.py` results:
> 
> ```
> $ ./install-eaf.py
> [EAF] ------------------------------------------
> [EAF] Installing core dependencies
> [EAF] Running pip install epc tld lxml mac-app-frontmost PyQt6 PyQt6-Qt6 PyQt6-sip PyQt6-WebEngine PyQt6-WebEngine-Qt6 @ /Users/randolph/.emacs.d/site-lisp/emacs-application-framework
> Requirement already satisfied: epc in /Users/randolph/.venv/py39/lib/python3.9/site-packages (0.0.5)
> Requirement already satisfied: tld in /Users/randolph/.venv/py39/lib/python3.9/site-packages (0.12.6)
> Requirement already satisfied: lxml in /Users/randolph/.venv/py39/lib/python3.9/site-packages (4.8.0)
> Requirement already satisfied: mac-app-frontmost in /Users/randolph/.venv/py39/lib/python3.9/site-packages (2020.12.3)
> Requirement already satisfied: PyQt6 in /Users/randolph/.venv/py39/lib/python3.9/site-packages (6.3.0)
> Requirement already satisfied: PyQt6-Qt6 in /Users/randolph/.venv/py39/lib/python3.9/site-packages (6.3.0)
> Requirement already satisfied: PyQt6-sip in /Users/randolph/.venv/py39/lib/python3.9/site-packages (13.3.1)
> Requirement already satisfied: PyQt6-WebEngine in /Users/randolph/.venv/py39/lib/python3.9/site-packages (6.3.0)
> Requirement already satisfied: PyQt6-WebEngine-Qt6 in /Users/randolph/.venv/py39/lib/python3.9/site-packages (6.3.0)
> Requirement already satisfied: sexpdata>=0.0.3 in /Users/randolph/.venv/py39/lib/python3.9/site-packages (from epc) (0.0.3)
> [EAF] Finished installing core dependencies
> [EAF] ------------------------------------------
> [EAF] ------------------------------------------
> [EAF] Installing application dependencies
> 
> [EAF] Updating browser to newest version...
> [EAF] Running git branch @ app/browser
> [EAF] Running git symbolic-ref HEAD @ app/browser
> [EAF] Running git pull origin master @ app/browser
> From https://github.com/emacs-eaf/eaf-browser
>  * branch            master     -> FETCH_HEAD
> Already up to date.
> 
> [EAF] Installing dependencies for installed applications
> [EAF] Finished installing applications and their dependencies
> 
> [EAF] Please ensure the following are added to your init.el:
> (require 'eaf-browser)
> [EAF] ------------------------------------------
> [EAF] install-eaf.py finished.
> 
> [EAF] Please run 'git pull ; ./install-eaf.py' (M-x eaf-install-and-update) to update EAF, applications and their dependencies.
> [EAF] Use the flag '--install-new-apps' to install previously uninstalled or new apps.
> ```
> 
> My eaf config:
> 
> ```emacs-lisp
> (use-package eaf
>   :load-path "~/.emacs.d/site-lisp/emacs-application-framework"
>   :after exec-path-from-shell
>   :bind (("C-c M-o" . eaf-open-url-at-point)
>          ("\e\e b"  . eaf-open-browser-with-history))
>   :config
>   (require 'eaf-browser)
>   (when (display-graphic-p)
>     (require 'eaf-all-the-icons))
>   (setq eaf-start-python-process-when-require nil)
>   (setq eaf-browser-default-search-engine "google")
>   (setq eaf-browser-continue-where-left-off t)
>   (setq eaf-chrome-bookmark-file "~/Library/Application Support/Microsoft Edge/Default/Bookmarks")
>   (setq eaf-browser-chrome-history-file "~/Library/Caches/Microsoft Edge/Default/Cache")
>   (setq eaf-browser-dark-mode t)
>   (setq eaf-browser-enable-adblocker t)
>   (setq eaf-browser-enable-autofill t)
>   (setq eaf-browser-translate-language "zh-CN")
>   (defalias 'eafs #'eaf-search-it)
>   (eaf-bind-key nil "M-q" eaf-browser-keybinding) ;; unbind, see more in the Wiki
>   (eaf-bind-key eaf-previous-buffer-same-app  "E" eaf-browser-keybinding)
>   (eaf-bind-key eaf-next-buffer-same-app      "R" eaf-browser-keybinding)
>   (eaf-bind-key eaf-py-proxy-history_backward "S" eaf-browser-keybinding)
>   (eaf-bind-key eaf-py-proxy-history_forward  "D" eaf-browser-keybinding)
>   (eaf-bind-key eaf-py-proxy-insert_or_recover_prev_close_page "X" eaf-browser-keybinding)
>   (eaf-bind-key eaf-get-path-or-url "s-/" eaf-browser-keybinding)
>   )
> ```
> 
> When I run `eaf-open-browser-with-history` command, I cannot open the browser with the following error:
> 
> ```
> Traceback (most recent call last):
>   File "/Users/randolph/.emacs.d/site-lisp/emacs-application-framework/eaf.py", line 25, in <module>
>     from PyQt6 import QtWebEngineWidgets as NeverUsed # noqa
> ModuleNotFoundError: No module named 'PyQt6'
> 
> Process *eaf* exited abnormally with code 1
> ```
> 
> Please help to look at it. Thanks a lot.

Don't use venv

**Comment by Dima-369** [comment]
Hmm, the error below I get is so frustrating because it works in a regular terminal (invoked by `python pyqt-code.py`), but inside Emacs it throws the error if any PyQt version is used:

```
qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: cocoa, minimal, offscreen.
```

**Comment by Dima-369** [comment]
I noticed that this recent commit fixes the `xcb` error above: https://github.com/emacs-eaf/emacs-application-framework/commit/318ff37563d21fa1fe08f230750c63122d40e7e2 so I can use EAF once again.

The `(setenv "QT_QPA_PLATFORM" "xcb")` call in `eaf.el` was the reason that it worked in the terminal, but not inside Emacs.

**Comment by lynnux** [comment]
刚才win10上装的gitee上的eaf也有这样的问题，浏览器完全没反应，打开*eaf*提示
```
qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""
This application failed to start because no Qt platform plugin could be initialized
```
等，修改eaf.el把`(unless (eq system-type 'darwin) (setenv "QT_QPA_PLATFORM" "xcb"))`，重开提示又不一样了：
```
qt.webenginecontext: 

GL Type: desktop
Surface Type: OpenGL
Surface Profile: CompatibilityProfile
Surface Version: 4.6
QSG RHI Backend: OpenGL
Using Supported QSG Backend: yes
Using Software Dynamic GL: no
Using Multithreaded OpenGL: yes

Init Parameters:
  *  application-name python 
  *  browser-subprocess-path C:\Users\lynnux\AppData\Roaming\Python\Python310\site-packages\PyQt6\Qt6\bin\QtWebEngineProcess.exe 
  *  create-default-gl-context  
  *  disable-es3-gl-context  
  *  disable-features ConsolidatedMovementXY,InstalledApp,BackgroundFetch,WebOTP,WebPayments,WebUSB,PictureInPicture 
  *  disable-speech-api  
  *  disable-web-security  
  *  enable-features NetworkServiceInProcess,TracingServiceInProcess 
  *  enable-threaded-compositing  
  *  in-process-gpu  
  *  use-gl desktop 

qt.webenginecontext: 

GL Type: desktop
Surface Type: OpenGL
Surface Profile: CompatibilityProfile
Surface Version: 4.6
QSG RHI Backend: OpenGL
Using Supported QSG Backend: yes
Using Software Dynamic GL: no
Using Multithreaded OpenGL: yes

Init Parameters:
  *  application-name python 
  *  browser-subprocess-path C:\Users\lynnux\AppData\Roaming\Python\Python310\site-packages\PyQt6\Qt6\bin\QtWebEngineProcess.exe 
  *  create-default-gl-context  
  *  disable-es3-gl-context  
  *  disable-features ConsolidatedMovementXY,InstalledApp,BackgroundFetch,WebOTP,WebPayments,WebUSB,PictureInPicture 
  *  disable-speech-api  
  *  disable-web-security  
  *  enable-features NetworkServiceInProcess,TracingServiceInProcess 
  *  enable-threaded-compositing  
  *  in-process-gpu  
  *  use-gl desktop 


Process *eaf*<1> exited abnormally with code 9

Process *eaf* exited abnormally with code 9

```

**Comment by manateelazycat** [comment]
> 刚才win10上装的gitee上的eaf也有这样的问题，浏览器完全没反应，打开_eaf_提示
> 
> ```
> qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""
> This application failed to start because no Qt platform plugin could be initialized
> ```
> 
> 等，修改eaf.el把`(unless (eq system-type 'darwin) (setenv "QT_QPA_PLATFORM" "xcb"))`删除，重开提示又不一样了：
> 
> ```
> qt.webenginecontext: 
> 
> GL Type: desktop
> Surface Type: OpenGL
> Surface Profile: CompatibilityProfile
> Surface Version: 4.6
> QSG RHI Backend: OpenGL
> Using Supported QSG Backend: yes
> Using Software Dynamic GL: no
> Using Multithreaded OpenGL: yes
> 
> Init Parameters:
>   *  application-name python 
>   *  browser-subprocess-path C:\Users\lynnux\AppData\Roaming\Python\Python310\site-packages\PyQt6\Qt6\bin\QtWebEngineProcess.exe 
>   *  create-default-gl-context  
>   *  disable-es3-gl-context  
>   *  disable-features ConsolidatedMovementXY,InstalledApp,BackgroundFetch,WebOTP,WebPayments,WebUSB,PictureInPicture 
>   *  disable-speech-api  
>   *  disable-web-security  
>   *  enable-features NetworkServiceInProcess,TracingServiceInProcess 
>   *  enable-threaded-compositing  
>   *  in-process-gpu  
>   *  use-gl desktop 
> 
> qt.webenginecontext: 
> 
> GL Type: desktop
> Surface Type: OpenGL
> Surface Profile: CompatibilityProfile
> Surface Version: 4.6
> QSG RHI Backend: OpenGL
> Using Supported QSG Backend: yes
> Using Software Dynamic GL: no
> Using Multithreaded OpenGL: yes
> 
> Init Parameters:
>   *  application-name python 
>   *  browser-subprocess-path C:\Users\lynnux\AppData\Roaming\Python\Python310\site-packages\PyQt6\Qt6\bin\QtWebEngineProcess.exe 
>   *  create-default-gl-context  
>   *  disable-es3-gl-context  
>   *  disable-features ConsolidatedMovementXY,InstalledApp,BackgroundFetch,WebOTP,WebPayments,WebUSB,PictureInPicture 
>   *  disable-speech-api  
>   *  disable-web-security  
>   *  enable-features NetworkServiceInProcess,TracingServiceInProcess 
>   *  enable-threaded-compositing  
>   *  in-process-gpu  
>   *  use-gl desktop 
> 
> 
> Process *eaf*<1> exited abnormally with code 9
> 
> Process *eaf* exited abnormally with code 9
> ```
看我另外一个 issue 的回复，先把依赖安装好。

**Comment by patrolli** [comment]
> > 刚才win10上装的gitee上的eaf也有这样的问题，浏览器完全没反应，打开_eaf_提示
> > ```
> > qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""
> > This application failed to start because no Qt platform plugin could be initialized
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 等，修改eaf.el把`(unless (eq system-type 'darwin) (setenv "QT_QPA_PLATFORM" "xcb"))`删除，重开提示又不一样了：
> > ```
> > qt.webenginecontext: 
> > 
> > GL Type: desktop
> > Surface Type: OpenGL
> > Surface Profile: CompatibilityProfile
> > Surface Version: 4.6
> > QSG RHI Backend: OpenGL
> > Using Supported QSG Backend: yes
> > Using Software Dynamic GL: no
> > Using Multithreaded OpenGL: yes
> > 
> > Init Parameters:
> >   *  application-name python 
> >   *  browser-subprocess-path C:\Users\lynnux\AppData\Roaming\Python\Python310\site-packages\PyQt6\Qt6\bin\QtWebEngineProcess.exe 
> >   *  create-default-gl-context  
> >   *  disable-es3-gl-context  
> >   *  disable-features ConsolidatedMovementXY,InstalledApp,BackgroundFetch,WebOTP,WebPayments,WebUSB,PictureInPicture 
> >   *  disable-speech-api  
> >   *  disable-web-security  
> >   *  enable-features NetworkServiceInProcess,TracingServiceInProcess 
> >   *  enable-threaded-compositing  
> >   *  in-process-gpu  
> >   *  use-gl desktop 
> > 
> > qt.webenginecontext: 
> > 
> > GL Type: desktop
> > Surface Type: OpenGL
> > Surface Profile: CompatibilityProfile
> > Surface Version: 4.6
> > QSG RHI Backend: OpenGL
> > Using Supported QSG Backend: yes
> > Using Software Dynamic GL: no
> > Using Multithreaded OpenGL: yes
> > 
> > Init Parameters:
> >   *  application-name python 
> >   *  browser-subprocess-path C:\Users\lynnux\AppData\Roaming\Python\Python310\site-packages\PyQt6\Qt6\bin\QtWebEngineProcess.exe 
> >   *  create-default-gl-context  
> >   *  disable-es3-gl-context  
> >   *  disable-features ConsolidatedMovementXY,InstalledApp,BackgroundFetch,WebOTP,WebPayments,WebUSB,PictureInPicture 
> >   *  disable-speech-api  
> >   *  disable-web-security  
> >   *  enable-features NetworkServiceInProcess,TracingServiceInProcess 
> >   *  enable-threaded-compositing  
> >   *  in-process-gpu  
> >   *  use-gl desktop 
> > 
> > 
> > Process *eaf*<1> exited abnormally with code 9
> > 
> > Process *eaf* exited abnormally with code 9
> > ```
> 
> 看我另外一个 issue 的回复，先把依赖安装好。

请问是哪一个 issue，我在 win10 上也遇到了同样的问题。"qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in "

**Comment by ameliesc** [comment]
I installed the most updated version of eaf and unfortunately still have this issue.
