### ISSUE TITLE
Issues with EAF window positioning and size resulting in overlapped buffers

### ISSUE THREAD

**Issue by Dima-369** [emacs-eaf/emacs-application-framework#970]
On the latest `master` with Qt6, the EAF buffer is not correctly aligned to the Emacs buffers, overlapping other buffers or not showing everything.

I am on `GNU Emacs 28.1 (build 2, x86_64-apple-darwin18.7.0, NS appkit-1671.60 Version 10.14.6 (Build 18G9216)) of 2022-04-13` on `macOS 10.14.6`.

I tested `eaf-get-window-allocation` and it returns correct values, but the positioning and width/height are still incorrect?

See here:

![image](https://user-images.githubusercontent.com/15002298/167239926-e02898ae-b073-4ea7-9be8-c21604b0c5f4.png)

Here I moved the EAF buffer to the top left:

![image](https://user-images.githubusercontent.com/15002298/167239942-6bf79307-415a-4703-b74f-03c334d2bd60.png)

**Comment by manateelazycat** [comment]
I haven't macOS for test, sorry I can't help you.

**Comment by Dima-369** [comment]
I found a fix. After `eaf` is loaded in, resetting the environment variables displays the window correctly:

```
(setenv "QT_AUTO_SCREEN_SCALE_FACTOR")
(setenv "QT_SCALE_FACTOR")
(setenv "QT_FONT_DPI")
```

I suppose the entire logic in `eaf--follow-system-dpi` can be avoided when on macOS except for the `QT_DEUG_PLUGINS` env. I suppose some kind of scaling is applied to the window size which is why it did not display correctly for me.

PS: It should be `QT_DEBUG_PLUGINS` in `eaf--follow-system-dpi` ;)

**Comment by manateelazycat** [comment]
> I found a fix. After `eaf` is loaded in, resetting the environment variables displays the window correctly:
> 
> ```
> (setenv "QT_AUTO_SCREEN_SCALE_FACTOR")
> (setenv "QT_SCALE_FACTOR")
> (setenv "QT_FONT_DPI")
> ```
> 
> I suppose the entire logic in `eaf--follow-system-dpi` can be avoided when on macOS except for the `QT_DEUG_PLUGINS` env. I suppose some kind of scaling is applied to the window size which is why it did not display correctly for me.
> 
> PS: It should be `QT_DEBUG_PLUGINS` in `eaf--follow-system-dpi` ;)

Good news, @Dima-369 Can you send a PR to fix this ? Thanks.

**Comment by Dima-369** [comment]
> Can you send a PR to fix this?

Here you go: https://github.com/emacs-eaf/emacs-application-framework/pull/973
