### ISSUE TITLE
Failing on installing pyqtwebengine (due to M1?)

### ISSUE THREAD

**Issue by PalaChen** [emacs-eaf/emacs-application-framework#971]
https://github.com/emacs-eaf/emacs-application-framework/issues/868

download code
git clone --depth=1 -b qt5-legacy https://github.com/emacs-eaf/emacs-application-framework.git ~/.emacs.d/site-lisp/emacs-application-framework/

use commands:

arch -x86_64 python ./install-eaf.py
arch: posix_spawnp: python: Bad CPU type in executable

use 
python ./install-eaf.py
```
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by manateelazycat** [comment]
I haven't macOS, can't help you, sorry.

**Comment by vohv** [comment]
Do not use arm-only python. Use the universal version. I also meet this problem while using python installed by homebrew.

https://www.python.org/downloads/macos/

```bash
file /usr/local/bin/python3
/usr/local/bin/python3: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit executable x86_64] [arm64:Mach-O 64-bit executable arm64]
/usr/local/bin/python3 (for architecture x86_64):	Mach-O 64-bit executable x86_64
/usr/local/bin/python3 (for architecture arm64):	Mach-O 64-bit executable arm64
```

**Comment by manateelazycat** [comment]
> Do not use arm-only python. Use the universal version. I also meet this problem while using python installed by homebrew.
> 
> https://www.python.org/downloads/macos/
> 
> ```shell
> $ file /usr/local/bin/python3
> /usr/local/bin/python3: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit executable x86_64] [arm64:Mach-O 64-bit executable arm64]
> /usr/local/bin/python3 (for architecture x86_64):	Mach-O 64-bit executable x86_64
> /usr/local/bin/python3 (for architecture arm64):	Mach-O 64-bit executable arm64
> ```
> 
> ```shell
> $ file /opt/homebrew/bin/python3
> /opt/homebrew/bin/python3: Mach-O 64-bit executable arm64
> ```

This looks good.
