### ISSUE TITLE
[EAF] Running npm install 出错，安装不成功

### ISSUE THREAD

**Issue by HomelandScenery** [emacs-eaf/emacs-application-framework#975]
**Describe the bug**

[EAF] Running npm install @ /Users/fazhao/.emacs.d/site-lisp/emacs-application-framework/app/file-manager
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: @vue/cli-plugin-eslint@4.5.13
npm ERR! Found: eslint@7.32.0
npm ERR! node_modules/eslint
npm ERR!   dev eslint@"^7.32.0" from the root project
npm ERR!   peer eslint@"^6.2.0 || ^7.0.0" from eslint-plugin-vue@7.16.0
npm ERR!   node_modules/eslint-plugin-vue
npm ERR!     dev eslint-plugin-vue@"^7.16.0" from the root project
npm ERR!   1 more (vue-eslint-parser)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer eslint@">= 1.6.0 < 7.0.0" from @vue/cli-plugin-eslint@4.5.13
npm ERR! node_modules/@vue/cli-plugin-eslint
npm ERR!   dev @vue/cli-plugin-eslint@"^4.5.13" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: eslint@6.8.0
npm ERR! node_modules/eslint
npm ERR!   peer eslint@">= 1.6.0 < 7.0.0" from @vue/cli-plugin-eslint@4.5.13
npm ERR!   node_modules/@vue/cli-plugin-eslint
npm ERR!     dev @vue/cli-plugin-eslint@"^4.5.13" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /Users/fazhao/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/fazhao/.npm/_logs/2022-05-19T07_57_24_664Z-debug-0.log

**To Reproduce**
最新版本，执行 ./install-eaf.py，前面的依赖都已经正常安装，就是到了[EAF] Running npm install这一步，就显示错误。

**Versions (please complete the following info):**
GNU Emacs 27.2 (build 1, x86_64-apple-darwin20.5.0, Carbon Version 164 AppKit 2022.5) of 2021-06-14
npm -version  8.6.0
 vue --version  @vue/cli 5.0.4

**Error logs**
[EAF/file-manager] Opening /Users/fazhao/.config/
[EAF/file-manager] Buffer id 'ea5a-8706-636c-0b25-db4e-e1cb-79fe' not exists, rebuild EAF buffer. [101 times]
[EAF] Buffer id 'ea5a-8706-636c-0b25-db4e-e1cb-79fe' not exists, rebuild EAF buffer.

**Screenshots**
<img width="1015" alt="image" src="https://user-images.githubusercontent.com/19407813/169248680-075a8fd5-907b-483f-93f6-8ac8962d878a.png">

**Additional context**
已经挂梯子，能正常访问下载。

**Comment by MatthewZMD** [comment]
依赖冲突只能是你本地环境的问题，建议跟着错误信息排查一下，实在爱莫能助

**Comment by SuperMMX** [comment]
第一次装 eaf，也碰到了同样的问题。

```
npm ERR! code ERESOLVE   
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!                 
npm ERR! While resolving: vue-demo@0.1.0
npm ERR! Found: eslint@7.32.0
npm ERR! node_modules/eslint
npm ERR!   dev eslint@"^7.32.0" from the root project
npm ERR!                 
npm ERR! Could not resolve dependency:
npm ERR! peer eslint@">= 1.6.0 < 7.0.0" from @vue/cli-plugin-eslint@4.5.17
npm ERR! node_modules/@vue/cli-plugin-eslint
npm ERR!   dev @vue/cli-plugin-eslint@"^4.5.13" from the root project
npm ERR!                 
```

参看这个 https://github.com/vuejs/vue-cli/issues/6374, 旧的 vue/cli-plugin-eslint 不支持新的 eslint 7。需要把 @vue/cli-plugin-eslint 的版本号改成 5.0.4 (现在最新的)。然后就没问题了。

修改太小，就不提 PR 了。

**Comment by HomelandScenery** [comment]
> 

try vue upgrade eslint -t v5.0.0-alpha.7 to update plugin

走到这步，怎么解决呢？我是小白😅

**Comment by SuperMMX** [comment]
出错之后，其实前面的 system / python dependencies 基本上已经装完了。这时候似乎不能再用 install-eaf.py 继续装，只能手动来。

把 "package.json" 中  @vue/cli-plugin-eslint 的版本号改成 "5.0.4"，然后 `npm install`、`npm build`，就没问题了。

其他几个 app 也可能有同样的问题 ，一个一个用同样的方法解决就可以了。

**Comment by MatthewZMD** [comment]
> 出错之后，其实前面的 system / python dependencies 基本上已经装完了。这时候似乎不能再用 install-eaf.py 继续装，只能手动来。
> 
可以./install-eaf.py --force

**Comment by liuyinz** [comment]
同样的错。

**Comment by manateelazycat** [comment]
最新版已经修复了 npm 的安装问题。

**Comment by arstum** [comment]
> 最新版已经修复了 npm 的安装问题。

display the same error in latest version
