### ISSUE TITLE
使用 eaf-file-manager 的时候图标无法正常显示。

### ISSUE THREAD

**Issue by gcclll** [emacs-eaf/emacs-application-framework#986]
**Describe the bug**

在Mac上使用 eaf-file-manager 的时候图标无法正常显示。

**To Reproduce**
通过 eaf-file-manager 打开文件管理器：
![image](https://user-images.githubusercontent.com/17329983/174198793-9001d996-8bf6-467a-bde0-95f436140031.png)

**Expected behavior**
希望能正常展示，或者有没什么参数可以手动控制不显示(那个无效图标看着挺别扭的)

**Versions (please complete the following info):**
 - Distro and DE/WM: MacOS Monterey 12.1
 - Versions of Dependencies:
 Python 3.10.4 
qt: stable 6.3.0 (bottled), HEAD
 - M-x emacs-version: GNU Emacs 29.0.50 (build 1, x86_64-apple-darwin21.2.0, NS appkit-2113.20 Version 12.1 (Build 21C52)) of 2021-12-30

**Screenshots**
![image](https://user-images.githubusercontent.com/17329983/174199794-c637029c-72ab-45fa-8d71-55b5886cf5e2.png)

![image](https://user-images.githubusercontent.com/17329983/174199809-8b564796-0858-4d1c-b078-cb658537b350.png)

**Comment by manateelazycat** [comment]
现在Qt只能从Linux Gnome/KDE 下读取图标主题， https://github.com/emacs-eaf/eaf-file-manager/commit/5b6eb3505113afc62b092a5b4cb1cae73f0af17f 我把我系统上能够扫描到的图标都加进去了。

如果发现有些文件没有图标，请把文件上传一下，我重新更新图标即可。
